var searchData=
[
  ['navierstokesassemblerale_3071',['NavierStokesAssemblerALE',['../classNavierStokesAssemblerALE.html',1,'']]],
  ['navierstokesassemblerbase_3072',['NavierStokesAssemblerBase',['../classNavierStokesAssemblerBase.html',1,'']]],
  ['navierstokesbase_3073',['NavierStokesBase',['../classNavierStokesBase.html',1,'']]],
  ['navierstokesbase_3c_20dim_2c_20linearalgebra_3a_3adistributed_3a_3avector_3c_20double_20_3e_2c_20indexset_20_3e_3074',['NavierStokesBase&lt; dim, LinearAlgebra::distributed::Vector&lt; double &gt;, IndexSet &gt;',['../classNavierStokesBase.html',1,'']]],
  ['navierstokesbase_3c_20dim_2c_20trilinoswrappers_3a_3ampi_3a_3ablockvector_2c_20std_3a_3avector_3c_20indexset_20_3e_20_3e_3075',['NavierStokesBase&lt; dim, TrilinosWrappers::MPI::BlockVector, std::vector&lt; IndexSet &gt; &gt;',['../classNavierStokesBase.html',1,'']]],
  ['navierstokesbase_3c_20dim_2c_20trilinoswrappers_3a_3ampi_3a_3avector_2c_20indexset_20_3e_3076',['NavierStokesBase&lt; dim, TrilinosWrappers::MPI::Vector, IndexSet &gt;',['../classNavierStokesBase.html',1,'']]],
  ['navierstokesfunctiondefined_3077',['NavierStokesFunctionDefined',['../classNavierStokesFunctionDefined.html',1,'']]],
  ['navierstokesoperatorbase_3078',['NavierStokesOperatorBase',['../classNavierStokesOperatorBase.html',1,'']]],
  ['navierstokespressurefunctiondefined_3079',['NavierStokesPressureFunctionDefined',['../classNavierStokesPressureFunctionDefined.html',1,'']]],
  ['navierstokesscratchdata_3080',['NavierStokesScratchData',['../classNavierStokesScratchData.html',1,'']]],
  ['navierstokessupgpspgoperator_3081',['NavierStokesSUPGPSPGOperator',['../classNavierStokesSUPGPSPGOperator.html',1,'']]],
  ['navierstokestransientsupgpspgoperator_3082',['NavierStokesTransientSUPGPSPGOperator',['../classNavierStokesTransientSUPGPSPGOperator.html',1,'']]],
  ['newtonian_3083',['Newtonian',['../classNewtonian.html',1,'']]],
  ['newtonnonlinearsolver_3084',['NewtonNonLinearSolver',['../classNewtonNonLinearSolver.html',1,'']]],
  ['nitsche_3085',['Nitsche',['../classParameters_1_1Nitsche.html',1,'Parameters']]],
  ['nitscheobject_3086',['NitscheObject',['../classParameters_1_1NitscheObject.html',1,'Parameters']]],
  ['nonlinearsolver_3087',['NonLinearSolver',['../classNonLinearSolver.html',1,'NonLinearSolver&lt; VectorType &gt;'],['../structParameters_1_1NonLinearSolver.html',1,'Parameters::NonLinearSolver']]],
  ['nonnewtonian_3088',['NonNewtonian',['../structParameters_1_1NonNewtonian.html',1,'Parameters']]],
  ['normaldistribution_3089',['NormalDistribution',['../classNormalDistribution.html',1,'']]],
  ['nsboundaryconditions_3090',['NSBoundaryConditions',['../classBoundaryConditions_1_1NSBoundaryConditions.html',1,'BoundaryConditions']]],
  ['nsboundaryfunctions_3091',['NSBoundaryFunctions',['../classBoundaryConditions_1_1NSBoundaryFunctions.html',1,'BoundaryConditions']]],
  ['nspressureboundaryfunctions_3092',['NSPressureBoundaryFunctions',['../classBoundaryConditions_1_1NSPressureBoundaryFunctions.html',1,'BoundaryConditions']]]
];
