var searchData=
[
  ['navierstokesassemblerbase_3281',['NavierStokesAssemblerBase',['../classNavierStokesAssemblerBase.html',1,'']]],
  ['navierstokesbase_3282',['NavierStokesBase',['../classNavierStokesBase.html',1,'']]],
  ['navierstokesbase_3c_20dim_2c_20linearalgebra_3a_3adistributed_3a_3avector_3c_20double_20_3e_2c_20indexset_20_3e_3283',['NavierStokesBase&lt; dim, LinearAlgebra::distributed::Vector&lt; double &gt;, IndexSet &gt;',['../classNavierStokesBase.html',1,'']]],
  ['navierstokesbase_3c_20dim_2c_20trilinoswrappers_3a_3ampi_3a_3ablockvector_2c_20std_3a_3avector_3c_20indexset_20_3e_20_3e_3284',['NavierStokesBase&lt; dim, TrilinosWrappers::MPI::BlockVector, std::vector&lt; IndexSet &gt; &gt;',['../classNavierStokesBase.html',1,'']]],
  ['navierstokesbase_3c_20dim_2c_20trilinoswrappers_3a_3ampi_3a_3avector_2c_20indexset_20_3e_3285',['NavierStokesBase&lt; dim, TrilinosWrappers::MPI::Vector, IndexSet &gt;',['../classNavierStokesBase.html',1,'']]],
  ['navierstokesfunctiondefined_3286',['NavierStokesFunctionDefined',['../classNavierStokesFunctionDefined.html',1,'']]],
  ['navierstokesoperatorbase_3287',['NavierStokesOperatorBase',['../classNavierStokesOperatorBase.html',1,'']]],
  ['navierstokespressurefunctiondefined_3288',['NavierStokesPressureFunctionDefined',['../classNavierStokesPressureFunctionDefined.html',1,'']]],
  ['navierstokesscratchdata_3289',['NavierStokesScratchData',['../classNavierStokesScratchData.html',1,'']]],
  ['navierstokessupgpspgoperator_3290',['NavierStokesSUPGPSPGOperator',['../classNavierStokesSUPGPSPGOperator.html',1,'']]],
  ['navierstokestransientsupgpspgoperator_3291',['NavierStokesTransientSUPGPSPGOperator',['../classNavierStokesTransientSUPGPSPGOperator.html',1,'']]],
  ['navierstokesvofassemblerevaporation_3292',['NavierStokesVOFAssemblerEvaporation',['../classNavierStokesVOFAssemblerEvaporation.html',1,'']]],
  ['newtonian_3293',['Newtonian',['../classNewtonian.html',1,'']]],
  ['newtonnonlinearsolver_3294',['NewtonNonLinearSolver',['../classNewtonNonLinearSolver.html',1,'']]],
  ['nitsche_3295',['Nitsche',['../classParameters_1_1Nitsche.html',1,'Parameters']]],
  ['nitscheobject_3296',['NitscheObject',['../classParameters_1_1NitscheObject.html',1,'Parameters']]],
  ['nonlinearsolver_3297',['NonLinearSolver',['../classNonLinearSolver.html',1,'NonLinearSolver&lt; VectorType &gt;'],['../structParameters_1_1NonLinearSolver.html',1,'Parameters::NonLinearSolver']]],
  ['nonnewtonian_3298',['NonNewtonian',['../structParameters_1_1NonNewtonian.html',1,'Parameters']]],
  ['normaldistribution_3299',['NormalDistribution',['../classNormalDistribution.html',1,'']]],
  ['nsboundaryconditions_3300',['NSBoundaryConditions',['../classBoundaryConditions_1_1NSBoundaryConditions.html',1,'BoundaryConditions']]],
  ['nsboundaryfunctions_3301',['NSBoundaryFunctions',['../classBoundaryConditions_1_1NSBoundaryFunctions.html',1,'BoundaryConditions']]],
  ['nspressureboundaryfunctions_3302',['NSPressureBoundaryFunctions',['../classBoundaryConditions_1_1NSPressureBoundaryFunctions.html',1,'BoundaryConditions']]]
];
