Developer documentation for the Lethe open-source library: NavierStokesBase< dim, VectorType, DofsType > Class Template Reference
NavierStokesBase< dim, VectorType, DofsType > Class Template Reference abstract
#include <navier_stokes_base.h>
Protected Member Functions
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual VectorType & get_evaluation_point () override
Getter methods to get the private attributes for the physic currently solved.
virtual VectorType & get_local_evaluation_point () override
virtual VectorType & get_newton_update () override
virtual VectorType & get_present_solution () override
virtual VectorType & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
void finish_simulation ()
finish_simulation Finish the simulation by calling all the post-processing elements that are required
virtual void postprocess (bool first_iteration)
postprocess Post-process simulation after an iteration
virtual void setup_dofs ()
setup_dofs
virtual void set_initial_condition (Parameters::InitialConditionType initial_condition_type, bool restart=false)
set_initial_conditions
virtual void finish_time_step ()
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
virtual void percolate_time_vectors_fd ()
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
void finish_simulation_fd ()
finish_simulation Finishes the simulation for fluid dynamics by calling the post-processing elements that are required
virtual void postprocess_fd (bool first_iteration)
postprocess Post-process fluid dynamics after an iteration
virtual void setup_dofs_fd ()=0
setup_dofs
virtual void update_multiphysics_time_average_solution ()=0
Update the time average velocity field solution.
virtual void set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart=false)=0
void postprocessing_forces (const VectorType &evaluation_point)
postprocessing_forces Post-processing function Outputs the forces acting on each boundary condition
void postprocessing_torques (const VectorType &evaluation_point)
postprocessing_torques Post-processing function Outputs the torque acting on each boundary condition
virtual void dynamic_flow_control ()
dynamic_flow_control If set to enable, dynamic_flow_control allows to control the flow by executing space-average velocity and beta coefficient force calculation at each time step.
virtual void iterate ()
iterate Do a regular CFD iteration
void box_refine_mesh ()
Allow the initial refinement of all cells of the principal mesh that are partially contained in one of the cells of the box refinement mesh given in the parameter.
virtual void refine_mesh ()
Allow the refinement of the mesh according to one of the 2 methods proposed.
void refine_mesh_kelly ()
Allow the refinement of the mesh based on the Kelly error estimator. See : https://www.dealii.org/current/doxygen/deal.II/classKellyErrorEstimator.html for more information on the Kelly error estimator.
void refine_mesh_uniform ()
Allow the uniform refinement of all the mesh.
virtual void read_checkpoint ()
read_checkpoint
void set_nodal_values ()
set_nodal_values Set the nodal values of velocity and pressure
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
Check if a specifique boundary condition exist.
void establish_solid_domain (const bool non_zero_constraints)
Turns regions of the mesh where the material_id=1 to a solid block by injecting it into the constraints This is achieved by imposing $\mathbf{u}=0$ within the cells which have a material_id=1. In addition, solid cells which are not connected to the fluid by any means also get a pressure dirichlet boundary condition which fixes the pressure to 0. This ensures that the linear system is well-posed. Right now, this routine only supports the usage of 1 solid domain, but eventually it could be extended to more than one. By default, the fluid domain is assumed to have a material_id=0 and the rest of the domains have a material_id>0.
virtual void write_checkpoint ()
write_checkpoint
void write_output_results (const VectorType &solution)
write_output_results Post-processing as parallel VTU files
virtual void output_field_hook (DataOut< dim > &)
output_field_hook This function is to be redefined in specialized classes to adapt the output to each solver.
void write_output_forces ()
write_output_forces Writes the forces per boundary condition to a text file output
void write_output_torques ()
write_output_torques Writes the torques per boundary condition to a text file output
void rescale_pressure_dofs_in_newton_update ()
rescale_pressure_dofs_in_newton_update This function is used to rescale pressure DOFs in the newton correction
VectorType init_temporary_vector ()
init_temporary_vector This function initializes correctly a temporary vector depending on the vector type
Protected Attributes
DofsType locally_owned_dofs
DofsType locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
VectorType evaluation_point
VectorType local_evaluation_point
VectorType newton_update
VectorType present_solution
VectorType system_rhs
std::vector< VectorType > previous_solutions
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, VectorType, DofsType > > average_velocities
VectorType average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::vector< Tensor< 1, dim > > > forces_on_boundaries
std::vector< Tensor< 1, 3 > > torques_on_boundaries
std::vector< TableHandler > forces_tables
std::vector< TableHandler > torques_tables
Additional Inherited Members
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
virtual void assemble_system_matrix ()=0
assemble_system_matrix Assembles the matrix
virtual void assemble_system_rhs ()=0
assemble_system_rhs Assembles the rhs
virtual void solve_linear_system (const bool initial_step, const bool renewed_matrix=true)=0
solve_linear_system Solves the linear system of equations
void solve_non_linear_system (const bool first_iteration)
solve_non_linear_system Solves the non linear system of equations
virtual void apply_constraints ()
Applies constraints to a local_evaluation_point.
virtual double get_current_residual ()
Default way to evaluate the residual for the nonlinear solver. Some application may use more complex evaluation of the residual and override this method.
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim, typename VectorType, typename DofsType>
class NavierStokesBase< dim, VectorType, DofsType >
A base class for all the Navier-Stokes equation This class regroups common facilities that are shared by all the Navier-Stokes implementations to reduce code multiplicity
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
VectorType The Vector type used for the solvers
DofsType the type of dof storage indices
Author
Bruno Blais, 2019
Definition at line 77 of file navier_stokes_base.h.
Constructor & Destructor Documentation
NavierStokesBase()
template<int dim, typename VectorType , typename DofsType > NavierStokesBase< dim, VectorType, DofsType >::NavierStokesBase (SimulationParameters< dim > & nsparam) protected
Definition at line 61 of file navier_stokes_base.cc.
~NavierStokesBase()
template<int dim, typename VectorType , typename DofsType > virtual NavierStokesBase< dim, VectorType, DofsType >::~NavierStokesBase () inline protected virtual
Definition at line 82 of file navier_stokes_base.h.
Member Function Documentation
box_refine_mesh()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::box_refine_mesh protected
Allow the initial refinement of all cells of the principal mesh that are partially contained in one of the cells of the box refinement mesh given in the parameter.
Definition at line 635 of file navier_stokes_base.cc.
References Parameters::Mesh::dealii, LetheGridTools::find_cells_in_cells(), Parameters::Mesh::gmsh, and pressure.
check_existance_of_bc()
template<int dim, typename VectorType , typename DofsType > bool NavierStokesBase< dim, VectorType, DofsType >::check_existance_of_bc (BoundaryConditions::BoundaryType bc) protected
Check if a specifique boundary condition exist.
Parameters
bc,the boundary type that we want to check if it exists
Definition at line 241 of file navier_stokes_base.cc.
dynamic_flow_control()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::dynamic_flow_control protected virtual
dynamic_flow_control If set to enable, dynamic_flow_control allows to control the flow by executing space-average velocity and beta coefficient force calculation at each time step.
Reimplemented in CFDDEMSolver< dim >.
Definition at line 203 of file navier_stokes_base.cc.
References calculate_average_velocity(), and Parameters::SimulationControl::steady.
establish_solid_domain()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::establish_solid_domain (const bool non_zero_constraints) protected
Turns regions of the mesh where the material_id=1 to a solid block by injecting it into the constraints This is achieved by imposing $\mathbf{u}=0$ within the cells which have a material_id=1. In addition, solid cells which are not connected to the fluid by any means also get a pressure dirichlet boundary condition which fixes the pressure to 0. This ensures that the linear system is well-posed. Right now, this routine only supports the usage of 1 solid domain, but eventually it could be extended to more than one. By default, the fluid domain is assumed to have a material_id=0 and the rest of the domains have a material_id>0.
Parameters
non_zero_constraints If this parameter is true, it indicates that it is the non_zero constraints which are being constrainted for the solid domain. If this is set to false, the zero constraints are constrained in the solid domain
Definition at line 1670 of file navier_stokes_base.cc.
finish_simulation()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::finish_simulation () inline protected
finish_simulation Finish the simulation by calling all the post-processing elements that are required
Generic interface routine to allow the CFD solver to cooperate with the multiphysics modules
Definition at line 135 of file navier_stokes_base.h.
finish_simulation_fd()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::finish_simulation_fd protected
finish_simulation Finishes the simulation for fluid dynamics by calling the post-processing elements that are required
Definition at line 456 of file navier_stokes_base.cc.
References Parameters::SimulationControl::steady.
finish_time_step()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::finish_time_step protected virtual
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
Key physics component for fluid dynamics
Definition at line 515 of file navier_stokes_base.cc.
References announce_string(), calculate_CFL(), Parameters::Timer::iteration, Parameters::SimulationControl::steady, and write_checkpoint().
get_evaluation_point()
template<int dim, typename VectorType , typename DofsType > virtual VectorType& NavierStokesBase< dim, VectorType, DofsType >::get_evaluation_point () inline override protected virtual
Getter methods to get the private attributes for the physic currently solved.
Parameters
current_physics_id Indicates the number associated with the physic currently solved. If the solver is only solving for a fluid dynamics problem, then the value will always be PhysicsID::fluid_dynamics.
Implements PhysicsSolver< VectorType >.
Definition at line 94 of file navier_stokes_base.h.
get_local_evaluation_point()
template<int dim, typename VectorType , typename DofsType > virtual VectorType& NavierStokesBase< dim, VectorType, DofsType >::get_local_evaluation_point () inline override protected virtual
Implements PhysicsSolver< VectorType >.
Definition at line 99 of file navier_stokes_base.h.
get_newton_update()
template<int dim, typename VectorType , typename DofsType > virtual VectorType& NavierStokesBase< dim, VectorType, DofsType >::get_newton_update () inline override protected virtual
Implements PhysicsSolver< VectorType >.
Definition at line 104 of file navier_stokes_base.h.
get_nonzero_constraints()
template<int dim, typename VectorType , typename DofsType > virtual AffineConstraints<double>& NavierStokesBase< dim, VectorType, DofsType >::get_nonzero_constraints () inline override protected virtual
Implements PhysicsSolver< VectorType >.
Definition at line 119 of file navier_stokes_base.h.
get_present_solution()
template<int dim, typename VectorType , typename DofsType > virtual VectorType& NavierStokesBase< dim, VectorType, DofsType >::get_present_solution () inline override protected virtual
Implements PhysicsSolver< VectorType >.
Definition at line 109 of file navier_stokes_base.h.
get_system_rhs()
template<int dim, typename VectorType , typename DofsType > virtual VectorType& NavierStokesBase< dim, VectorType, DofsType >::get_system_rhs () inline override protected virtual
Implements PhysicsSolver< VectorType >.
Definition at line 114 of file navier_stokes_base.h.
init_temporary_vector()
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::init_temporary_vector inline protected
init_temporary_vector This function initializes correctly a temporary vector depending on the vector type
Definition at line 2320 of file navier_stokes_base.cc.
iterate()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::iterate protected virtual
iterate Do a regular CFD iteration
Reimplemented in GLSVANSSolver< dim >.
Definition at line 551 of file navier_stokes_base.cc.
References announce_string(), fluid_dynamics, Parameters::quiet, and PhysicsSolver< VectorType >::solve_non_linear_system().
output_field_hook()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::output_field_hook (DataOut< dim > &) protected virtual
output_field_hook This function is to be redefined in specialized classes to adapt the output to each solver.
Reimplemented in GLSVANSSolver< dim >, and GLSSharpNavierStokesSolver< dim >.
Definition at line 1829 of file navier_stokes_base.cc.
percolate_time_vectors_fd()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::percolate_time_vectors_fd protected virtual
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
Definition at line 504 of file navier_stokes_base.cc.
postprocess()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::postprocess (bool first_iteration) inline protected virtual
postprocess Post-process simulation after an iteration
Parameters
first_iteration Indicator if the simulation is at it's first simulation or not.
Definition at line 148 of file navier_stokes_base.h.
postprocess_fd()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::postprocess_fd (bool first_iteration) protected virtual
postprocess Post-process fluid dynamics after an iteration
Reimplemented in GLSSharpNavierStokesSolver< dim >, and CFDDEMSolver< dim >.
Definition at line 1138 of file navier_stokes_base.cc.
References calculate_apparent_viscosity(), calculate_enstrophy(), calculate_flow_rate(), calculate_kinetic_energy(), calculate_L2_error(), calculate_pressure_drop(), Parameters::SimulationControl::steady, and Parameters::verbose.
postprocessing_forces()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::postprocessing_forces (const VectorType & evaluation_point) protected
postprocessing_forces Post-processing function Outputs the forces acting on each boundary condition
End of key physics components for fluid dynamics
Definition at line 261 of file navier_stokes_base.cc.
postprocessing_torques()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::postprocessing_torques (const VectorType & evaluation_point) protected
postprocessing_torques Post-processing function Outputs the torque acting on each boundary condition
Definition at line 382 of file navier_stokes_base.cc.
read_checkpoint()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::read_checkpoint protected virtual
read_checkpoint
Reimplemented in GLSNitscheNavierStokesSolver< dim, spacedim >, GLSSharpNavierStokesSolver< dim >, and CFDDEMSolver< dim >.
Definition at line 1530 of file navier_stokes_base.cc.
References Parameters::PostProcessing::apparent_viscosity_output_name, Parameters::PostProcessing::calculate_apparent_viscosity, Parameters::PostProcessing::calculate_enstrophy, Parameters::PostProcessing::calculate_flow_rate, Parameters::PostProcessing::calculate_kinetic_energy, Parameters::PostProcessing::calculate_pressure_drop, deserialize_table(), Parameters::PostProcessing::enstrophy_output_name, Parameters::PostProcessing::flow_rate_output_name, Parameters::PostProcessing::kinetic_energy_output_name, and Parameters::PostProcessing::pressure_drop_output_name.
refine_mesh()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::refine_mesh protected virtual
Allow the refinement of the mesh according to one of the 2 methods proposed.
Reimplemented in GLSNitscheNavierStokesSolver< dim, spacedim >.
Definition at line 617 of file navier_stokes_base.cc.
References Parameters::MeshAdaptation::kelly, and Parameters::MeshAdaptation::uniform.
refine_mesh_kelly()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::refine_mesh_kelly protected
Allow the refinement of the mesh based on the Kelly error estimator. See : https://www.dealii.org/current/doxygen/deal.II/classKellyErrorEstimator.html for more information on the Kelly error estimator.
Definition at line 848 of file navier_stokes_base.cc.
References Parameters::MeshAdaptation::fraction, Parameters::MeshAdaptation::number, Parameters::MeshAdaptation::pressure, pressure, and Parameters::MeshAdaptation::velocity.
refine_mesh_uniform()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::refine_mesh_uniform protected
Allow the uniform refinement of all the mesh.
Definition at line 1062 of file navier_stokes_base.cc.
rescale_pressure_dofs_in_newton_update()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::rescale_pressure_dofs_in_newton_update protected
rescale_pressure_dofs_in_newton_update This function is used to rescale pressure DOFs in the newton correction
Definition at line 2272 of file navier_stokes_base.cc.
set_initial_condition()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::set_initial_condition (Parameters::InitialConditionType initial_condition_type, bool restart = false) inline protected virtual
set_initial_conditions
Parameters
initial_condition_type Type of method use to impose initial condition.
restart Indicator if the simulation is being restarted or not.
Definition at line 177 of file navier_stokes_base.h.
set_initial_condition_fd()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart = false) protected pure virtual
Implemented in MFNavierStokesSolver< dim >, GLSNavierStokesSolver< dim >, and GDNavierStokesSolver< dim >.
set_nodal_values()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::set_nodal_values protected
set_nodal_values Set the nodal values of velocity and pressure
Definition at line 1483 of file navier_stokes_base.cc.
References Parameters::SimulationControl::initial_solution, and pressure.
setup_dofs()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::setup_dofs () inline protected virtual
setup_dofs
Initialize the degree of freedom and the memory associated with them for fluid dynamics and enabled auxiliary physics.
Reimplemented in GLSVANSSolver< dim >.
Definition at line 161 of file navier_stokes_base.h.
setup_dofs_fd()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::setup_dofs_fd () protected pure virtual
setup_dofs
Initialize the dofs for fluid dynamics
Implemented in MFNavierStokesSolver< dim >, GLSNavierStokesSolver< dim >, and GDNavierStokesSolver< dim >.
update_multiphysics_time_average_solution()
template<int dim, typename VectorType , typename DofsType > virtual void NavierStokesBase< dim, VectorType, DofsType >::update_multiphysics_time_average_solution () protected pure virtual
Update the time average velocity field solution.
Implemented in MFNavierStokesSolver< dim >, GLSNavierStokesSolver< dim >, and GDNavierStokesSolver< dim >.
write_checkpoint()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::write_checkpoint protected virtual
write_checkpoint
Reimplemented in GLSNitscheNavierStokesSolver< dim, spacedim >, GLSSharpNavierStokesSolver< dim >, and CFDDEMSolver< dim >.
Definition at line 2168 of file navier_stokes_base.cc.
References Parameters::PostProcessing::apparent_viscosity_output_name, Parameters::PostProcessing::calculate_apparent_viscosity, Parameters::PostProcessing::calculate_enstrophy, Parameters::PostProcessing::calculate_flow_rate, Parameters::PostProcessing::calculate_kinetic_energy, Parameters::PostProcessing::calculate_pressure_drop, Parameters::PostProcessing::enstrophy_output_name, Parameters::PostProcessing::flow_rate_output_name, Parameters::PostProcessing::kinetic_energy_output_name, Parameters::PostProcessing::pressure_drop_output_name, and serialize_table().
write_output_forces()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::write_output_forces protected
write_output_forces Writes the forces per boundary condition to a text file output
Definition at line 2124 of file navier_stokes_base.cc.
write_output_results()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::write_output_results (const VectorType & solution) protected
write_output_results Post-processing as parallel VTU files
Definition at line 1835 of file navier_stokes_base.cc.
References PostProcessorSmoothing< dim, VectorType >::calculate_smoothed_field(), PostProcessorSmoothing< dim, VectorType >::get_dof_handler(), and Parameters::VelocitySource::srf.
write_output_torques()
template<int dim, typename VectorType , typename DofsType > void NavierStokesBase< dim, VectorType, DofsType >::write_output_torques protected
write_output_torques Writes the torques per boundary condition to a text file output
Definition at line 2146 of file navier_stokes_base.cc.
Member Data Documentation
apparent_viscosity_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::apparent_viscosity_table protected
Definition at line 469 of file navier_stokes_base.h.
assemblers
template<int dim, typename VectorType , typename DofsType > std::vector<std::shared_ptr<NavierStokesAssemblerBase<dim> > > NavierStokesBase< dim, VectorType, DofsType >::assemblers protected
Definition at line 458 of file navier_stokes_base.h.
average_solution
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::average_solution protected
Definition at line 474 of file navier_stokes_base.h.
average_velocities
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<AverageVelocities<dim, VectorType, DofsType> > NavierStokesBase< dim, VectorType, DofsType >::average_velocities protected
Definition at line 473 of file navier_stokes_base.h.
cell_quadrature
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<Quadrature<dim> > NavierStokesBase< dim, VectorType, DofsType >::cell_quadrature protected
Definition at line 454 of file navier_stokes_base.h.
computing_timer
template<int dim, typename VectorType , typename DofsType > TimerOutput NavierStokesBase< dim, VectorType, DofsType >::computing_timer protected
Definition at line 421 of file navier_stokes_base.h.
dof_handler
template<int dim, typename VectorType , typename DofsType > DoFHandler<dim> NavierStokesBase< dim, VectorType, DofsType >::dof_handler protected
Definition at line 418 of file navier_stokes_base.h.
enstrophy_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::enstrophy_table protected
Definition at line 467 of file navier_stokes_base.h.
error_table
template<int dim, typename VectorType , typename DofsType > ConvergenceTable NavierStokesBase< dim, VectorType, DofsType >::error_table protected
Definition at line 480 of file navier_stokes_base.h.
evaluation_point
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::evaluation_point protected
Definition at line 438 of file navier_stokes_base.h.
exact_solution
template<int dim, typename VectorType , typename DofsType > Function<dim>* NavierStokesBase< dim, VectorType, DofsType >::exact_solution protected
Definition at line 427 of file navier_stokes_base.h.
face_quadrature
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<Quadrature<dim - 1> > NavierStokesBase< dim, VectorType, DofsType >::face_quadrature protected
Definition at line 455 of file navier_stokes_base.h.
fe
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<FESystem<dim> > NavierStokesBase< dim, VectorType, DofsType >::fe protected
Definition at line 419 of file navier_stokes_base.h.
flow_control
template<int dim, typename VectorType , typename DofsType > FlowControl<dim> NavierStokesBase< dim, VectorType, DofsType >::flow_control protected
Definition at line 431 of file navier_stokes_base.h.
flow_rate_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::flow_rate_table protected
Definition at line 471 of file navier_stokes_base.h.
forces_on_boundaries
template<int dim, typename VectorType , typename DofsType > std::vector<std::vector<Tensor<1, dim> > > NavierStokesBase< dim, VectorType, DofsType >::forces_on_boundaries protected
Definition at line 483 of file navier_stokes_base.h.
forces_tables
template<int dim, typename VectorType , typename DofsType > std::vector<TableHandler> NavierStokesBase< dim, VectorType, DofsType >::forces_tables protected
Definition at line 485 of file navier_stokes_base.h.
forcing_function
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<Function<dim> > NavierStokesBase< dim, VectorType, DofsType >::forcing_function protected
Definition at line 428 of file navier_stokes_base.h.
kinetic_energy_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::kinetic_energy_table protected
Definition at line 468 of file navier_stokes_base.h.
local_evaluation_point
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::local_evaluation_point protected
Definition at line 439 of file navier_stokes_base.h.
locally_owned_dofs
template<int dim, typename VectorType , typename DofsType > DofsType NavierStokesBase< dim, VectorType, DofsType >::locally_owned_dofs protected
Definition at line 410 of file navier_stokes_base.h.
locally_relevant_dofs
template<int dim, typename VectorType , typename DofsType > DofsType NavierStokesBase< dim, VectorType, DofsType >::locally_relevant_dofs protected
Definition at line 411 of file navier_stokes_base.h.
mapping
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<Mapping<dim> > NavierStokesBase< dim, VectorType, DofsType >::mapping protected
Definition at line 453 of file navier_stokes_base.h.
mesh_controller
template<int dim, typename VectorType , typename DofsType > MeshController NavierStokesBase< dim, VectorType, DofsType >::mesh_controller protected
Definition at line 477 of file navier_stokes_base.h.
mpi_communicator
template<int dim, typename VectorType , typename DofsType > MPI_Comm NavierStokesBase< dim, VectorType, DofsType >::mpi_communicator protected
Definition at line 413 of file navier_stokes_base.h.
multiphysics
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<MultiphysicsInterface<dim> > NavierStokesBase< dim, VectorType, DofsType >::multiphysics protected
Definition at line 461 of file navier_stokes_base.h.
n_mpi_processes
template<int dim, typename VectorType , typename DofsType > const unsigned int NavierStokesBase< dim, VectorType, DofsType >::n_mpi_processes protected
Definition at line 414 of file navier_stokes_base.h.
newton_update
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::newton_update protected
Definition at line 440 of file navier_stokes_base.h.
nonzero_constraints
template<int dim, typename VectorType , typename DofsType > AffineConstraints<double> NavierStokesBase< dim, VectorType, DofsType >::nonzero_constraints protected
Definition at line 435 of file navier_stokes_base.h.
number_quadrature_points
template<int dim, typename VectorType , typename DofsType > unsigned int NavierStokesBase< dim, VectorType, DofsType >::number_quadrature_points protected
Definition at line 450 of file navier_stokes_base.h.
present_solution
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::present_solution protected
Definition at line 441 of file navier_stokes_base.h.
pressure_drop_table
template<int dim, typename VectorType , typename DofsType > TableHandler NavierStokesBase< dim, VectorType, DofsType >::pressure_drop_table protected
Definition at line 470 of file navier_stokes_base.h.
pressure_fem_degree
template<int dim, typename VectorType , typename DofsType > const unsigned int NavierStokesBase< dim, VectorType, DofsType >::pressure_fem_degree protected
Definition at line 449 of file navier_stokes_base.h.
previous_solutions
template<int dim, typename VectorType , typename DofsType > std::vector<VectorType> NavierStokesBase< dim, VectorType, DofsType >::previous_solutions protected
Definition at line 445 of file navier_stokes_base.h.
pvdhandler
template<int dim, typename VectorType , typename DofsType > PVDHandler NavierStokesBase< dim, VectorType, DofsType >::pvdhandler protected
Definition at line 424 of file navier_stokes_base.h.
simulation_control
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<SimulationControl> NavierStokesBase< dim, VectorType, DofsType >::simulation_control protected
Definition at line 464 of file navier_stokes_base.h.
simulation_parameters
template<int dim, typename VectorType , typename DofsType > SimulationParameters<dim> NavierStokesBase< dim, VectorType, DofsType >::simulation_parameters protected
Definition at line 423 of file navier_stokes_base.h.
system_rhs
template<int dim, typename VectorType , typename DofsType > VectorType NavierStokesBase< dim, VectorType, DofsType >::system_rhs protected
Definition at line 442 of file navier_stokes_base.h.
this_mpi_process
template<int dim, typename VectorType , typename DofsType > const unsigned int NavierStokesBase< dim, VectorType, DofsType >::this_mpi_process protected
Definition at line 415 of file navier_stokes_base.h.
torques_on_boundaries
template<int dim, typename VectorType , typename DofsType > std::vector<Tensor<1, 3> > NavierStokesBase< dim, VectorType, DofsType >::torques_on_boundaries protected
Definition at line 484 of file navier_stokes_base.h.
torques_tables
template<int dim, typename VectorType , typename DofsType > std::vector<TableHandler> NavierStokesBase< dim, VectorType, DofsType >::torques_tables protected
Definition at line 486 of file navier_stokes_base.h.
triangulation
template<int dim, typename VectorType , typename DofsType > std::shared_ptr<parallel::DistributedTriangulationBase<dim> > NavierStokesBase< dim, VectorType, DofsType >::triangulation protected
Definition at line 417 of file navier_stokes_base.h.
velocity_fem_degree
template<int dim, typename VectorType , typename DofsType > const unsigned int NavierStokesBase< dim, VectorType, DofsType >::velocity_fem_degree protected
Definition at line 448 of file navier_stokes_base.h.
zero_constraints
template<int dim, typename VectorType , typename DofsType > AffineConstraints<double> NavierStokesBase< dim, VectorType, DofsType >::zero_constraints protected
Definition at line 434 of file navier_stokes_base.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/navier_stokes_base.h
/home/runner/work/lethe/lethe/source/solvers/navier_stokes_base.cc