Developer documentation for the Lethe open-source library: VolumeOfFluid< dim > Class Template Reference
VolumeOfFluid< dim > Class Template Reference
#include <vof.h>
Public Member Functions
VolumeOfFluid (MultiphysicsInterface< dim > *multiphysics_interface, const SimulationParameters< dim > &p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim >> p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control)
VOF - Base constructor.
~VolumeOfFluid ()
VOF - Base destructor. At the present moment this is an interface with nothing.
void assemble_matrix_and_rhs ()
Call for the assembly of the matrix and the right-hand side.
void assemble_rhs ()
Call for the assembly of the right-hand side.
void attach_solution_to_output (DataOut< dim > &data_out) override
Attach the solution vector to the DataOut provided. This function enable the auxiliary physics to output their solution via the core solver.
double calculate_L2_error ()
Calculates the L2 error of the solution.
template<typename VectorType >
void calculate_volume_and_mass (const TrilinosWrappers::MPI::Vector &solution, const VectorType &current_solution_fd, const Parameters::FluidIndicator monitored_fluid)
Calculates the volume and mass for a given fluid phase. Used for conservation monitoring.
template<typename VectorType >
std::pair< Tensor< 1, dim >, Tensor< 1, dim > > calculate_barycenter (const TrilinosWrappers::MPI::Vector &solution, const VectorType &current_solution_fd)
Calculates the barycenter of the fluid and its velocity.
void finish_simulation () override
Carry out the operations required to finish a simulation correctly.
void percolate_time_vectors () override
Carry out the operations required to rearrange the values of the previous solution at the end of a time step.
void modify_solution () override
Carry out modifications on the auxiliary physic solution.
void postprocess (bool first_iteration) override
Postprocess the auxiliary physics results. Post-processing this case implies the calculation of all derived quantities using the solution vector of the physics. It does not concern the output of the solution using the DataOutObject, which is accomplished through the attach_solution_to_output function.
void pre_mesh_adaptation () override
pre_mesh_adaption Prepares the auxiliary physics variables for a mesh refinement/coarsening
void post_mesh_adaptation () override
post_mesh_adaption Interpolates the auxiliary physics variables to the new mesh
void compute_kelly (const std::pair< const Parameters::MeshAdaptation::Variable, Parameters::MultipleAdaptationParameters > &ivar, dealii::Vector< float > &estimated_error_per_cell) override
Compute the Kelly error estimator on the phase parameter for mesh refinement. See : https://www.dealii.org/current/doxygen/deal.II/classKellyErrorEstimator.html for more information on the Kelly error estimator.
void write_checkpoint () override
Prepares auxiliary physics to write checkpoint.
void read_checkpoint () override
Set solution vector of Auxiliary Physics using checkpoint.
void setup_dofs () override
Sets-up the DofHandler and the degree of freedom associated with the physics.
void define_zero_constraints ()
defined the zero constraints used to solve the problem.
void define_non_zero_constraints ()
defined the non zero constraints used to solve the problem.
void set_initial_conditions () override
Sets-up the initial conditions associated with the physics. Generally, physics only support imposing nodal values, but some physics additionnaly support the use of L2 projection or steady-state solutions.
void update_boundary_conditions () override
Update non zero constraints if the boundary is time dependent.
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
Call for the solution of the linear system of equation using a strategy appropriate to the auxiliary physics.
const DoFHandler< dim > & get_dof_handler () override
Getter methods to get the private attributes for the physic currently solved NB : dof_handler and present_solution are passed to the multiphysics interface at the end of the setup_dofs method.
TrilinosWrappers::MPI::Vector & get_evaluation_point () override
Getter methods that give access to the private attributes of the physics being solved. These methods must be provided by the physics as they are the key to solve a problem using Lethe.
TrilinosWrappers::MPI::Vector & get_local_evaluation_point () override
TrilinosWrappers::MPI::Vector & get_newton_update () override
TrilinosWrappers::MPI::Vector & get_present_solution () override
TrilinosWrappers::MPI::Vector & get_system_rhs () override
AffineConstraints< double > & get_nonzero_constraints () override
DoFHandler< dim > * get_projected_phase_fraction_gradient_dof_handler ()
DoFHandler< dim > * get_curvature_dof_handler ()
TrilinosWrappers::MPI::Vector * get_projected_phase_fraction_gradient_solution ()
TrilinosWrappers::MPI::Vector * get_curvature_solution ()
Public Member Functions inherited from AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >
AuxiliaryPhysics (const Parameters::NonLinearSolver non_linear_solver_parameters)
AuxiliaryPhysics - Base constructor for Auxiliary physics. At the present moment this is an interface with nothing. The auxiliary physics is a pure virtual class.
virtual ~AuxiliaryPhysics ()
AuxiliaryPhysics - Base destructor. At the present moment this is an interface with nothing.
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
solve_non_linear_system Solves the non linear system of equations
virtual void apply_constraints ()
Applies constraints to a local_evaluation_point.
virtual double get_current_residual ()
Default way to evaluate the residual for the nonlinear solver. Some application may use more complex evaluation of the residual and override this method.
Private Member Functions
void assemble_system_matrix () override
Assembles the matrix associated with the solver.
void assemble_system_rhs () override
Assemble the rhs associated with the solver.
virtual void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, VOFScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
Assemble the local matrix for a given cell.
virtual void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, VOFScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
Assemble the local rhs for a given cell.
virtual void setup_assemblers ()
sets up the vector of assembler functions
virtual void copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData &copy_data)
Copy local cell information to global matrix.
virtual void copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData &copy_data)
Copy local cell rhs information to global rhs.
void update_solution_and_constraints (TrilinosWrappers::MPI::Vector &solution)
Limit the phase fractions between 0 and 1. This is necessary before interface sharpening. More information can be found in step_41 of deal.II tutorials: https://www.dealii.org/current/doxygen/deal.II/step_41.html.
void assemble_L2_projection_interface_sharpening (TrilinosWrappers::MPI::Vector &solution, const double sharpening_threshold)
Assemble the system for interface sharpening.
void solve_interface_sharpening (TrilinosWrappers::MPI::Vector &solution)
Solves the assembled system to sharpen the interface. The linear_solver_tolerance is hardcoded = 1e-15, and an ILU Preconditioner is used. After solving the system, this function overwrites the solution with the sharpened solution.
void assemble_mass_matrix (TrilinosWrappers::SparseMatrix &mass_matrix)
Assembles a mass_matrix which is used in update_solution_and_constraints function to limit the phase fractions of cells in the range of [0,1] before sharpening the interface. More information can be found in step_41 of deal.II tutorials: https://www.dealii.org/current/doxygen/deal.II/step_41.html.
void handle_interface_sharpening ()
Carries out interface sharpening. It is called in the modify solution function. Launches sharpen_interface with the possibility to ensure conservation and handles output messages.
double find_sharpening_threshold ()
Find the sharpening threshold to ensure mass conservation of the fluid monitored, as given in the prm (VOF, subsection monitoring), by binary search.
double calculate_mass_deviation (const Parameters::FluidIndicator monitored_fluid, const double sharpening_threshold)
Calculate the mass deviation of the monitored fluid, between the current iteration and the mass at first iteration (mass_first_iteration). Used to test multiple sharpening threshold in the binary search algorithm (adaptive sharpening).
void sharpen_interface (TrilinosWrappers::MPI::Vector &solution, const double sharpening_threshold, const bool sharpen_previous_solutions)
Carries out interface sharpening. It is called in the modify solution function.
void smooth_phase_fraction ()
Carries out the smoothing phase fraction with a projection step (to avoid a staircase interface).
void find_projected_phase_fraction_gradient ()
Carries out finding the gradients of phase fraction. Obtained gradients of phase fraction is used in find_projected_interface_curvature to find interface curvature (k).
void find_projected_interface_curvature ()
Carries out finding the interface curvature.
void assemble_projection_phase_fraction (TrilinosWrappers::MPI::Vector &solution)
Assembles the matrix and rhs for calculation of a smooth phase fraction using a projection.
void solve_projection_phase_fraction (TrilinosWrappers::MPI::Vector &solution)
Solves smooth phase fraction system.
void assemble_projected_phase_fraction_gradient_matrix_and_rhs (TrilinosWrappers::MPI::Vector &solution)
Assembles the matrix and rhs for calculation of projected phase fraction gradient (pfg).
void solve_projected_phase_fraction_gradient ()
Solves phase fraction gradient system.
void assemble_curvature_matrix_and_rhs (TrilinosWrappers::MPI::Vector &present_projected_phase_fraction_gradient_solution)
Assembles the matrix and rhs for calculation of the curvature.
void solve_curvature ()
Solves curvature system.
void apply_phase_filter ()
Applies filter on phase fraction values.
Private Attributes
TrilinosWrappers::MPI::Vector nodal_phase_fraction_owned
MultiphysicsInterface< dim > * multiphysics
TimerOutput computing_timer
const SimulationParameters< dim > & simulation_parameters
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
std::shared_ptr< SimulationControl > simulation_control
DoFHandler< dim > dof_handler
DoFHandler< dim > projected_phase_fraction_gradient_dof_handler
DoFHandler< dim > curvature_dof_handler
std::shared_ptr< FiniteElement< dim > > fe
std::shared_ptr< FESystem< dim > > fe_projected_phase_fraction_gradient
std::shared_ptr< FiniteElement< dim > > fe_curvature
ConvergenceTable error_table
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Mapping< dim > > projected_phase_fraction_gradient_mapping
std::shared_ptr< Mapping< dim > > curvature_mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
TrilinosWrappers::MPI::Vector evaluation_point
TrilinosWrappers::MPI::Vector local_evaluation_point
TrilinosWrappers::MPI::Vector newton_update
TrilinosWrappers::MPI::Vector present_solution
TrilinosWrappers::MPI::Vector system_rhs
AffineConstraints< double > nonzero_constraints
AffineConstraints< double > bounding_constraints
AffineConstraints< double > zero_constraints
TrilinosWrappers::SparseMatrix system_matrix
TrilinosWrappers::MPI::Vector solution_pw
TrilinosWrappers::MPI::Vector filtered_solution
std::vector< TrilinosWrappers::MPI::Vector > previous_solutions
std::shared_ptr< parallel::distributed::SolutionTransfer< dim, TrilinosWrappers::MPI::Vector > > solution_transfer
std::vector< parallel::distributed::SolutionTransfer< dim, TrilinosWrappers::MPI::Vector > > previous_solutions_transfer
TrilinosWrappers::SparseMatrix system_matrix_phase_fraction
TrilinosWrappers::SparseMatrix complete_system_matrix_phase_fraction
TrilinosWrappers::MPI::Vector system_rhs_phase_fraction
TrilinosWrappers::MPI::Vector complete_system_rhs_phase_fraction
TrilinosWrappers::SparseMatrix mass_matrix_phase_fraction
TrilinosWrappers::MPI::Vector present_projected_phase_fraction_gradient_solution
IndexSet locally_owned_dofs_projected_phase_fraction_gradient
IndexSet locally_relevant_dofs_projected_phase_fraction_gradient
AffineConstraints< double > projected_phase_fraction_gradient_constraints
TrilinosWrappers::MPI::Vector nodal_projected_phase_fraction_gradient_relevant
TrilinosWrappers::MPI::Vector nodal_projected_phase_fraction_gradient_owned
TrilinosWrappers::SparseMatrix system_matrix_projected_phase_fraction_gradient
TrilinosWrappers::MPI::Vector system_rhs_projected_phase_fraction_gradient
TrilinosWrappers::MPI::Vector present_curvature_solution
IndexSet locally_owned_dofs_curvature
IndexSet locally_relevant_dofs_curvature
AffineConstraints< double > curvature_constraints
TrilinosWrappers::MPI::Vector nodal_curvature_relevant
TrilinosWrappers::MPI::Vector nodal_curvature_owned
std::vector< Tensor< 1, dim > > projected_phase_fraction_gradient_values
std::vector< double > curvature_values
TrilinosWrappers::SparseMatrix system_matrix_curvature
TrilinosWrappers::MPI::Vector system_rhs_curvature
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
const double phase_upper_bound = 1.0
const double phase_lower_bound = 0.0
TableHandler table_monitoring_vof
double volume_monitored
double mass_monitored
double mass_first_iteration
double sharpening_threshold
TableHandler table_barycenter
std::vector< std::shared_ptr< VOFAssemblerBase< dim > > > assemblers
std::shared_ptr< VolumeOfFluidFilterBase > filter
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class VolumeOfFluid< dim >
Definition at line 56 of file vof.h.
Constructor & Destructor Documentation
VolumeOfFluid()
template<int dim> VolumeOfFluid< dim >::VolumeOfFluid (MultiphysicsInterface< dim > * multiphysics_interface, const SimulationParameters< dim > & p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim >> p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control) inline
VOF - Base constructor.
Definition at line 63 of file vof.h.
References VolumeOfFluid< dim >::cell_quadrature, VolumeOfFluid< dim >::computing_timer, VolumeOfFluid< dim >::curvature_mapping, VolumeOfFluid< dim >::dof_handler, VolumeOfFluid< dim >::face_quadrature, VolumeOfFluid< dim >::fe, VolumeOfFluid< dim >::fe_curvature, VolumeOfFluid< dim >::fe_projected_phase_fraction_gradient, VolumeOfFluid< dim >::mapping, maximum_number_of_previous_solutions(), Parameters::Timer::none, PhysicsSolver< VectorType >::pcout, VolumeOfFluid< dim >::previous_solutions, VolumeOfFluid< dim >::previous_solutions_transfer, VolumeOfFluid< dim >::projected_phase_fraction_gradient_mapping, VolumeOfFluid< dim >::simulation_parameters, and VolumeOfFluid< dim >::solution_transfer.
~VolumeOfFluid()
template<int dim> VolumeOfFluid< dim >::~VolumeOfFluid () inline
VOF - Base destructor. At the present moment this is an interface with nothing.
Definition at line 161 of file vof.h.
Member Function Documentation
apply_phase_filter()
template<int dim> void VolumeOfFluid< dim >::apply_phase_filter private
Applies filter on phase fraction values.
Definition at line 2637 of file vof.cc.
References VolumeOfFluidFilterBase::model_cast(), and Parameters::verbose.
assemble_curvature_matrix_and_rhs()
template<int dim> void VolumeOfFluid< dim >::assemble_curvature_matrix_and_rhs (TrilinosWrappers::MPI::Vector & present_projected_phase_fraction_gradient_solution) private
Assembles the matrix and rhs for calculation of the curvature.
Solves: $$ v * k + \eta * \nabla v . \nabla k = \nabla v . (\psi / |\psi|) $$ where $$v$$, $$psi$$, $$eta$$, and $$k$$ are test function, fpg, filter value, and curvature.
Parameters
present_projected_phase_fraction_gradient_solution
Definition at line 1559 of file vof.cc.
assemble_L2_projection_interface_sharpening()
template<int dim> void VolumeOfFluid< dim >::assemble_L2_projection_interface_sharpening (TrilinosWrappers::MPI::Vector & solution, const double sharpening_threshold) private
Assemble the system for interface sharpening.
This function assembles the weak form of: $$ \Phi = c ^ (1 - \alpha) * (\phi ^ \alpha) if 0 <= \phi <= c $$ $$ \Phi = 1 - (1 - c) ^ (1 - \alpha) * (1 - \phi) ^ \alpha if c < \phi <= 1 $$ Reference for sharpening method https://www.sciencedirect.com/science/article/pii/S0045782500002000
Parameters
solution VOF solution (phase fraction)
sharpening_threshold Interface sharpening threshold that represents the mass conservation level
Definition at line 2444 of file vof.cc.
assemble_local_system_matrix()
template<int dim> void VolumeOfFluid< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, VOFScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for VOFScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 98 of file vof.cc.
References StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, VOFScratchData< dim >::reinit(), VOFScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_local_system_rhs()
template<int dim> void VolumeOfFluid< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, VOFScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for VOFScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 222 of file vof.cc.
References StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, VOFScratchData< dim >::reinit(), VOFScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_mass_matrix()
template<int dim> void VolumeOfFluid< dim >::assemble_mass_matrix (TrilinosWrappers::SparseMatrix & mass_matrix) private
Assembles a mass_matrix which is used in update_solution_and_constraints function to limit the phase fractions of cells in the range of [0,1] before sharpening the interface. More information can be found in step_41 of deal.II tutorials: https://www.dealii.org/current/doxygen/deal.II/step_41.html.
Parameters
mass_matrix
Definition at line 2603 of file vof.cc.
assemble_matrix_and_rhs()
template<int dim> void VolumeOfFluid< dim >::assemble_matrix_and_rhs
Call for the assembly of the matrix and the right-hand side.
Deprecated:
This function is to be deprecated when the new assembly mechanism is integrated to this solver
Definition at line 31 of file vof.cc.
assemble_projected_phase_fraction_gradient_matrix_and_rhs()
template<int dim> void VolumeOfFluid< dim >::assemble_projected_phase_fraction_gradient_matrix_and_rhs (TrilinosWrappers::MPI::Vector & solution) private
Assembles the matrix and rhs for calculation of projected phase fraction gradient (pfg).
Solves: $$ v . \psi + \eta * \nabla v . \nabla \psi = v . \nabla \phi $$ where $$v$$, $$\psi$$, $$\eta$$, and $$\phi$$ are test function, fpg, filter value, and phase fraction.
Parameters
solution VOF solution (phase fraction)
Definition at line 1348 of file vof.cc.
assemble_projection_phase_fraction()
template<int dim> void VolumeOfFluid< dim >::assemble_projection_phase_fraction (TrilinosWrappers::MPI::Vector & solution) private
Assembles the matrix and rhs for calculation of a smooth phase fraction using a projection.
Parameters
solution VOF solution (phase fraction)
Definition at line 1189 of file vof.cc.
assemble_rhs()
template<int dim> void VolumeOfFluid< dim >::assemble_rhs
Call for the assembly of the right-hand side.
Deprecated:
This function is to be deprecated when the new assembly mechanism is integrated to this solver
Definition at line 40 of file vof.cc.
assemble_system_matrix()
template<int dim> void VolumeOfFluid< dim >::assemble_system_matrix override private virtual
Assembles the matrix associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 67 of file vof.cc.
References VolumeOfFluid< dim >::assemble_local_system_matrix(), VolumeOfFluid< dim >::copy_local_matrix_to_global_matrix(), and fluid_dynamics.
assemble_system_rhs()
template<int dim> void VolumeOfFluid< dim >::assemble_system_rhs override private virtual
Assemble the rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 191 of file vof.cc.
References VolumeOfFluid< dim >::assemble_local_system_rhs(), VolumeOfFluid< dim >::copy_local_rhs_to_global_rhs(), and fluid_dynamics.
attach_solution_to_output()
template<int dim> void VolumeOfFluid< dim >::attach_solution_to_output (DataOut< dim > & data_out) override virtual
Attach the solution vector to the DataOut provided. This function enable the auxiliary physics to output their solution via the core solver.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 315 of file vof.cc.
calculate_barycenter()
template<int dim> template<typename VectorType > template std::pair< Tensor< 1, 3 >, Tensor< 1, 3 > > VolumeOfFluid< dim >::calculate_barycenter< TrilinosWrappers::MPI::BlockVector > (const TrilinosWrappers::MPI::Vector & solution, const VectorType & current_solution_fd)
Calculates the barycenter of the fluid and its velocity.
Parameters
solution VOF solution
solution Fluid dynamics solution
Definition at line 398 of file vof.cc.
References fluid_dynamics, and VolumeOfFluidFilterBase::model_cast().
calculate_L2_error()
template<int dim> double VolumeOfFluid< dim >::calculate_L2_error
Calculates the L2 error of the solution.
Definition at line 352 of file vof.cc.
calculate_mass_deviation()
template<int dim> double VolumeOfFluid< dim >::calculate_mass_deviation (const Parameters::FluidIndicator monitored_fluid, const double sharpening_threshold) private
Calculate the mass deviation of the monitored fluid, between the current iteration and the mass at first iteration (mass_first_iteration). Used to test multiple sharpening threshold in the binary search algorithm (adaptive sharpening).
Parameters
monitored_fluid Fluid indicator (fluid0 or fluid1) corresponding to the phase of interest.
sharpening_threshold Interface sharpening threshold that represents the mass conservation level
Definition at line 1101 of file vof.cc.
References fluid_dynamics.
calculate_volume_and_mass()
template<int dim> template<typename VectorType > void VolumeOfFluid< dim >::calculate_volume_and_mass (const TrilinosWrappers::MPI::Vector & solution, const VectorType & current_solution_fd, const Parameters::FluidIndicator monitored_fluid)
Calculates the volume and mass for a given fluid phase. Used for conservation monitoring.
Parameters
solution VOF solution (phase fraction)
current_solution_fd current solution for the fluid dynamics
monitored_fluid Fluid indicator (fluid0 or fluid1) corresponding to the phase of interest.
Definition at line 506 of file vof.cc.
References Parameters::fluid0, Parameters::fluid1, fluid_dynamics, pressure, and set_field_vector().
compute_kelly()
template<int dim> void VolumeOfFluid< dim >::compute_kelly (const std::pair< const Parameters::MeshAdaptation::Variable, Parameters::MultipleAdaptationParameters > & ivar, dealii::Vector< float > & estimated_error_per_cell) override virtual
Compute the Kelly error estimator on the phase parameter for mesh refinement. See : https://www.dealii.org/current/doxygen/deal.II/classKellyErrorEstimator.html for more information on the Kelly error estimator.
Parameters
ivar The current element of the map simulation_parameters.mesh_adaptation.variables
estimated_error_per_cell The deal.II vector of estimated_error_per_cell
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 1798 of file vof.cc.
References Parameters::MeshAdaptation::phase.
copy_local_matrix_to_global_matrix()
template<int dim> void VolumeOfFluid< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell information to global matrix.
Definition at line 176 of file vof.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void VolumeOfFluid< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell rhs information to global rhs.
Definition at line 299 of file vof.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_rhs.
define_non_zero_constraints()
template<int dim> void VolumeOfFluid< dim >::define_non_zero_constraints
defined the non zero constraints used to solve the problem.
Definition at line 2232 of file vof.cc.
References BoundaryConditions::periodic, and BoundaryConditions::vof_dirichlet.
define_zero_constraints()
template<int dim> void VolumeOfFluid< dim >::define_zero_constraints
defined the zero constraints used to solve the problem.
Definition at line 2188 of file vof.cc.
References BoundaryConditions::periodic, and BoundaryConditions::vof_dirichlet.
find_projected_interface_curvature()
template<int dim> void VolumeOfFluid< dim >::find_projected_interface_curvature private
Carries out finding the interface curvature.
Definition at line 1180 of file vof.cc.
find_projected_phase_fraction_gradient()
template<int dim> void VolumeOfFluid< dim >::find_projected_phase_fraction_gradient private
Carries out finding the gradients of phase fraction. Obtained gradients of phase fraction is used in find_projected_interface_curvature to find interface curvature (k).
Definition at line 1172 of file vof.cc.
find_sharpening_threshold()
template<int dim> double VolumeOfFluid< dim >::find_sharpening_threshold private
Find the sharpening threshold to ensure mass conservation of the fluid monitored, as given in the prm (VOF, subsection monitoring), by binary search.
Definition at line 979 of file vof.cc.
References Parameters::quiet.
finish_simulation()
template<int dim> void VolumeOfFluid< dim >::finish_simulation override virtual
Carry out the operations required to finish a simulation correctly.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 609 of file vof.cc.
References Parameters::extra_verbose, Parameters::SimulationControl::steady, and Parameters::verbose.
get_curvature_dof_handler()
template<int dim> DoFHandler<dim>* VolumeOfFluid< dim >::get_curvature_dof_handler () inline
Definition at line 389 of file vof.h.
References VolumeOfFluid< dim >::curvature_dof_handler.
get_curvature_solution()
template<int dim> TrilinosWrappers::MPI::Vector* VolumeOfFluid< dim >::get_curvature_solution () inline
Definition at line 399 of file vof.h.
References VolumeOfFluid< dim >::present_curvature_solution.
get_dof_handler()
template<int dim> const DoFHandler<dim>& VolumeOfFluid< dim >::get_dof_handler () inline override virtual
Getter methods to get the private attributes for the physic currently solved NB : dof_handler and present_solution are passed to the multiphysics interface at the end of the setup_dofs method.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 349 of file vof.h.
References VolumeOfFluid< dim >::dof_handler.
get_evaluation_point()
template<int dim> TrilinosWrappers::MPI::Vector& VolumeOfFluid< dim >::get_evaluation_point () inline override virtual
Getter methods that give access to the private attributes of the physics being solved. These methods must be provided by the physics as they are the key to solve a problem using Lethe.
Implements PhysicsSolver< VectorType >.
Definition at line 354 of file vof.h.
References VolumeOfFluid< dim >::evaluation_point.
get_local_evaluation_point()
template<int dim> TrilinosWrappers::MPI::Vector& VolumeOfFluid< dim >::get_local_evaluation_point () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 359 of file vof.h.
References VolumeOfFluid< dim >::local_evaluation_point.
get_newton_update()
template<int dim> TrilinosWrappers::MPI::Vector& VolumeOfFluid< dim >::get_newton_update () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 364 of file vof.h.
References VolumeOfFluid< dim >::newton_update.
get_nonzero_constraints()
template<int dim> AffineConstraints<double>& VolumeOfFluid< dim >::get_nonzero_constraints () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 379 of file vof.h.
References VolumeOfFluid< dim >::nonzero_constraints.
get_present_solution()
template<int dim> TrilinosWrappers::MPI::Vector& VolumeOfFluid< dim >::get_present_solution () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 369 of file vof.h.
References VolumeOfFluid< dim >::present_solution.
get_projected_phase_fraction_gradient_dof_handler()
template<int dim> DoFHandler<dim>* VolumeOfFluid< dim >::get_projected_phase_fraction_gradient_dof_handler () inline
Definition at line 384 of file vof.h.
References VolumeOfFluid< dim >::projected_phase_fraction_gradient_dof_handler.
get_projected_phase_fraction_gradient_solution()
template<int dim> TrilinosWrappers::MPI::Vector* VolumeOfFluid< dim >::get_projected_phase_fraction_gradient_solution () inline
Definition at line 394 of file vof.h.
References VolumeOfFluid< dim >::present_projected_phase_fraction_gradient_solution.
get_system_rhs()
template<int dim> TrilinosWrappers::MPI::Vector& VolumeOfFluid< dim >::get_system_rhs () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 374 of file vof.h.
References VolumeOfFluid< dim >::system_rhs.
handle_interface_sharpening()
template<int dim> void VolumeOfFluid< dim >::handle_interface_sharpening private
Carries out interface sharpening. It is called in the modify solution function. Launches sharpen_interface with the possibility to ensure conservation and handles output messages.
Definition at line 938 of file vof.cc.
References Parameters::adaptive, and Parameters::quiet.
modify_solution()
template<int dim> void VolumeOfFluid< dim >::modify_solution override virtual
Carry out modifications on the auxiliary physic solution.
Reimplemented from AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 912 of file vof.cc.
percolate_time_vectors()
template<int dim> void VolumeOfFluid< dim >::percolate_time_vectors override virtual
Carry out the operations required to rearrange the values of the previous solution at the end of a time step.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 640 of file vof.cc.
post_mesh_adaptation()
template<int dim> void VolumeOfFluid< dim >::post_mesh_adaptation override virtual
post_mesh_adaption Interpolates the auxiliary physics variables to the new mesh
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 1761 of file vof.cc.
postprocess()
template<int dim> void VolumeOfFluid< dim >::postprocess (bool first_iteration) override virtual
Postprocess the auxiliary physics results. Post-processing this case implies the calculation of all derived quantities using the solution vector of the physics. It does not concern the output of the solution using the DataOutObject, which is accomplished through the attach_solution_to_output function.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 651 of file vof.cc.
References announce_string(), calculate_L2_error(), Parameters::fluid0, Parameters::fluid1, fluid_dynamics, Parameters::Timer::iteration, make_table_scalars_tensors(), and Parameters::verbose.
pre_mesh_adaptation()
template<int dim> void VolumeOfFluid< dim >::pre_mesh_adaptation override virtual
pre_mesh_adaption Prepares the auxiliary physics variables for a mesh refinement/coarsening
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 1747 of file vof.cc.
read_checkpoint()
template<int dim> void VolumeOfFluid< dim >::read_checkpoint override virtual
Set solution vector of Auxiliary Physics using checkpoint.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 1873 of file vof.cc.
References deserialize_table(), Parameters::fluid0, and Parameters::fluid1.
set_initial_conditions()
template<int dim> void VolumeOfFluid< dim >::set_initial_conditions override virtual
Sets-up the initial conditions associated with the physics. Generally, physics only support imposing nodal values, but some physics additionnaly support the use of L2 projection or steady-state solutions.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 2278 of file vof.cc.
setup_assemblers()
template<int dim> void VolumeOfFluid< dim >::setup_assemblers private virtual
sets up the vector of assembler functions
Definition at line 47 of file vof.cc.
References is_bdf().
setup_dofs()
template<int dim> void VolumeOfFluid< dim >::setup_dofs override virtual
Sets-up the DofHandler and the degree of freedom associated with the physics.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 1942 of file vof.cc.
References VOF.
sharpen_interface()
template<int dim> void VolumeOfFluid< dim >::sharpen_interface (TrilinosWrappers::MPI::Vector & solution, const double sharpening_threshold, const bool sharpen_previous_solutions) private
Carries out interface sharpening. It is called in the modify solution function.
Parameters
solution VOF solution (phase fraction)
sharpening_threshold Interface sharpening threshold that represents the mass conservation level
sharpen_previous_solutions Boolean true if sharpening is applied on the present and past solutions, false if the sharpening is applied on the given solution vector only. Used to determine the sharpening threshold by binary search.
Definition at line 1126 of file vof.cc.
smooth_phase_fraction()
template<int dim> void VolumeOfFluid< dim >::smooth_phase_fraction private
Carries out the smoothing phase fraction with a projection step (to avoid a staircase interface).
Definition at line 1164 of file vof.cc.
solve_curvature()
template<int dim> void VolumeOfFluid< dim >::solve_curvature private
Solves curvature system.
Definition at line 1694 of file vof.cc.
References Parameters::quiet, and VOF.
solve_interface_sharpening()
template<int dim> void VolumeOfFluid< dim >::solve_interface_sharpening (TrilinosWrappers::MPI::Vector & solution) private
Solves the assembled system to sharpen the interface. The linear_solver_tolerance is hardcoded = 1e-15, and an ILU Preconditioner is used. After solving the system, this function overwrites the solution with the sharpened solution.
Parameters
solution VOF solution (phase fraction)
Definition at line 2537 of file vof.cc.
References Parameters::extra_verbose, and VOF.
solve_linear_system()
template<int dim> void VolumeOfFluid< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) override virtual
Call for the solution of the linear system of equation using a strategy appropriate to the auxiliary physics.
Parameters
initial_step Provides the linear solver with indication if this solution is the first one for the system of equation or not
renewed_matrix Indicates to the linear solve if the system matrix has been recalculated or not
Implements PhysicsSolver< VectorType >.
Definition at line 2296 of file vof.cc.
References Parameters::quiet, and VOF.
solve_projected_phase_fraction_gradient()
template<int dim> void VolumeOfFluid< dim >::solve_projected_phase_fraction_gradient private
Solves phase fraction gradient system.
Definition at line 1500 of file vof.cc.
References Parameters::quiet, and VOF.
solve_projection_phase_fraction()
template<int dim> void VolumeOfFluid< dim >::solve_projection_phase_fraction (TrilinosWrappers::MPI::Vector & solution) private
Solves smooth phase fraction system.
Parameters
solution VOF solution (phase fraction)
Definition at line 1295 of file vof.cc.
References Parameters::quiet, and VOF.
update_boundary_conditions()
template<int dim> void VolumeOfFluid< dim >::update_boundary_conditions override virtual
Update non zero constraints if the boundary is time dependent.
Reimplemented from AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 2165 of file vof.cc.
References BoundaryConditions::vof_dirichlet.
update_solution_and_constraints()
template<int dim> void VolumeOfFluid< dim >::update_solution_and_constraints (TrilinosWrappers::MPI::Vector & solution) private
Limit the phase fractions between 0 and 1. This is necessary before interface sharpening. More information can be found in step_41 of deal.II tutorials: https://www.dealii.org/current/doxygen/deal.II/step_41.html.
Definition at line 2371 of file vof.cc.
write_checkpoint()
template<int dim> void VolumeOfFluid< dim >::write_checkpoint override virtual
Prepares auxiliary physics to write checkpoint.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 1820 of file vof.cc.
References Parameters::fluid0, Parameters::fluid1, and serialize_table().
Member Data Documentation
assemblers
template<int dim> std::vector<std::shared_ptr<VOFAssemblerBase<dim> > > VolumeOfFluid< dim >::assemblers private
Definition at line 768 of file vof.h.
bounding_constraints
template<int dim> AffineConstraints<double> VolumeOfFluid< dim >::bounding_constraints private
Definition at line 700 of file vof.h.
cell_quadrature
template<int dim> std::shared_ptr<Quadrature<dim> > VolumeOfFluid< dim >::cell_quadrature private
Definition at line 687 of file vof.h.
complete_system_matrix_phase_fraction
template<int dim> TrilinosWrappers::SparseMatrix VolumeOfFluid< dim >::complete_system_matrix_phase_fraction private
Definition at line 719 of file vof.h.
complete_system_rhs_phase_fraction
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::complete_system_rhs_phase_fraction private
Definition at line 721 of file vof.h.
computing_timer
template<int dim> TimerOutput VolumeOfFluid< dim >::computing_timer private
Definition at line 668 of file vof.h.
curvature_constraints
template<int dim> AffineConstraints<double> VolumeOfFluid< dim >::curvature_constraints private
Definition at line 742 of file vof.h.
curvature_dof_handler
template<int dim> DoFHandler<dim> VolumeOfFluid< dim >::curvature_dof_handler private
Definition at line 677 of file vof.h.
curvature_mapping
template<int dim> std::shared_ptr<Mapping<dim> > VolumeOfFluid< dim >::curvature_mapping private
Definition at line 686 of file vof.h.
curvature_values
template<int dim> std::vector<double> VolumeOfFluid< dim >::curvature_values private
Definition at line 747 of file vof.h.
dof_handler
template<int dim> DoFHandler<dim> VolumeOfFluid< dim >::dof_handler private
Definition at line 675 of file vof.h.
error_table
template<int dim> ConvergenceTable VolumeOfFluid< dim >::error_table private
Definition at line 681 of file vof.h.
evaluation_point
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::evaluation_point private
Definition at line 694 of file vof.h.
face_quadrature
template<int dim> std::shared_ptr<Quadrature<dim - 1> > VolumeOfFluid< dim >::face_quadrature private
Definition at line 688 of file vof.h.
fe
template<int dim> std::shared_ptr<FiniteElement<dim> > VolumeOfFluid< dim >::fe private
Definition at line 678 of file vof.h.
fe_curvature
template<int dim> std::shared_ptr<FiniteElement<dim> > VolumeOfFluid< dim >::fe_curvature private
Definition at line 680 of file vof.h.
fe_projected_phase_fraction_gradient
template<int dim> std::shared_ptr<FESystem<dim> > VolumeOfFluid< dim >::fe_projected_phase_fraction_gradient private
Definition at line 679 of file vof.h.
filter
template<int dim> std::shared_ptr<VolumeOfFluidFilterBase> VolumeOfFluid< dim >::filter private
Definition at line 771 of file vof.h.
filtered_solution
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::filtered_solution private
Definition at line 704 of file vof.h.
ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> VolumeOfFluid< dim >::ilu_preconditioner private
Definition at line 751 of file vof.h.
local_evaluation_point
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::local_evaluation_point private
Definition at line 695 of file vof.h.
locally_owned_dofs
template<int dim> IndexSet VolumeOfFluid< dim >::locally_owned_dofs private
Definition at line 691 of file vof.h.
locally_owned_dofs_curvature
template<int dim> IndexSet VolumeOfFluid< dim >::locally_owned_dofs_curvature private
Definition at line 740 of file vof.h.
locally_owned_dofs_projected_phase_fraction_gradient
template<int dim> IndexSet VolumeOfFluid< dim >::locally_owned_dofs_projected_phase_fraction_gradient private
Definition at line 727 of file vof.h.
locally_relevant_dofs
template<int dim> IndexSet VolumeOfFluid< dim >::locally_relevant_dofs private
Definition at line 692 of file vof.h.
locally_relevant_dofs_curvature
template<int dim> IndexSet VolumeOfFluid< dim >::locally_relevant_dofs_curvature private
Definition at line 741 of file vof.h.
locally_relevant_dofs_projected_phase_fraction_gradient
template<int dim> IndexSet VolumeOfFluid< dim >::locally_relevant_dofs_projected_phase_fraction_gradient private
Definition at line 728 of file vof.h.
mapping
template<int dim> std::shared_ptr<Mapping<dim> > VolumeOfFluid< dim >::mapping private
Definition at line 684 of file vof.h.
mass_first_iteration
template<int dim> double VolumeOfFluid< dim >::mass_first_iteration private
Definition at line 761 of file vof.h.
mass_matrix_phase_fraction
template<int dim> TrilinosWrappers::SparseMatrix VolumeOfFluid< dim >::mass_matrix_phase_fraction private
Definition at line 722 of file vof.h.
mass_monitored
template<int dim> double VolumeOfFluid< dim >::mass_monitored private
Definition at line 760 of file vof.h.
multiphysics
template<int dim> MultiphysicsInterface<dim>* VolumeOfFluid< dim >::multiphysics private
Definition at line 666 of file vof.h.
newton_update
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::newton_update private
Definition at line 696 of file vof.h.
nodal_curvature_owned
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::nodal_curvature_owned private
Definition at line 744 of file vof.h.
nodal_curvature_relevant
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::nodal_curvature_relevant private
Definition at line 743 of file vof.h.
nodal_phase_fraction_owned
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::nodal_phase_fraction_owned private
Definition at line 664 of file vof.h.
nodal_projected_phase_fraction_gradient_owned
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::nodal_projected_phase_fraction_gradient_owned private
Definition at line 732 of file vof.h.
nodal_projected_phase_fraction_gradient_relevant
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::nodal_projected_phase_fraction_gradient_relevant private
Definition at line 731 of file vof.h.
nonzero_constraints
template<int dim> AffineConstraints<double> VolumeOfFluid< dim >::nonzero_constraints private
Definition at line 699 of file vof.h.
phase_lower_bound
template<int dim> const double VolumeOfFluid< dim >::phase_lower_bound = 0.0 private
Definition at line 755 of file vof.h.
phase_upper_bound
template<int dim> const double VolumeOfFluid< dim >::phase_upper_bound = 1.0 private
Definition at line 754 of file vof.h.
present_curvature_solution
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::present_curvature_solution private
Definition at line 739 of file vof.h.
present_projected_phase_fraction_gradient_solution
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::present_projected_phase_fraction_gradient_solution private
Definition at line 726 of file vof.h.
present_solution
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::present_solution private
Definition at line 697 of file vof.h.
previous_solutions
template<int dim> std::vector<TrilinosWrappers::MPI::Vector> VolumeOfFluid< dim >::previous_solutions private
Definition at line 707 of file vof.h.
previous_solutions_transfer
template<int dim> std::vector< parallel::distributed::SolutionTransfer<dim, TrilinosWrappers::MPI::Vector> > VolumeOfFluid< dim >::previous_solutions_transfer private
Definition at line 715 of file vof.h.
projected_phase_fraction_gradient_constraints
template<int dim> AffineConstraints<double> VolumeOfFluid< dim >::projected_phase_fraction_gradient_constraints private
Definition at line 729 of file vof.h.
projected_phase_fraction_gradient_dof_handler
template<int dim> DoFHandler<dim> VolumeOfFluid< dim >::projected_phase_fraction_gradient_dof_handler private
Definition at line 676 of file vof.h.
projected_phase_fraction_gradient_mapping
template<int dim> std::shared_ptr<Mapping<dim> > VolumeOfFluid< dim >::projected_phase_fraction_gradient_mapping private
Definition at line 685 of file vof.h.
projected_phase_fraction_gradient_values
template<int dim> std::vector<Tensor<1, dim> > VolumeOfFluid< dim >::projected_phase_fraction_gradient_values private
Definition at line 746 of file vof.h.
sharpening_threshold
template<int dim> double VolumeOfFluid< dim >::sharpening_threshold private
Definition at line 762 of file vof.h.
simulation_control
template<int dim> std::shared_ptr<SimulationControl> VolumeOfFluid< dim >::simulation_control private
Definition at line 674 of file vof.h.
simulation_parameters
template<int dim> const SimulationParameters<dim>& VolumeOfFluid< dim >::simulation_parameters private
Definition at line 670 of file vof.h.
solution_pw
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::solution_pw private
Definition at line 703 of file vof.h.
solution_transfer
template<int dim> std::shared_ptr< parallel::distributed::SolutionTransfer<dim, TrilinosWrappers::MPI::Vector> > VolumeOfFluid< dim >::solution_transfer private
Definition at line 712 of file vof.h.
system_matrix
template<int dim> TrilinosWrappers::SparseMatrix VolumeOfFluid< dim >::system_matrix private
Definition at line 702 of file vof.h.
system_matrix_curvature
template<int dim> TrilinosWrappers::SparseMatrix VolumeOfFluid< dim >::system_matrix_curvature private
Definition at line 749 of file vof.h.
system_matrix_phase_fraction
template<int dim> TrilinosWrappers::SparseMatrix VolumeOfFluid< dim >::system_matrix_phase_fraction private
Definition at line 718 of file vof.h.
system_matrix_projected_phase_fraction_gradient
template<int dim> TrilinosWrappers::SparseMatrix VolumeOfFluid< dim >::system_matrix_projected_phase_fraction_gradient private
Definition at line 735 of file vof.h.
system_rhs
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::system_rhs private
Definition at line 698 of file vof.h.
system_rhs_curvature
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::system_rhs_curvature private
Definition at line 750 of file vof.h.
system_rhs_phase_fraction
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::system_rhs_phase_fraction private
Definition at line 720 of file vof.h.
system_rhs_projected_phase_fraction_gradient
template<int dim> TrilinosWrappers::MPI::Vector VolumeOfFluid< dim >::system_rhs_projected_phase_fraction_gradient private
Definition at line 736 of file vof.h.
table_barycenter
template<int dim> TableHandler VolumeOfFluid< dim >::table_barycenter private
Definition at line 765 of file vof.h.
table_monitoring_vof
template<int dim> TableHandler VolumeOfFluid< dim >::table_monitoring_vof private
Definition at line 758 of file vof.h.
triangulation
template<int dim> std::shared_ptr<parallel::DistributedTriangulationBase<dim> > VolumeOfFluid< dim >::triangulation private
Definition at line 673 of file vof.h.
volume_monitored
template<int dim> double VolumeOfFluid< dim >::volume_monitored private
Definition at line 759 of file vof.h.
zero_constraints
template<int dim> AffineConstraints<double> VolumeOfFluid< dim >::zero_constraints private
Definition at line 701 of file vof.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/vof.h
/home/runner/work/lethe/lethe/source/solvers/vof.cc