Developer documentation for the Lethe open-source library: IBStencil< dim > Class Template Reference
IBStencil< dim > Class Template Reference
#include <ib_stencil.h>
Public Member Functions
virtual unsigned int number_of_interpolation_support_points (const unsigned int order)
Return the number of points used by the interpolation stencil excluding the dof itself for a stencil of a given order.
virtual std::tuple< Point< dim >, std::vector< Point< dim > > > support_points_for_interpolation (const unsigned int order, const double length_ratio, IBParticle< dim > &p, const Point< dim > &dof_point, const typename DoFHandler< dim >::active_cell_iterator &cell_guess)
Define the points for the IB stencil, based on the order and the particle position as well as the DOF position Depending on the order, the output variable "point" change definition. In the case of stencil orders 1 to 4 the variable point returns the position of the DOF directly. In the case of high order stencil, it returns the position of the point that is on the IB. The variable "interpolation points" return the points used to define the cell used for the stencil definition and the locations of the points use in the stencil calculation.
virtual std::tuple< Point< dim >, std::vector< Point< dim > > > support_points_for_interpolation (const unsigned int order, const double length_ratio, IBParticle< dim > &p, const Point< dim > &dof_point)
virtual Point< dim > point_for_cell_detection (IBParticle< dim > &p, const Point< dim > &dof_point, const typename DoFHandler< dim >::active_cell_iterator &cell_guess)
Define the point used to define the cell used for the stencil calculation.
virtual Point< dim > point_for_cell_detection (IBParticle< dim > &p, const Point< dim > &dof_point)
virtual std::vector< double > coefficients (const unsigned int order, const double length_ratio)
Return the coefficient of the stencil based on the order. The coefficients of the IB stencil assume a ratio of length between the distance of the farthest interpolation point and the DOF and the distance between the IB and the DOF of 1/8. The coefficient order goes from the coefficient of the DOF to the coefficient of the farthest interpolation point.
virtual double ib_velocity (IBParticle< dim > &p, const Point< dim > &dof_point, const unsigned int component, const typename DoFHandler< dim >::active_cell_iterator &cell_guess)
Return the velocity of the IB used in the RHS of the equation.
virtual double ib_velocity (IBParticle< dim > &p, const Point< dim > &dof_point, const unsigned int component)
Private Member Functions
void p_base (unsigned int order)
Return the points on the reference 1D element for the polynomial base.
Private Attributes
std::vector< double > reference_points
Detailed Description
template<int dim>
class IBStencil< dim >
Definition at line 34 of file ib_stencil.h.
Member Function Documentation
coefficients()
template<int dim> std::vector< double > IBStencil< dim >::coefficients (const unsigned int order, const double length_ratio) virtual
Return the coefficient of the stencil based on the order. The coefficients of the IB stencil assume a ratio of length between the distance of the farthest interpolation point and the DOF and the distance between the IB and the DOF of 1/8. The coefficient order goes from the coefficient of the DOF to the coefficient of the farthest interpolation point.
Parameters
order,the stencil order.
length_ratio the length ratio between the 2 side of the stencil.
Definition at line 38 of file ib_stencil.cc.
ib_velocity() [1/2]
template<int dim> double IBStencil< dim >::ib_velocity (IBParticle< dim > & p, const Point< dim > & dof_point, const unsigned int component) virtual
See overloaded function
Definition at line 290 of file ib_stencil.cc.
References IBParticle< dim >::closest_surface_point(), IBParticle< dim >::omega, IBParticle< dim >::position, and IBParticle< dim >::velocity.
ib_velocity() [2/2]
template<int dim> double IBStencil< dim >::ib_velocity (IBParticle< dim > & p, const Point< dim > & dof_point, const unsigned int component, const typename DoFHandler< dim >::active_cell_iterator & cell_guess) virtual
Return the velocity of the IB used in the RHS of the equation.
Parameters
p,the IB particle that cuts the cell.
dof_point,the support point of the DOF.
component,the stencil component of the dof (vx=0,vy=1,vz=2).
cell_guess A guess of the cell containing the evaluation point, which is useful to reduce computation time
Definition at line 223 of file ib_stencil.cc.
References IBParticle< dim >::closest_surface_point(), IBParticle< dim >::omega, IBParticle< dim >::position, and IBParticle< dim >::velocity.
number_of_interpolation_support_points()
template<int dim> unsigned int IBStencil< dim >::number_of_interpolation_support_points (const unsigned int order) virtual
Return the number of points used by the interpolation stencil excluding the dof itself for a stencil of a given order.
Parameters
order,the stencil order.
Definition at line 10 of file ib_stencil.cc.
p_base()
template<int dim> void IBStencil< dim >::p_base (unsigned int order) private
Return the points on the reference 1D element for the polynomial base.
Parameters
order,the order of the stencil.
Definition at line 24 of file ib_stencil.cc.
point_for_cell_detection() [1/2]
template<int dim> Point< dim > IBStencil< dim >::point_for_cell_detection (IBParticle< dim > & p, const Point< dim > & dof_point) virtual
See overloaded function
Definition at line 206 of file ib_stencil.cc.
References IBParticle< dim >::closest_surface_point().
point_for_cell_detection() [2/2]
template<int dim> Point< dim > IBStencil< dim >::point_for_cell_detection (IBParticle< dim > & p, const Point< dim > & dof_point, const typename DoFHandler< dim >::active_cell_iterator & cell_guess) virtual
Define the point used to define the cell used for the stencil calculation.
Parameters
p,the IB particle that cuts the cell.
dof_point,the support point of the DOF.
cell_guess A guess of the cell containing the evaluation point, which is useful to reduce computation time
Definition at line 187 of file ib_stencil.cc.
References IBParticle< dim >::closest_surface_point().
support_points_for_interpolation() [1/2]
template<int dim> std::tuple< Point< dim >, std::vector< Point< dim > > > IBStencil< dim >::support_points_for_interpolation (const unsigned int order, const double length_ratio, IBParticle< dim > & p, const Point< dim > & dof_point) virtual
See overloaded function
Definition at line 142 of file ib_stencil.cc.
References IBParticle< dim >::closest_surface_point().
support_points_for_interpolation() [2/2]
template<int dim> std::tuple< Point< dim >, std::vector< Point< dim > > > IBStencil< dim >::support_points_for_interpolation (const unsigned int order, const double length_ratio, IBParticle< dim > & p, const Point< dim > & dof_point, const typename DoFHandler< dim >::active_cell_iterator & cell_guess) virtual
Define the points for the IB stencil, based on the order and the particle position as well as the DOF position Depending on the order, the output variable "point" change definition. In the case of stencil orders 1 to 4 the variable point returns the position of the DOF directly. In the case of high order stencil, it returns the position of the point that is on the IB. The variable "interpolation points" return the points used to define the cell used for the stencil definition and the locations of the points use in the stencil calculation.
Parameters
order,the stencil order.
length_ratio the length ratio between the 2 side of the stencil.
p,the IB particle that cuts the cell.
dof_point,the support point of the DOF.
cell_guess A guess of the cell containing the evaluation point, which is useful to reduce computation time
Definition at line 95 of file ib_stencil.cc.
References IBParticle< dim >::closest_surface_point().
Member Data Documentation
reference_points
template<int dim> std::vector<double> IBStencil< dim >::reference_points private
Definition at line 154 of file ib_stencil.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/ib_stencil.h
/home/runner/work/lethe/lethe/source/core/ib_stencil.cc