Developer documentation for the Lethe open-source library: PhysicsSolver< VectorType > Class Template Reference
PhysicsSolver< VectorType > Class Template Reference abstract
Class that has all the common elements of a physics solver. It creates the nonlinear solver as specified by the user using the parameters file and provides all the necessary elements needed by the solver to solve a physics problem.
#include <physics_solver.h>
Public Member Functions
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
virtual void assemble_system_matrix ()=0
assemble_system_matrix Assembles the matrix
virtual void assemble_system_rhs ()=0
assemble_system_rhs Assembles the rhs
virtual void solve_linear_system (const bool initial_step, const bool renewed_matrix=true)=0
solve_linear_system Solves the linear system of equations
void solve_non_linear_system (const bool first_iteration)
solve_non_linear_system Solves the non linear system of equations
virtual void apply_constraints ()
Applies constraints to a local_evaluation_point.
virtual VectorType & get_evaluation_point ()=0
Getter methods that give access to the private attributes of the physics being solved. These methods must be provided by the physics as they are the key to solve a problem using Lethe.
virtual VectorType & get_local_evaluation_point ()=0
virtual VectorType & get_newton_update ()=0
virtual VectorType & get_present_solution ()=0
virtual VectorType & get_system_rhs ()=0
virtual AffineConstraints< double > & get_nonzero_constraints ()=0
virtual double get_current_residual ()
Default way to evaluate the residual for the nonlinear solver. Some application may use more complex evaluation of the residual and override this method.
Public Attributes
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Private Attributes
NonLinearSolver< VectorType > * non_linear_solver
Detailed Description
template<typename VectorType>
class PhysicsSolver< VectorType >
Class that has all the common elements of a physics solver. It creates the nonlinear solver as specified by the user using the parameters file and provides all the necessary elements needed by the solver to solve a physics problem.
Parameters
non_linear_solver_parameters A set of parameters that will be used to construct the non-linear solver
Definition at line 36 of file physics_solver.h.
Constructor & Destructor Documentation
PhysicsSolver()
template<typename VectorType > PhysicsSolver< VectorType >::PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
Definition at line 128 of file physics_solver.h.
References Parameters::NonLinearSolver::inexact_newton, Parameters::NonLinearSolver::kinsol_newton, Parameters::NonLinearSolver::newton, PhysicsSolver< VectorType >::non_linear_solver, and Parameters::NonLinearSolver::solver.
~PhysicsSolver()
template<typename VectorType > virtual PhysicsSolver< VectorType >::~PhysicsSolver () inline virtual
Definition at line 41 of file physics_solver.h.
References PhysicsSolver< VectorType >::non_linear_solver.
Member Function Documentation
apply_constraints()
template<typename VectorType > virtual void PhysicsSolver< VectorType >::apply_constraints () inline virtual
Applies constraints to a local_evaluation_point.
Definition at line 83 of file physics_solver.h.
References PhysicsSolver< VectorType >::get_local_evaluation_point(), and PhysicsSolver< VectorType >::get_nonzero_constraints().
assemble_system_matrix()
template<typename VectorType > virtual void PhysicsSolver< VectorType >::assemble_system_matrix () pure virtual
assemble_system_matrix Assembles the matrix
Implemented in VolumeOfFluid< dim >, Tracer< dim >, MFNavierStokesSolver< dim >, HeatTransfer< dim >, GLSNitscheNavierStokesSolver< dim, spacedim >, GLSNavierStokesSolver< dim >, GDNavierStokesSolver< dim >, CahnHilliard< dim >, GLSVANSSolver< dim >, and GLSSharpNavierStokesSolver< dim >.
assemble_system_rhs()
template<typename VectorType > virtual void PhysicsSolver< VectorType >::assemble_system_rhs () pure virtual
assemble_system_rhs Assembles the rhs
Implemented in VolumeOfFluid< dim >, Tracer< dim >, MFNavierStokesSolver< dim >, HeatTransfer< dim >, GLSNitscheNavierStokesSolver< dim, spacedim >, GLSNavierStokesSolver< dim >, GDNavierStokesSolver< dim >, CahnHilliard< dim >, GLSVANSSolver< dim >, and GLSSharpNavierStokesSolver< dim >.
get_current_residual()
template<typename VectorType > virtual double PhysicsSolver< VectorType >::get_current_residual () inline virtual
Default way to evaluate the residual for the nonlinear solver. Some application may use more complex evaluation of the residual and override this method.
Reimplemented in GLSSharpNavierStokesSolver< dim >.
Definition at line 114 of file physics_solver.h.
References PhysicsSolver< VectorType >::get_system_rhs().
get_evaluation_point()
template<typename VectorType > virtual VectorType& PhysicsSolver< VectorType >::get_evaluation_point () pure virtual
Getter methods that give access to the private attributes of the physics being solved. These methods must be provided by the physics as they are the key to solve a problem using Lethe.
Implemented in VolumeOfFluid< dim >, Tracer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >, NavierStokesBase< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, HeatTransfer< dim >, and CahnHilliard< dim >.
get_local_evaluation_point()
template<typename VectorType > virtual VectorType& PhysicsSolver< VectorType >::get_local_evaluation_point () pure virtual
Implemented in VolumeOfFluid< dim >, Tracer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >, NavierStokesBase< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, HeatTransfer< dim >, and CahnHilliard< dim >.
get_newton_update()
template<typename VectorType > virtual VectorType& PhysicsSolver< VectorType >::get_newton_update () pure virtual
Implemented in VolumeOfFluid< dim >, Tracer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >, NavierStokesBase< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, HeatTransfer< dim >, and CahnHilliard< dim >.
get_nonzero_constraints()
template<typename VectorType > virtual AffineConstraints<double>& PhysicsSolver< VectorType >::get_nonzero_constraints () pure virtual
Implemented in VolumeOfFluid< dim >, Tracer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >, NavierStokesBase< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, HeatTransfer< dim >, and CahnHilliard< dim >.
get_present_solution()
template<typename VectorType > virtual VectorType& PhysicsSolver< VectorType >::get_present_solution () pure virtual
Implemented in VolumeOfFluid< dim >, Tracer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >, NavierStokesBase< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, HeatTransfer< dim >, and CahnHilliard< dim >.
get_system_rhs()
template<typename VectorType > virtual VectorType& PhysicsSolver< VectorType >::get_system_rhs () pure virtual
Implemented in VolumeOfFluid< dim >, Tracer< dim >, NavierStokesBase< dim, VectorType, DofsType >, NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >, NavierStokesBase< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > >, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >, HeatTransfer< dim >, and CahnHilliard< dim >.
solve_linear_system()
template<typename VectorType > virtual void PhysicsSolver< VectorType >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) pure virtual
solve_linear_system Solves the linear system of equations
Parameters
initial_step Provides the linear solver with indication if this solution is the first one for the system of equation or not
renewed_matrix Indicates to the linear solve if the system matrix has been recalculated or not
Implemented in VolumeOfFluid< dim >, Tracer< dim >, MFNavierStokesSolver< dim >, HeatTransfer< dim >, GLSNavierStokesSolver< dim >, CahnHilliard< dim >, and GDNavierStokesSolver< dim >.
solve_non_linear_system()
template<typename VectorType > void PhysicsSolver< VectorType >::solve_non_linear_system (const bool first_iteration)
solve_non_linear_system Solves the non linear system of equations
Parameters
first_iteration Indicates whether it is the first iteration of the non linear solver
Definition at line 154 of file physics_solver.h.
Member Data Documentation
non_linear_solver
template<typename VectorType > NonLinearSolver<VectorType>* PhysicsSolver< VectorType >::non_linear_solver private
Definition at line 124 of file physics_solver.h.
pcout
template<typename VectorType > ConditionalOStream PhysicsSolver< VectorType >::pcout
Definition at line 120 of file physics_solver.h.
time_stepping_method
template<typename VectorType > Parameters::SimulationControl::TimeSteppingMethod PhysicsSolver< VectorType >::time_stepping_method
Definition at line 121 of file physics_solver.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/core/non_linear_solver.h
/home/runner/work/lethe/lethe/include/core/physics_solver.h