Developer documentation for the Lethe open-source library: CahnHilliard< dim > Class Template Reference
CahnHilliard< dim > Class Template Reference
#include <cahn_hilliard.h>
Public Member Functions
CahnHilliard (MultiphysicsInterface< dim > *multiphysics_interface, const SimulationParameters< dim > &p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim >> p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control)
void attach_solution_to_output (DataOut< dim > &data_out) override
Attach the solution vector to the DataOut provided. This function enable the auxiliary physics to output their solution via the core solver.
std::pair< double, double > calculate_L2_error ()
Calculates the L2 error of the solution.
void finish_simulation () override
Carry out the operations required to finish a simulation correctly.
void percolate_time_vectors () override
Rearrange vector solution correctly for transient simulations.
void postprocess (bool first_iteration) override
Postprocess the auxiliary physics results. Post-processing this case implies the calculation of all derived quantities using the solution vector of the physics. It does not concern the output of the solution using the DataOutObject, which is accomplished through the attach_solution_to_output function.
void pre_mesh_adaptation () override
pre_mesh_adaption Prepares the auxiliary physics variables for a mesh refinement/coarsening
void post_mesh_adaptation () override
post_mesh_adaption Interpolates the auxiliary physics variables to the new mesh
void compute_kelly (const std::pair< const Parameters::MeshAdaptation::Variable, Parameters::MultipleAdaptationParameters > &ivar, dealii::Vector< float > &estimated_error_per_cell) override
Compute the Kelly error estimator for mesh refinement. NB : not implemented for the cahn_hilliard equations for now.
void write_checkpoint () override
Prepares Cahn-Hilliard to write checkpoint.
void read_checkpoint () override
Allows Cahn-Hilliard physics to set-up solution vector from checkpoint file;.
const DoFHandler< dim > & get_dof_handler () override
Returns the dof_handler of the Cahn-Hilliard physics.
void setup_dofs () override
Sets-up the DofHandler and the degree of freedom associated with the physics.
void set_initial_conditions () override
Sets-up the initial conditions associated with the physics. Generally, physics only support imposing nodal values, but some physics additionally support the use of L2 projection or steady-state solutions.
void update_boundary_conditions () override
Update non zero constraints if the boundary is time-dependent.
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
Call for the solution of the linear system of equation using a strategy appropriate to the auxiliary physics.
TrilinosWrappers::MPI::Vector & get_evaluation_point () override
Getter methods to get the private attributes for the physic currently solved NB : dof_handler and present_solution are passed to the multiphysics interface at the end of the setup_dofs method.
TrilinosWrappers::MPI::Vector & get_local_evaluation_point () override
TrilinosWrappers::MPI::Vector & get_newton_update () override
TrilinosWrappers::MPI::Vector & get_present_solution () override
TrilinosWrappers::MPI::Vector & get_system_rhs () override
AffineConstraints< double > & get_nonzero_constraints () override
Public Member Functions inherited from AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >
AuxiliaryPhysics (const Parameters::NonLinearSolver non_linear_solver_parameters)
AuxiliaryPhysics - Base constructor for Auxiliary physics. At the present moment this is an interface with nothing. The auxiliary physics is a pure virtual class.
virtual ~AuxiliaryPhysics ()
AuxiliaryPhysics - Base destructor. At the present moment this is an interface with nothing.
virtual void modify_solution ()
Carry out modifications on the auxiliary physic solution. To be defined for some physics only (eg. free surface, see vof.h).
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
solve_non_linear_system Solves the non linear system of equations
virtual void apply_constraints ()
Applies constraints to a local_evaluation_point.
virtual double get_current_residual ()
Default way to evaluate the residual for the nonlinear solver. Some application may use more complex evaluation of the residual and override this method.
Private Member Functions
void assemble_system_matrix () override
Assembles the matrix associated with the solver.
void assemble_system_rhs () override
Assemble the rhs associated with the solver.
virtual void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, CahnHilliardScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
Assemble the local matrix for a given cell.
virtual void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, CahnHilliardScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
Assemble the local rhs for a given cell.
virtual void setup_assemblers ()
sets up the vector of assembler functions
virtual void copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData &copy_data)
Copy local cell information to global matrix.
virtual void copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData &copy_data)
Copy local cell rhs information to global rhs.
void calculate_phase_statistics ()
Calculate phase order parameter integral for monitoring purposes.
void write_phase_statistics ()
Writes the phase integral to an output file.
template<typename VectorType >
std::pair< Tensor< 1, dim >, Tensor< 1, dim > > calculate_barycenter (const TrilinosWrappers::MPI::Vector &solution, const VectorType &current_solution_fd)
Calculates the barycenter of fluid 1 and its velocity.
Private Attributes
MultiphysicsInterface< dim > * multiphysics
TimerOutput computing_timer
const SimulationParameters< dim > & simulation_parameters
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
std::shared_ptr< SimulationControl > simulation_control
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
ConvergenceTable error_table
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
TrilinosWrappers::MPI::Vector evaluation_point
TrilinosWrappers::MPI::Vector local_evaluation_point
TrilinosWrappers::MPI::Vector newton_update
TrilinosWrappers::MPI::Vector present_solution
TrilinosWrappers::MPI::Vector system_rhs
AffineConstraints< double > nonzero_constraints
AffineConstraints< double > zero_constraints
TrilinosWrappers::SparseMatrix system_matrix
std::vector< TrilinosWrappers::MPI::Vector > previous_solutions
std::shared_ptr< parallel::distributed::SolutionTransfer< dim, TrilinosWrappers::MPI::Vector > > solution_transfer
std::vector< parallel::distributed::SolutionTransfer< dim, TrilinosWrappers::MPI::Vector > > previous_solutions_transfer
std::vector< std::shared_ptr< CahnHilliardAssemblerBase< dim > > > assemblers
TableHandler barycenter_table
TableHandler statistics_table
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class CahnHilliard< dim >
Definition at line 58 of file cahn_hilliard.h.
Constructor & Destructor Documentation
CahnHilliard()
template<int dim> CahnHilliard< dim >::CahnHilliard (MultiphysicsInterface< dim > * multiphysics_interface, const SimulationParameters< dim > & p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim >> p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control) inline
Definition at line 61 of file cahn_hilliard.h.
References CahnHilliard< dim >::cell_quadrature, CahnHilliard< dim >::computing_timer, CahnHilliard< dim >::dof_handler, CahnHilliard< dim >::face_quadrature, CahnHilliard< dim >::fe, CahnHilliard< dim >::mapping, maximum_number_of_previous_solutions(), Parameters::Timer::none, CahnHilliard< dim >::previous_solutions, CahnHilliard< dim >::previous_solutions_transfer, CahnHilliard< dim >::simulation_parameters, and CahnHilliard< dim >::solution_transfer.
Member Function Documentation
assemble_local_system_matrix()
template<int dim> void CahnHilliard< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, CahnHilliardScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for CahnHilliardScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 107 of file cahn_hilliard.cc.
References StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, CahnHilliardScratchData< dim >::reinit(), CahnHilliardScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_local_system_rhs()
template<int dim> void CahnHilliard< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, CahnHilliardScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for CahnHilliardScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 206 of file cahn_hilliard.cc.
References StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, CahnHilliardScratchData< dim >::reinit(), CahnHilliardScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_system_matrix()
template<int dim> void CahnHilliard< dim >::assemble_system_matrix override private virtual
Assembles the matrix associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 75 of file cahn_hilliard.cc.
References CahnHilliard< dim >::assemble_local_system_matrix(), CahnHilliard< dim >::copy_local_matrix_to_global_matrix(), and fluid_dynamics.
assemble_system_rhs()
template<int dim> void CahnHilliard< dim >::assemble_system_rhs override private virtual
Assemble the rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 174 of file cahn_hilliard.cc.
References CahnHilliard< dim >::assemble_local_system_rhs(), CahnHilliard< dim >::copy_local_rhs_to_global_rhs(), and fluid_dynamics.
attach_solution_to_output()
template<int dim> void CahnHilliard< dim >::attach_solution_to_output (DataOut< dim > & data_out) override virtual
Attach the solution vector to the DataOut provided. This function enable the auxiliary physics to output their solution via the core solver.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 272 of file cahn_hilliard.cc.
calculate_barycenter()
template<int dim> template<typename VectorType > template std::pair< Tensor< 1, 3 >, Tensor< 1, 3 > > CahnHilliard< dim >::calculate_barycenter< TrilinosWrappers::MPI::BlockVector > (const TrilinosWrappers::MPI::Vector & solution, const VectorType & current_solution_fd) private
Calculates the barycenter of fluid 1 and its velocity.
Parameters
solution Cahn-Hilliard solution
current_solution_fd Fluid dynamics solution
Definition at line 1111 of file cahn_hilliard.cc.
References fluid_dynamics.
calculate_L2_error()
template<int dim> std::pair< double, double > CahnHilliard< dim >::calculate_L2_error
Calculates the L2 error of the solution.
Definition at line 293 of file cahn_hilliard.cc.
calculate_phase_statistics()
template<int dim> void CahnHilliard< dim >::calculate_phase_statistics private
Calculate phase order parameter integral for monitoring purposes.
Definition at line 367 of file cahn_hilliard.cc.
References announce_string(), and Parameters::verbose.
compute_kelly()
template<int dim> void CahnHilliard< dim >::compute_kelly (const std::pair< const Parameters::MeshAdaptation::Variable, Parameters::MultipleAdaptationParameters > & ivar, dealii::Vector< float > & estimated_error_per_cell) override virtual
Compute the Kelly error estimator for mesh refinement. NB : not implemented for the cahn_hilliard equations for now.
Parameters
ivar The current element of the map simulation_parameters.mesh_adaptation.variables
estimated_error_per_cell The deal.II vector of estimated_error_per_cell
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 711 of file cahn_hilliard.cc.
References Parameters::MeshAdaptation::phase_cahn_hilliard.
copy_local_matrix_to_global_matrix()
template<int dim> void CahnHilliard< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell information to global matrix.
Definition at line 159 of file cahn_hilliard.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void CahnHilliard< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell rhs information to global rhs.
Definition at line 258 of file cahn_hilliard.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_rhs.
finish_simulation()
template<int dim> void CahnHilliard< dim >::finish_simulation override virtual
Carry out the operations required to finish a simulation correctly.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 447 of file cahn_hilliard.cc.
References Parameters::SimulationControl::steady, and Parameters::verbose.
get_dof_handler()
template<int dim> const DoFHandler<dim>& CahnHilliard< dim >::get_dof_handler () inline override virtual
Returns the dof_handler of the Cahn-Hilliard physics.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 234 of file cahn_hilliard.h.
References CahnHilliard< dim >::dof_handler.
get_evaluation_point()
template<int dim> TrilinosWrappers::MPI::Vector& CahnHilliard< dim >::get_evaluation_point () inline override virtual
Getter methods to get the private attributes for the physic currently solved NB : dof_handler and present_solution are passed to the multiphysics interface at the end of the setup_dofs method.
Implements PhysicsSolver< VectorType >.
Definition at line 278 of file cahn_hilliard.h.
References CahnHilliard< dim >::evaluation_point.
get_local_evaluation_point()
template<int dim> TrilinosWrappers::MPI::Vector& CahnHilliard< dim >::get_local_evaluation_point () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 283 of file cahn_hilliard.h.
References CahnHilliard< dim >::local_evaluation_point.
get_newton_update()
template<int dim> TrilinosWrappers::MPI::Vector& CahnHilliard< dim >::get_newton_update () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 288 of file cahn_hilliard.h.
References CahnHilliard< dim >::newton_update.
get_nonzero_constraints()
template<int dim> AffineConstraints<double>& CahnHilliard< dim >::get_nonzero_constraints () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 303 of file cahn_hilliard.h.
References CahnHilliard< dim >::nonzero_constraints.
get_present_solution()
template<int dim> TrilinosWrappers::MPI::Vector& CahnHilliard< dim >::get_present_solution () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 293 of file cahn_hilliard.h.
References CahnHilliard< dim >::present_solution.
get_system_rhs()
template<int dim> TrilinosWrappers::MPI::Vector& CahnHilliard< dim >::get_system_rhs () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 298 of file cahn_hilliard.h.
References CahnHilliard< dim >::system_rhs.
percolate_time_vectors()
template<int dim> void CahnHilliard< dim >::percolate_time_vectors override virtual
Rearrange vector solution correctly for transient simulations.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 477 of file cahn_hilliard.cc.
post_mesh_adaptation()
template<int dim> void CahnHilliard< dim >::post_mesh_adaptation override virtual
post_mesh_adaption Interpolates the auxiliary physics variables to the new mesh
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 682 of file cahn_hilliard.cc.
postprocess()
template<int dim> void CahnHilliard< dim >::postprocess (bool first_iteration) override virtual
Postprocess the auxiliary physics results. Post-processing this case implies the calculation of all derived quantities using the solution vector of the physics. It does not concern the output of the solution using the DataOutObject, which is accomplished through the attach_solution_to_output function.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 488 of file cahn_hilliard.cc.
References announce_string(), calculate_L2_error(), fluid_dynamics, Parameters::Timer::iteration, make_table_scalars_tensors(), and Parameters::verbose.
pre_mesh_adaptation()
template<int dim> void CahnHilliard< dim >::pre_mesh_adaptation override virtual
pre_mesh_adaption Prepares the auxiliary physics variables for a mesh refinement/coarsening
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 669 of file cahn_hilliard.cc.
read_checkpoint()
template<int dim> void CahnHilliard< dim >::read_checkpoint override virtual
Allows Cahn-Hilliard physics to set-up solution vector from checkpoint file;.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 781 of file cahn_hilliard.cc.
References deserialize_table().
set_initial_conditions()
template<int dim> void CahnHilliard< dim >::set_initial_conditions override virtual
Sets-up the initial conditions associated with the physics. Generally, physics only support imposing nodal values, but some physics additionally support the use of L2 projection or steady-state solutions.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 1002 of file cahn_hilliard.cc.
setup_assemblers()
template<int dim> void CahnHilliard< dim >::setup_assemblers private virtual
sets up the vector of assembler functions
Definition at line 31 of file cahn_hilliard.cc.
References is_bdf().
setup_dofs()
template<int dim> void CahnHilliard< dim >::setup_dofs override virtual
Sets-up the DofHandler and the degree of freedom associated with the physics.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 829 of file cahn_hilliard.cc.
References cahn_hilliard.
solve_linear_system()
template<int dim> void CahnHilliard< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) override virtual
Call for the solution of the linear system of equation using a strategy appropriate to the auxiliary physics.
Parameters
initial_step Provides the linear solver with indication if this solution is the first one for the system of equation or not
renewed_matrix Indicates to the linear solve if the system matrix has been recalculated or not
Implements PhysicsSolver< VectorType >.
Definition at line 1030 of file cahn_hilliard.cc.
References cahn_hilliard, and Parameters::quiet.
update_boundary_conditions()
template<int dim> void CahnHilliard< dim >::update_boundary_conditions override virtual
Update non zero constraints if the boundary is time-dependent.
Reimplemented from AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 952 of file cahn_hilliard.cc.
References BoundaryConditions::cahn_hilliard_dirichlet_phase_order.
write_checkpoint()
template<int dim> void CahnHilliard< dim >::write_checkpoint override virtual
Prepares Cahn-Hilliard to write checkpoint.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 747 of file cahn_hilliard.cc.
References serialize_table().
write_phase_statistics()
template<int dim> void CahnHilliard< dim >::write_phase_statistics private
Writes the phase integral to an output file.
Definition at line 430 of file cahn_hilliard.cc.
Member Data Documentation
assemblers
template<int dim> std::vector<std::shared_ptr<CahnHilliardAssemblerBase<dim> > > CahnHilliard< dim >::assemblers private
Definition at line 460 of file cahn_hilliard.h.
barycenter_table
template<int dim> TableHandler CahnHilliard< dim >::barycenter_table private
Definition at line 463 of file cahn_hilliard.h.
cell_quadrature
template<int dim> std::shared_ptr<Quadrature<dim> > CahnHilliard< dim >::cell_quadrature private
Definition at line 428 of file cahn_hilliard.h.
computing_timer
template<int dim> TimerOutput CahnHilliard< dim >::computing_timer private
Definition at line 414 of file cahn_hilliard.h.
dof_handler
template<int dim> DoFHandler<dim> CahnHilliard< dim >::dof_handler private
Definition at line 422 of file cahn_hilliard.h.
error_table
template<int dim> ConvergenceTable CahnHilliard< dim >::error_table private
Definition at line 432 of file cahn_hilliard.h.
evaluation_point
template<int dim> TrilinosWrappers::MPI::Vector CahnHilliard< dim >::evaluation_point private
Definition at line 438 of file cahn_hilliard.h.
face_quadrature
template<int dim> std::shared_ptr<Quadrature<dim - 1> > CahnHilliard< dim >::face_quadrature private
Definition at line 429 of file cahn_hilliard.h.
fe
template<int dim> std::shared_ptr<FESystem<dim> > CahnHilliard< dim >::fe private
Definition at line 425 of file cahn_hilliard.h.
local_evaluation_point
template<int dim> TrilinosWrappers::MPI::Vector CahnHilliard< dim >::local_evaluation_point private
Definition at line 439 of file cahn_hilliard.h.
locally_owned_dofs
template<int dim> IndexSet CahnHilliard< dim >::locally_owned_dofs private
Definition at line 435 of file cahn_hilliard.h.
locally_relevant_dofs
template<int dim> IndexSet CahnHilliard< dim >::locally_relevant_dofs private
Definition at line 436 of file cahn_hilliard.h.
mapping
template<int dim> std::shared_ptr<Mapping<dim> > CahnHilliard< dim >::mapping private
Definition at line 427 of file cahn_hilliard.h.
multiphysics
template<int dim> MultiphysicsInterface<dim>* CahnHilliard< dim >::multiphysics private
Definition at line 412 of file cahn_hilliard.h.
newton_update
template<int dim> TrilinosWrappers::MPI::Vector CahnHilliard< dim >::newton_update private
Definition at line 440 of file cahn_hilliard.h.
nonzero_constraints
template<int dim> AffineConstraints<double> CahnHilliard< dim >::nonzero_constraints private
Definition at line 443 of file cahn_hilliard.h.
present_solution
template<int dim> TrilinosWrappers::MPI::Vector CahnHilliard< dim >::present_solution private
Definition at line 441 of file cahn_hilliard.h.
previous_solutions
template<int dim> std::vector<TrilinosWrappers::MPI::Vector> CahnHilliard< dim >::previous_solutions private
Definition at line 449 of file cahn_hilliard.h.
previous_solutions_transfer
template<int dim> std::vector< parallel::distributed::SolutionTransfer<dim, TrilinosWrappers::MPI::Vector> > CahnHilliard< dim >::previous_solutions_transfer private
Definition at line 457 of file cahn_hilliard.h.
simulation_control
template<int dim> std::shared_ptr<SimulationControl> CahnHilliard< dim >::simulation_control private
Definition at line 421 of file cahn_hilliard.h.
simulation_parameters
template<int dim> const SimulationParameters<dim>& CahnHilliard< dim >::simulation_parameters private
Definition at line 416 of file cahn_hilliard.h.
solution_transfer
template<int dim> std::shared_ptr< parallel::distributed::SolutionTransfer<dim, TrilinosWrappers::MPI::Vector> > CahnHilliard< dim >::solution_transfer private
Definition at line 454 of file cahn_hilliard.h.
statistics_table
template<int dim> TableHandler CahnHilliard< dim >::statistics_table private
Definition at line 466 of file cahn_hilliard.h.
system_matrix
template<int dim> TrilinosWrappers::SparseMatrix CahnHilliard< dim >::system_matrix private
Definition at line 445 of file cahn_hilliard.h.
system_rhs
template<int dim> TrilinosWrappers::MPI::Vector CahnHilliard< dim >::system_rhs private
Definition at line 442 of file cahn_hilliard.h.
triangulation
template<int dim> std::shared_ptr<parallel::DistributedTriangulationBase<dim> > CahnHilliard< dim >::triangulation private
Definition at line 420 of file cahn_hilliard.h.
zero_constraints
template<int dim> AffineConstraints<double> CahnHilliard< dim >::zero_constraints private
Definition at line 444 of file cahn_hilliard.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/cahn_hilliard.h
/home/runner/work/lethe/lethe/source/solvers/cahn_hilliard.cc