Developer documentation for the Lethe open-source library: /home/runner/work/lethe/lethe/include/core/bdf.h File Reference
bdf.h File Reference
#include <core/parameters.h>
#include <deal.II/lac/vector.h>
#include <vector>
Functions
Vector< double > bdf_coefficients (unsigned int order, const std::vector< double > time_steps)
Calculate the coefficients required for BDF integration of order n. The coefficients are determined through a recursion algorithm. The algorithm is taken from : Hay, Alexander, et al. "hp-Adaptive time integration based on the BDF for viscous flows." Journal of Computational Physics 291 (2015): 151-176.
Vector< double > bdf_coefficients (const Parameters::SimulationControl::TimeSteppingMethod method, const std::vector< double > time_steps)
Calculate the coefficients required for BDF integration of order n. The coefficients are determined through a recursion algorithm. The algorithm is taken from : Hay, Alexander, et al. "hp-Adaptive time integration based on the BDF for viscous flows." Journal of Computational Physics 291 (2015): 151-176.
Vector< double > delta (const unsigned int order, const unsigned int n, const unsigned int j, const Vector< double > times)
Recursion function to calculate the bdf coefficient.
unsigned int maximum_number_of_previous_solutions ()
Returns the maximum number of previous time steps supposed by the BDF schemes implemented in Lethe. At the moment this is hardcoded to 3, but eventually this could be made larger or smaller depending on the methods used.
unsigned int number_of_previous_solutions (Parameters::SimulationControl::TimeSteppingMethod method)
Returns the number of previous time steps for a BDF Scheme.
template<typename DataType >
void bdf_extrapolate (const std::vector< double > &time_vector, const std::vector< std::vector< DataType >> &solution_vector, const unsigned int number_of_previous_solutions, std::vector< DataType > &extrapolated_solution)
Extrapolates vector of solution to time_vector[0] using previous solution times and previous solution.
Function Documentation
bdf_coefficients() [1/2]
Vector<double> bdf_coefficients (const Parameters::SimulationControl::TimeSteppingMethod method, const std::vector< double > time_steps)
Calculate the coefficients required for BDF integration of order n. The coefficients are determined through a recursion algorithm. The algorithm is taken from : Hay, Alexander, et al. "hp-Adaptive time integration based on the BDF for viscous flows." Journal of Computational Physics 291 (2015): 151-176.
Parameters
method The time stepping method
time_steps a vector containing all the time steps. The time steps should be in reverse order. For example, if the method is a BDF2, it uses three values for the time : (t) (t-dt_1) and (t-dt_2). Thus the time step vector should contain dt_1 and dt_2.
Definition at line 55 of file bdf.cc.
References Parameters::SimulationControl::bdf1, Parameters::SimulationControl::bdf2, Parameters::SimulationControl::bdf3, bdf_coefficients(), and Parameters::SimulationControl::steady_bdf.
bdf_coefficients() [2/2]
Vector<double> bdf_coefficients (unsigned int order, const std::vector< double > time_steps)
Calculate the coefficients required for BDF integration of order n. The coefficients are determined through a recursion algorithm. The algorithm is taken from : Hay, Alexander, et al. "hp-Adaptive time integration based on the BDF for viscous flows." Journal of Computational Physics 291 (2015): 151-176.
Parameters
order The order of the BDF method. The BDF method of order n requires n+1 arrays
time_steps a vector containing all the time steps. The time steps should be in reverse order. For example, if the method is a BDF2, it uses three values for the time : (t) (t-dt_1) and (t-dt_2). Thus the time step vector should contain dt_1 and dt_2.
Definition at line 23 of file bdf.cc.
References delta().
bdf_extrapolate()
template<typename DataType > void bdf_extrapolate (const std::vector< double > & time_vector, const std::vector< std::vector< DataType >> & solution_vector, const unsigned int number_of_previous_solutions, std::vector< DataType > & extrapolated_solution) inline
Extrapolates vector of solution to time_vector[0] using previous solution times and previous solution.
Template Parameters
The type of the variable being extrapolated (e.g. double, Tensor<1,dim>)
Parameters
time_vector The vector of times. The solution will be extrapolated to time 0. It should be of size number_of_previous_solutions+1
solution_vector The vector of solutions. The solution will be extrapolated to index 0. It should be at least of size number_of_previous_solutions
number_of_previous_solutions The number of previous solutions to use to extrapolate
extrapolated_solution The vector of extrapolated solutions
Definition at line 132 of file bdf.h.
References number_of_previous_solutions().
delta()
Vector<double> delta (const unsigned int order, const unsigned int n, const unsigned int j, const Vector< double > times)
Recursion function to calculate the bdf coefficient.
Parameters
order Order of the bdf method
n Integer required for the recursive function calculation
j Integer required for the recursive function calculation
times Vector of the times corresponding to the various iteration in reverse order. For example in a BDF2 method, three values of the time must be in the array : t, t-dt_1 and t-dt_2.
Definition at line 76 of file bdf.cc.
References delta().
maximum_number_of_previous_solutions()
unsigned int maximum_number_of_previous_solutions () inline
Returns the maximum number of previous time steps supposed by the BDF schemes implemented in Lethe. At the moment this is hardcoded to 3, but eventually this could be made larger or smaller depending on the methods used.
Definition at line 96 of file bdf.h.
number_of_previous_solutions()
unsigned int number_of_previous_solutions (Parameters::SimulationControl::TimeSteppingMethod method) inline
Returns the number of previous time steps for a BDF Scheme.
Definition at line 106 of file bdf.h.
References Parameters::SimulationControl::bdf1, Parameters::SimulationControl::bdf2, Parameters::SimulationControl::bdf3, and Parameters::SimulationControl::steady_bdf.