Developer documentation for the Lethe open-source library: MFNavierStokesSolver< dim > Class Template Reference
MFNavierStokesSolver< dim > Class Template Reference
A solver class for the Navier-Stokes equation that uses the matrix free approach.
#include <mf_navier_stokes.h>
Public Member Functions
MFNavierStokesSolver (SimulationParameters< dim > &nsparam)
Construct a new MFNavierStokesSolver object.
~MFNavierStokesSolver ()
Destroy the MFNavierStokesSolver object.
virtual void solve ()
Solves the Navier-Stokes problem.
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
solve_non_linear_system Solves the non linear system of equations
virtual void apply_constraints ()
Applies constraints to a local_evaluation_point.
virtual double get_current_residual ()
Default way to evaluate the residual for the nonlinear solver. Some application may use more complex evaluation of the residual and override this method.
Protected Member Functions
virtual void setup_dofs_fd () override
Setup the DoFs, system operator and solution vectors.
void update_boundary_conditions ()
Update non zero constraints if the boundary is time dependent.
virtual void set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart=false) override
Set the initial conditions for the solver.
virtual void assemble_system_matrix () override
Assemble the matrix associated with the solver. This function is only required for compilation and it is not used for matrix free solvers.
virtual void assemble_system_rhs () override
Assemble the system rhs associated with the solver.
virtual void update_multiphysics_time_average_solution () override
Update the average velocity field solution in the multiphyscics interface.
void calculate_time_derivative_previous_solutions ()
Calculate and store time derivatives of previous solutions according to time-stepping scheme to use them in the operator.
void define_non_zero_constraints ()
Define the non-zero constraints used to solve the problem.
void define_zero_constraints ()
Define the zero constraints used to solve the problem.
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
Call for the assembly of the linear system of equations.
Protected Member Functions inherited from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual LinearAlgebra::distributed::Vector< double > & get_evaluation_point () override
Getter methods to get the private attributes for the physic currently solved.
virtual LinearAlgebra::distributed::Vector< double > & get_local_evaluation_point () override
virtual LinearAlgebra::distributed::Vector< double > & get_newton_update () override
virtual LinearAlgebra::distributed::Vector< double > & get_present_solution () override
virtual LinearAlgebra::distributed::Vector< double > & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
void finish_simulation ()
finish_simulation Finish the simulation by calling all the post-processing elements that are required
virtual void postprocess (bool first_iteration)
postprocess Post-process simulation after an iteration
virtual void setup_dofs ()
setup_dofs
virtual void set_initial_condition (Parameters::InitialConditionType initial_condition_type, bool restart=false)
set_initial_conditions
virtual void finish_time_step ()
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
virtual void percolate_time_vectors_fd ()
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
void finish_simulation_fd ()
finish_simulation Finishes the simulation for fluid dynamics by calling the post-processing elements that are required
virtual void postprocess_fd (bool first_iteration)
postprocess Post-process fluid dynamics after an iteration
void postprocessing_forces (const LinearAlgebra::distributed::Vector< double > &evaluation_point)
postprocessing_forces Post-processing function Outputs the forces acting on each boundary condition
void postprocessing_torques (const LinearAlgebra::distributed::Vector< double > &evaluation_point)
postprocessing_torques Post-processing function Outputs the torque acting on each boundary condition
virtual void dynamic_flow_control ()
dynamic_flow_control If set to enable, dynamic_flow_control allows to control the flow by executing space-average velocity and beta coefficient force calculation at each time step.
virtual void iterate ()
iterate Do a regular CFD iteration
void box_refine_mesh ()
Allow the initial refinement of all cells of the principal mesh that are partially contained in one of the cells of the box refinement mesh given in the parameter.
virtual void refine_mesh ()
Allow the refinement of the mesh according to one of the 2 methods proposed.
void refine_mesh_kelly ()
Allow the refinement of the mesh based on the Kelly error estimator. See : https://www.dealii.org/current/doxygen/deal.II/classKellyErrorEstimator.html for more information on the Kelly error estimator.
void refine_mesh_uniform ()
Allow the uniform refinement of all the mesh.
virtual void read_checkpoint ()
read_checkpoint
void set_nodal_values ()
set_nodal_values Set the nodal values of velocity and pressure
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
Check if a specifique boundary condition exist.
void establish_solid_domain (const bool non_zero_constraints)
Turns regions of the mesh where the material_id=1 to a solid block by injecting it into the constraints This is achieved by imposing $\mathbf{u}=0$ within the cells which have a material_id=1. In addition, solid cells which are not connected to the fluid by any means also get a pressure dirichlet boundary condition which fixes the pressure to 0. This ensures that the linear system is well-posed. Right now, this routine only supports the usage of 1 solid domain, but eventually it could be extended to more than one. By default, the fluid domain is assumed to have a material_id=0 and the rest of the domains have a material_id>0.
virtual void write_checkpoint ()
write_checkpoint
void write_output_results (const LinearAlgebra::distributed::Vector< double > &solution)
write_output_results Post-processing as parallel VTU files
virtual void output_field_hook (DataOut< dim > &)
output_field_hook This function is to be redefined in specialized classes to adapt the output to each solver.
void write_output_forces ()
write_output_forces Writes the forces per boundary condition to a text file output
void write_output_torques ()
write_output_torques Writes the torques per boundary condition to a text file output
void rescale_pressure_dofs_in_newton_update ()
rescale_pressure_dofs_in_newton_update This function is used to rescale pressure DOFs in the newton correction
LinearAlgebra::distributed::Vector< double > init_temporary_vector ()
init_temporary_vector This function initializes correctly a temporary vector depending on the vector type
Protected Attributes
std::shared_ptr< NavierStokesOperatorBase< dim, double > > system_operator
std::shared_ptr< PreconditionMG< dim, VectorType, LSTransferType > > ls_multigrid_preconditioner
std::shared_ptr< PreconditionMG< dim, VectorType, GCTransferType > > gc_multigrid_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
VectorType time_derivative_previous_solutions
TimerOutput mg_computing_timer
Protected Attributes inherited from NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
LinearAlgebra::distributed::Vector< double > evaluation_point
LinearAlgebra::distributed::Vector< double > local_evaluation_point
LinearAlgebra::distributed::Vector< double > newton_update
LinearAlgebra::distributed::Vector< double > present_solution
LinearAlgebra::distributed::Vector< double > system_rhs
std::vector< LinearAlgebra::distributed::Vector< double > > previous_solutions
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, LinearAlgebra::distributed::Vector< double >, IndexSet > > average_velocities
LinearAlgebra::distributed::Vector< double > average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::vector< Tensor< 1, dim > > > forces_on_boundaries
std::vector< Tensor< 1, 3 > > torques_on_boundaries
std::vector< TableHandler > forces_tables
std::vector< TableHandler > torques_tables
Private Types
using VectorType = LinearAlgebra::distributed::Vector< double >
using LSTransferType = MGTransferMatrixFree< dim, double >
using GCTransferType = MGTransferGlobalCoarsening< dim, VectorType >
Private Member Functions
void assemble_L2_projection ()
Assembles an L2_projection matrix for the velocity and the pressure. This L2 projection matrix can be used to set the initial condition for the Navier-Stokes problem.
void solve_system_GMRES (const bool initial_step, const double absolute_residual, const double relative_residual)
GMRES solver with preconditioning.
void solve_with_LSMG (SolverGMRES< VectorType > &solver)
Set-up local smoothing MG preconditioner.
void solve_with_GCMG (SolverGMRES< VectorType > &solver)
Set-up global coarsening MG preconditioner.
void solve_with_ILU (SolverGMRES< VectorType > &solver)
Set-up ILU preconditioner.
double estimate_omega (std::shared_ptr< NavierStokesOperatorBase< dim, double >> &mg_operator, const unsigned int &level, const VectorType &diagonal)
Estimate the eigenvalues to obtain a relaxation parameter for the MG smoother.
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class MFNavierStokesSolver< dim >
A solver class for the Navier-Stokes equation that uses the matrix free approach.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved.
Definition at line 42 of file mf_navier_stokes.h.
Member Typedef Documentation
GCTransferType
template<int dim> using MFNavierStokesSolver< dim >::GCTransferType = MGTransferGlobalCoarsening<dim, VectorType> private
Definition at line 49 of file mf_navier_stokes.h.
LSTransferType
template<int dim> using MFNavierStokesSolver< dim >::LSTransferType = MGTransferMatrixFree<dim, double> private
Definition at line 48 of file mf_navier_stokes.h.
VectorType
template<int dim> using MFNavierStokesSolver< dim >::VectorType = LinearAlgebra::distributed::Vector<double> private
Definition at line 47 of file mf_navier_stokes.h.
Constructor & Destructor Documentation
MFNavierStokesSolver()
template<int dim> MFNavierStokesSolver< dim >::MFNavierStokesSolver (SimulationParameters< dim > & nsparam)
Construct a new MFNavierStokesSolver object.
Parameters
nsparam Relevant parameters for the solver.
Definition at line 48 of file mf_navier_stokes.cc.
References NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::fe, SimulationParameters< dim >::fem_parameters, is_bdf(), Parameters::FEM::pressure_order, Parameters::Stabilization::pspg_supg, NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >::simulation_control, Parameters::Stabilization::stabilization, SimulationParameters< dim >::stabilization, MFNavierStokesSolver< dim >::system_operator, Parameters::Stabilization::use_default_stabilization, and Parameters::FEM::velocity_order.
~MFNavierStokesSolver()
template<int dim> MFNavierStokesSolver< dim >::~MFNavierStokesSolver
Destroy the MFNavierStokesSolver object.
Definition at line 81 of file mf_navier_stokes.cc.
Member Function Documentation
assemble_L2_projection()
template<int dim> void MFNavierStokesSolver< dim >::assemble_L2_projection private
Assembles an L2_projection matrix for the velocity and the pressure. This L2 projection matrix can be used to set the initial condition for the Navier-Stokes problem.
Definition at line 1681 of file mf_navier_stokes.cc.
assemble_system_matrix()
template<int dim> void MFNavierStokesSolver< dim >::assemble_system_matrix override protected virtual
Assemble the matrix associated with the solver. This function is only required for compilation and it is not used for matrix free solvers.
Implements PhysicsSolver< VectorType >.
Definition at line 405 of file mf_navier_stokes.cc.
assemble_system_rhs()
template<int dim> void MFNavierStokesSolver< dim >::assemble_system_rhs override protected virtual
Assemble the system rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 413 of file mf_navier_stokes.cc.
calculate_time_derivative_previous_solutions()
template<int dim> void MFNavierStokesSolver< dim >::calculate_time_derivative_previous_solutions protected
Calculate and store time derivatives of previous solutions according to time-stepping scheme to use them in the operator.
Definition at line 437 of file mf_navier_stokes.cc.
References bdf_coefficients(), and number_of_previous_solutions().
define_non_zero_constraints()
template<int dim> void MFNavierStokesSolver< dim >::define_non_zero_constraints protected
Define the non-zero constraints used to solve the problem.
Definition at line 1494 of file mf_navier_stokes.cc.
References BoundaryConditions::function, BoundaryConditions::noslip, BoundaryConditions::periodic, pressure, and BoundaryConditions::slip.
define_zero_constraints()
template<int dim> void MFNavierStokesSolver< dim >::define_zero_constraints protected
Define the zero constraints used to solve the problem.
Definition at line 1582 of file mf_navier_stokes.cc.
References BoundaryConditions::function_weak, BoundaryConditions::outlet, BoundaryConditions::partial_slip, BoundaryConditions::periodic, BoundaryConditions::pressure, pressure, and BoundaryConditions::slip.
estimate_omega()
template<int dim> double MFNavierStokesSolver< dim >::estimate_omega (std::shared_ptr< NavierStokesOperatorBase< dim, double >> & mg_operator, const unsigned int & level, const VectorType & diagonal) private
Estimate the eigenvalues to obtain a relaxation parameter for the MG smoother.
Parameters
operator Operator for which the estimation needs to be done
level Corresponding MG level
diagonal Pre-computed diagonal of level operator
Returns
double Omega relaxation parameter
Definition at line 455 of file mf_navier_stokes.cc.
References fluid_dynamics, and Parameters::quiet.
set_initial_condition_fd()
template<int dim> void MFNavierStokesSolver< dim >::set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart = false) override protected virtual
Set the initial conditions for the solver.
If the simulation is restarted from a checkpoint, the initial solution setting is bypassed and the checkpoint is instead read.
Parameters
initial_condition_type The type of initial condition to be set.
restart A boolean that indicates if the simulation is being restarted. If set to true, the initial conditions are never set, but are instead overriden by the read_checkpoint functionality.
Implements NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 276 of file mf_navier_stokes.cc.
References Parameters::nodal, Parameters::ramp, read_checkpoint(), Parameters::SimulationControl::steady, and Parameters::viscous.
setup_dofs_fd()
template<int dim> void MFNavierStokesSolver< dim >::setup_dofs_fd override protected virtual
Setup the DoFs, system operator and solution vectors.
Implements NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 156 of file mf_navier_stokes.cc.
References fluid_dynamics, and Parameters::LinearSolver::lsmg.
solve()
template<int dim> void MFNavierStokesSolver< dim >::solve virtual
Solves the Navier-Stokes problem.
This functions solves the problem defined by the Navier-Stokes parameter file by iterating through time or through the mesh refinements.
Definition at line 88 of file mf_navier_stokes.cc.
References announce_string(), Parameters::extra_verbose, fluid_dynamics, is_bdf(), Parameters::MeshAdaptation::none, read_mesh_and_manifolds(), and NavierStokesBase< dim, VectorType, DofsType >::refine_mesh().
solve_linear_system()
template<int dim> void MFNavierStokesSolver< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) override protected virtual
Call for the assembly of the linear system of equations.
Parameters
initial_step Indicates if this is the first solution of the linear system. If this is the case, the non_zero version of the constraints are used for the Dirichlet boundary conditions.
renewed_matrix Indicates if the matrix has been reassembled, and thus the preconditioner needs to be reassmbled.
TODO: the renewed_matrix parameter needs to be deprecated.
Implements PhysicsSolver< VectorType >.
Definition at line 1661 of file mf_navier_stokes.cc.
References fluid_dynamics, and Parameters::LinearSolver::gmres.
solve_system_GMRES()
template<int dim> void MFNavierStokesSolver< dim >::solve_system_GMRES (const bool initial_step, const double absolute_residual, const double relative_residual) private
GMRES solver with preconditioning.
Definition at line 1688 of file mf_navier_stokes.cc.
References fluid_dynamics, Parameters::LinearSolver::gcmg, Parameters::LinearSolver::ilu, Parameters::LinearSolver::lsmg, and Parameters::quiet.
solve_with_GCMG()
template<int dim> void MFNavierStokesSolver< dim >::solve_with_GCMG (SolverGMRES< VectorType > & solver) private
Set-up global coarsening MG preconditioner.
Definition at line 991 of file mf_navier_stokes.cc.
References fluid_dynamics.
solve_with_ILU()
template<int dim> void MFNavierStokesSolver< dim >::solve_with_ILU (SolverGMRES< VectorType > & solver) private
Set-up ILU preconditioner.
Definition at line 1459 of file mf_navier_stokes.cc.
References fluid_dynamics.
solve_with_LSMG()
template<int dim> void MFNavierStokesSolver< dim >::solve_with_LSMG (SolverGMRES< VectorType > & solver) private
Set-up local smoothing MG preconditioner.
Definition at line 523 of file mf_navier_stokes.cc.
References Parameters::LinearSolver::amg, fluid_dynamics, BoundaryConditions::function_weak, Parameters::LinearSolver::ilu, is_bdf(), BoundaryConditions::outlet, BoundaryConditions::partial_slip, BoundaryConditions::periodic, BoundaryConditions::pressure, pressure, Parameters::Stabilization::pspg_supg, Parameters::quiet, NavierStokesOperatorBase< dim, number >::reinit(), and BoundaryConditions::slip.
update_boundary_conditions()
template<int dim> void MFNavierStokesSolver< dim >::update_boundary_conditions protected
Update non zero constraints if the boundary is time dependent.
Definition at line 247 of file mf_navier_stokes.cc.
update_multiphysics_time_average_solution()
template<int dim> void MFNavierStokesSolver< dim >::update_multiphysics_time_average_solution override protected virtual
Update the average velocity field solution in the multiphyscics interface.
Implements NavierStokesBase< dim, LinearAlgebra::distributed::Vector< double >, IndexSet >.
Definition at line 430 of file mf_navier_stokes.cc.
Member Data Documentation
gc_multigrid_preconditioner
template<int dim> std::shared_ptr<PreconditionMG<dim, VectorType, GCTransferType> > MFNavierStokesSolver< dim >::gc_multigrid_preconditioner protected
Definition at line 220 of file mf_navier_stokes.h.
ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> MFNavierStokesSolver< dim >::ilu_preconditioner protected
Definition at line 221 of file mf_navier_stokes.h.
ls_multigrid_preconditioner
template<int dim> std::shared_ptr<PreconditionMG<dim, VectorType, LSTransferType> > MFNavierStokesSolver< dim >::ls_multigrid_preconditioner protected
Definition at line 218 of file mf_navier_stokes.h.
mg_computing_timer
template<int dim> TimerOutput MFNavierStokesSolver< dim >::mg_computing_timer protected
Definition at line 226 of file mf_navier_stokes.h.
system_operator
template<int dim> std::shared_ptr<NavierStokesOperatorBase<dim, double> > MFNavierStokesSolver< dim >::system_operator protected
Definition at line 215 of file mf_navier_stokes.h.
time_derivative_previous_solutions
template<int dim> VectorType MFNavierStokesSolver< dim >::time_derivative_previous_solutions protected
Definition at line 224 of file mf_navier_stokes.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/mf_navier_stokes.h
/home/runner/work/lethe/lethe/source/solvers/mf_navier_stokes.cc