Developer documentation for the Lethe open-source library: PlaneInsertion< dim > Class Template Reference
PlaneInsertion< dim > Class Template Reference
#include <plane_insertion.h>
Public Member Functions
PlaneInsertion (const DEMSolverParameters< dim > &dem_parameters, const parallel::distributed::Triangulation< dim > &triangulation, const std::vector< std::shared_ptr< Distribution >> &distribution_object_container)
virtual void insert (Particles::ParticleHandler< dim > &particle_handler, const parallel::distributed::Triangulation< dim > &triangulation, const DEMSolverParameters< dim > &dem_parameters) override
virtual void serialize (boost::archive::text_oarchive &ar, const unsigned int) override
Serialize the plane insertion object to an output archive.
virtual void deserialize (boost::archive::text_iarchive &ar, const unsigned int) override
Deserialize an input archive to the plane insertion object.
Public Member Functions inherited from Insertion< dim >
Insertion (const std::vector< std::shared_ptr< Distribution >> &distribution_object_container)
Carries out the insertion of particles. This is the base class of volume_insertion, plane_insertion and list_insertion classes.
Private Member Functions
void find_inplane_cells (const parallel::distributed::Triangulation< dim > &triangulation, Point< 3 > plane_point, Tensor< 1, 3 > plane_normal_vector)
Store the cells that are cut by the plane.
void find_centers_of_inplane_cells ()
Store the location of the centers of all the cells that are in the plane.
Private Attributes
std::set< typename Triangulation< dim >::active_cell_iterator > plane_cells_for_insertion
double maximum_range_for_randomness
int particles_of_each_type_remaining
unsigned int current_inserting_particle_type
std::unordered_map< unsigned int, Point< dim > > cells_centers
bool mark_for_update
boost::signals2::connection change_to_triangulation
Additional Inherited Members
Protected Member Functions inherited from Insertion< dim >
void print_insertion_info (const unsigned int &inserted_this_step, const unsigned int &remained_particles, const unsigned int &particle_type, const ConditionalOStream &pcout)
Print information about the particles that have been inserted during an insertion time step.
void assign_particle_properties (const DEMSolverParameters< dim > &dem_parameters, const unsigned int &inserted_this_step_this_proc, const unsigned int &current_inserting_particle_type, std::vector< std::vector< double >> &particle_properties)
Carries out assigning the properties of inserted particles.
void calculate_insertion_domain_maximum_particle_number (const DEMSolverParameters< dim > &dem_parameters, const ConditionalOStream &pcout)
Carries out finding the maximum number of inserted particles based on the insertion box size. If the requested number of particles for insertion in each insertion step is larger than this maximum, it is limited to this value and a warning is printed.
Protected Attributes inherited from Insertion< dim >
unsigned int inserted_this_step
std::vector< int > number_of_particles_directions
std::vector< double > axis_min
std::vector< double > axis_max
double maximum_diameter
unsigned int inserted_this_step_this_proc
std::vector< std::shared_ptr< Distribution > > distributions_objects
Detailed Description
template<int dim>
class PlaneInsertion< dim >
Insertion of particles using cells cut by a plane
Note
Particle insertion using cells cut by a plane. Locally owned cells that are cut by the plane are flagged. From those flagged cells, we insert a particle at their centroids if they are individually empty (contain no particle). This way, no significant overlap is occurring on the insertion of new particle which can occur with other insertion method.
Definition at line 43 of file plane_insertion.h.
Constructor & Destructor Documentation
PlaneInsertion()
template<int dim> PlaneInsertion< dim >::PlaneInsertion (const DEMSolverParameters< dim > & dem_parameters, const parallel::distributed::Triangulation< dim > & triangulation, const std::vector< std::shared_ptr< Distribution >> & distribution_object_container)
The plane insertion class insert particles using a plane define by a point an a normal vector. This method of insertion can be useful when dealing with a domain close to be fully filled with particle. In this situation, other insertion method have a high risk to create a big overlap between particles on insertion. The plane insertion method mitigate this risk by insertion at the center of empty cells.
Parameters
dem_parameters DEM parameters declared in the .prm file
triangulation Triangulation object used in the simulation.
Definition at line 11 of file plane_insertion.cc.
References PlaneInsertion< dim >::change_to_triangulation, PlaneInsertion< dim >::current_inserting_particle_type, PlaneInsertion< dim >::find_centers_of_inplane_cells(), PlaneInsertion< dim >::find_inplane_cells(), DEMSolverParameters< dim >::insertion_info, Parameters::Lagrangian::InsertionInfo::insertion_maximum_offset, Parameters::Lagrangian::InsertionInfo::insertion_plane_normal_vector, Parameters::Lagrangian::InsertionInfo::insertion_plane_point, PlaneInsertion< dim >::mark_for_update, and PlaneInsertion< dim >::maximum_range_for_randomness.
Member Function Documentation
deserialize()
template<int dim> virtual void PlaneInsertion< dim >::deserialize (boost::archive::text_iarchive & ar, const unsigned int) inline override virtual
Deserialize an input archive to the plane insertion object.
Parameters
ar Input archive where the attributes are stored.
Implements Insertion< dim >.
Definition at line 94 of file plane_insertion.h.
References PlaneInsertion< dim >::current_inserting_particle_type, and PlaneInsertion< dim >::particles_of_each_type_remaining.
find_centers_of_inplane_cells()
template<int dim> void PlaneInsertion< dim >::find_centers_of_inplane_cells private
Store the location of the centers of all the cells that are in the plane.
Definition at line 95 of file plane_insertion.cc.
find_inplane_cells()
template<int dim> void PlaneInsertion< dim >::find_inplane_cells (const parallel::distributed::Triangulation< dim > & triangulation, Point< 3 > plane_point, Tensor< 1, 3 > plane_normal_vector) private
Store the cells that are cut by the plane.
Parameters
triangulation Triangulation to access the cells in which the particles are inserted
plane_point Point which define the plane
plane_normal_vector Vector which define the normal direction of the plane.
Definition at line 45 of file plane_insertion.cc.
References point_nd_to_3d().
insert()
template<int dim> void PlaneInsertion< dim >::insert (Particles::ParticleHandler< dim > & particle_handler, const parallel::distributed::Triangulation< dim > & triangulation, const DEMSolverParameters< dim > & dem_parameters) override virtual
Carries out the insertion of particles.
Parameters
particle_handler The particle handler of particles which are being inserted.
triangulation Triangulation to access the cells in which the particles are inserted.
dem_parameters DEM parameters declared in the .prm file.
Implements Insertion< dim >.
Definition at line 108 of file plane_insertion.cc.
References DEMSolverParameters< dim >::insertion_info, Parameters::Lagrangian::InsertionInfo::insertion_plane_normal_vector, Parameters::Lagrangian::InsertionInfo::insertion_plane_point, DEMSolverParameters< dim >::lagrangian_physical_properties, Parameters::Lagrangian::LagrangianPhysicalProperties::number, and Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number.
serialize()
template<int dim> virtual void PlaneInsertion< dim >::serialize (boost::archive::text_oarchive & ar, const unsigned int) inline override virtual
Serialize the plane insertion object to an output archive.
Parameters
ar Output archive where the attributes are stored.
Implements Insertion< dim >.
Definition at line 82 of file plane_insertion.h.
References PlaneInsertion< dim >::current_inserting_particle_type, and PlaneInsertion< dim >::particles_of_each_type_remaining.
Member Data Documentation
cells_centers
template<int dim> std::unordered_map<unsigned int, Point<dim> > PlaneInsertion< dim >::cells_centers private
Definition at line 127 of file plane_insertion.h.
change_to_triangulation
template<int dim> boost::signals2::connection PlaneInsertion< dim >::change_to_triangulation private
Definition at line 129 of file plane_insertion.h.
current_inserting_particle_type
template<int dim> unsigned int PlaneInsertion< dim >::current_inserting_particle_type private
Definition at line 126 of file plane_insertion.h.
mark_for_update
template<int dim> bool PlaneInsertion< dim >::mark_for_update private
Definition at line 128 of file plane_insertion.h.
maximum_range_for_randomness
template<int dim> double PlaneInsertion< dim >::maximum_range_for_randomness private
Definition at line 124 of file plane_insertion.h.
particles_of_each_type_remaining
template<int dim> int PlaneInsertion< dim >::particles_of_each_type_remaining private
Definition at line 125 of file plane_insertion.h.
plane_cells_for_insertion
template<int dim> std::set<typename Triangulation<dim>::active_cell_iterator> PlaneInsertion< dim >::plane_cells_for_insertion private
Definition at line 123 of file plane_insertion.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/plane_insertion.h
/home/runner/work/lethe/lethe/source/dem/plane_insertion.cc