Developer documentation for the Lethe open-source library: GDNavierStokesSolver< dim > Class Template Reference
GDNavierStokesSolver< dim > Class Template Reference
#include <gd_navier_stokes.h>
Public Member Functions
GDNavierStokesSolver (SimulationParameters< dim > &nsparam)
~GDNavierStokesSolver ()
void solve ()
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
solve_non_linear_system Solves the non linear system of equations
virtual void apply_constraints ()
Applies constraints to a local_evaluation_point.
virtual double get_current_residual ()
Default way to evaluate the residual for the nonlinear solver. Some application may use more complex evaluation of the residual and override this method.
Private Member Functions
void assemble_system_matrix () override
Assembles the matrix associated with the solver.
void assemble_system_rhs () override
Assemble the rhs associated with the solver.
virtual void update_multiphysics_time_average_solution () override
Update the average velocity field solution in the multiphysics interface.
void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data)
Assemble the local matrix for a given cell.
void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data)
Assemble the local rhs for a given cell.
void setup_assemblers ()
sets up the vector of assembler functions
void copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > &copy_data)
Copy local cell information to global matrix.
void copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > &copy_data)
Copy local cell rhs information to global rhs.
template<bool assemble_matrix, Parameters::SimulationControl::TimeSteppingMethod scheme>
void assembleGD ()
void assemble_L2_projection ()
virtual void setup_dofs_fd () override
setup_dofs
virtual void set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart=false) override
void set_solution_vector (double value)
void solve_L2_system (bool initial_step, double relative_residual, double minimum_residual)
void solve_linear_system (const bool initial_step, const bool renewed_matrix) override
void solve_system_GMRES (const bool initial_step, const double relative_residual, const double minimum_residual, const bool renewed_matrix)
void setup_AMG ()
void setup_ILU ()
Private Attributes
TrilinosWrappers::BlockSparsityPattern sparsity_pattern
TrilinosWrappers::BlockSparseMatrix system_matrix
TrilinosWrappers::SparseMatrix pressure_mass_matrix
std::vector< types::global_dof_index > dofs_per_block
std::shared_ptr< TrilinosWrappers::PreconditionILU > velocity_ilu_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionAMG > velocity_amg_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionILU > pressure_ilu_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionAMG > pressure_amg_preconditioner
std::shared_ptr< BlockSchurPreconditioner< TrilinosWrappers::PreconditionILU > > system_ilu_preconditioner
std::shared_ptr< BlockSchurPreconditioner< TrilinosWrappers::PreconditionAMG > > system_amg_preconditioner
const double gamma = 1
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Protected Member Functions inherited from NavierStokesBase< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual TrilinosWrappers::MPI::BlockVector & get_evaluation_point () override
Getter methods to get the private attributes for the physic currently solved.
virtual TrilinosWrappers::MPI::BlockVector & get_local_evaluation_point () override
virtual TrilinosWrappers::MPI::BlockVector & get_newton_update () override
virtual TrilinosWrappers::MPI::BlockVector & get_present_solution () override
virtual TrilinosWrappers::MPI::BlockVector & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
void finish_simulation ()
finish_simulation Finish the simulation by calling all the post-processing elements that are required
virtual void postprocess (bool first_iteration)
postprocess Post-process simulation after an iteration
virtual void setup_dofs ()
setup_dofs
virtual void set_initial_condition (Parameters::InitialConditionType initial_condition_type, bool restart=false)
set_initial_conditions
virtual void finish_time_step ()
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
virtual void percolate_time_vectors_fd ()
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
void finish_simulation_fd ()
finish_simulation Finishes the simulation for fluid dynamics by calling the post-processing elements that are required
virtual void postprocess_fd (bool first_iteration)
postprocess Post-process fluid dynamics after an iteration
void postprocessing_forces (const TrilinosWrappers::MPI::BlockVector &evaluation_point)
postprocessing_forces Post-processing function Outputs the forces acting on each boundary condition
void postprocessing_torques (const TrilinosWrappers::MPI::BlockVector &evaluation_point)
postprocessing_torques Post-processing function Outputs the torque acting on each boundary condition
virtual void dynamic_flow_control ()
dynamic_flow_control If set to enable, dynamic_flow_control allows to control the flow by executing space-average velocity and beta coefficient force calculation at each time step.
virtual void iterate ()
iterate Do a regular CFD iteration
void box_refine_mesh ()
Allow the initial refinement of all cells of the principal mesh that are partially contained in one of the cells of the box refinement mesh given in the parameter.
virtual void refine_mesh ()
Allow the refinement of the mesh according to one of the 2 methods proposed.
void refine_mesh_kelly ()
Allow the refinement of the mesh based on the Kelly error estimator. See : https://www.dealii.org/current/doxygen/deal.II/classKellyErrorEstimator.html for more information on the Kelly error estimator.
void refine_mesh_uniform ()
Allow the uniform refinement of all the mesh.
virtual void read_checkpoint ()
read_checkpoint
void set_nodal_values ()
set_nodal_values Set the nodal values of velocity and pressure
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
Check if a specifique boundary condition exist.
void establish_solid_domain (const bool non_zero_constraints)
Turns regions of the mesh where the material_id=1 to a solid block by injecting it into the constraints This is achieved by imposing $\mathbf{u}=0$ within the cells which have a material_id=1. In addition, solid cells which are not connected to the fluid by any means also get a pressure dirichlet boundary condition which fixes the pressure to 0. This ensures that the linear system is well-posed. Right now, this routine only supports the usage of 1 solid domain, but eventually it could be extended to more than one. By default, the fluid domain is assumed to have a material_id=0 and the rest of the domains have a material_id>0.
virtual void write_checkpoint ()
write_checkpoint
void write_output_results (const TrilinosWrappers::MPI::BlockVector &solution)
write_output_results Post-processing as parallel VTU files
virtual void output_field_hook (DataOut< dim > &)
output_field_hook This function is to be redefined in specialized classes to adapt the output to each solver.
void write_output_forces ()
write_output_forces Writes the forces per boundary condition to a text file output
void write_output_torques ()
write_output_torques Writes the torques per boundary condition to a text file output
void rescale_pressure_dofs_in_newton_update ()
rescale_pressure_dofs_in_newton_update This function is used to rescale pressure DOFs in the newton correction
TrilinosWrappers::MPI::BlockVector init_temporary_vector ()
init_temporary_vector This function initializes correctly a temporary vector depending on the vector type
Protected Attributes inherited from NavierStokesBase< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > >
std::vector< IndexSet > locally_owned_dofs
std::vector< IndexSet > locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
TrilinosWrappers::MPI::BlockVector evaluation_point
TrilinosWrappers::MPI::BlockVector local_evaluation_point
TrilinosWrappers::MPI::BlockVector newton_update
TrilinosWrappers::MPI::BlockVector present_solution
TrilinosWrappers::MPI::BlockVector system_rhs
std::vector< TrilinosWrappers::MPI::BlockVector > previous_solutions
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > > > average_velocities
TrilinosWrappers::MPI::BlockVector average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::vector< Tensor< 1, dim > > > forces_on_boundaries
std::vector< Tensor< 1, 3 > > torques_on_boundaries
std::vector< TableHandler > forces_tables
std::vector< TableHandler > torques_tables
Detailed Description
template<int dim>
class GDNavierStokesSolver< dim >
A solver class for the Navier-Stokes equation using Grad-Div stabilization
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Author
Bruno Blais, 2019
Definition at line 78 of file gd_navier_stokes.h.
Constructor & Destructor Documentation
GDNavierStokesSolver()
template<int dim> GDNavierStokesSolver< dim >::GDNavierStokesSolver (SimulationParameters< dim > & nsparam)
Definition at line 48 of file gd_navier_stokes.cc.
~GDNavierStokesSolver()
template<int dim> GDNavierStokesSolver< dim >::~GDNavierStokesSolver
Definition at line 56 of file gd_navier_stokes.cc.
Member Function Documentation
assemble_L2_projection()
template<int dim> void GDNavierStokesSolver< dim >::assemble_L2_projection private
Definition at line 441 of file gd_navier_stokes.cc.
References pressure.
assemble_local_system_matrix()
template<int dim> void GDNavierStokesSolver< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) private
Assemble the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 233 of file gd_navier_stokes.cc.
References NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, NavierStokesScratchData< dim >::enable_heat_transfer(), heat_transfer, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_vof(), StabilizedMethodsTensorCopyData< dim >::reset(), and VOF.
assemble_local_system_rhs()
template<int dim> void GDNavierStokesSolver< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) private
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 360 of file gd_navier_stokes.cc.
References NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, heat_transfer, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_heat_transfer(), NavierStokesScratchData< dim >::reinit_vof(), StabilizedMethodsTensorCopyData< dim >::reset(), and VOF.
assemble_system_matrix()
template<int dim> void GDNavierStokesSolver< dim >::assemble_system_matrix override private virtual
Assembles the matrix associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 176 of file gd_navier_stokes.cc.
References GDNavierStokesSolver< dim >::assemble_local_system_matrix(), GDNavierStokesSolver< dim >::copy_local_matrix_to_global_matrix(), and VOF.
assemble_system_rhs()
template<int dim> void GDNavierStokesSolver< dim >::assemble_system_rhs override private virtual
Assemble the rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 305 of file gd_navier_stokes.cc.
References GDNavierStokesSolver< dim >::assemble_local_system_rhs(), GDNavierStokesSolver< dim >::copy_local_rhs_to_global_rhs(), heat_transfer, and VOF.
assembleGD()
template<int dim> template<bool assemble_matrix, Parameters::SimulationControl::TimeSteppingMethod scheme> void GDNavierStokesSolver< dim >::assembleGD () private
copy_local_matrix_to_global_matrix()
template<int dim> void GDNavierStokesSolver< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > & copy_data) private
Copy local cell information to global matrix.
Definition at line 290 of file gd_navier_stokes.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void GDNavierStokesSolver< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > & copy_data) private
Copy local cell rhs information to global rhs.
Definition at line 425 of file gd_navier_stokes.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_rhs.
set_initial_condition_fd()
template<int dim> void GDNavierStokesSolver< dim >::set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart = false) override private virtual
Set the initial condition using a L2 or a viscous solver
Implements NavierStokesBase< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > >.
Definition at line 792 of file gd_navier_stokes.cc.
References Parameters::L2projection, Parameters::nodal, read_checkpoint(), Parameters::SimulationControl::steady, and Parameters::viscous.
set_solution_vector()
template<int dim> void GDNavierStokesSolver< dim >::set_solution_vector (double value) private
Definition at line 781 of file gd_navier_stokes.cc.
setup_AMG()
template<int dim> void GDNavierStokesSolver< dim >::setup_AMG private
Set-up AMG preconditioner
Definition at line 919 of file gd_navier_stokes.cc.
References fluid_dynamics, and pressure.
setup_assemblers()
template<int dim> void GDNavierStokesSolver< dim >::setup_assemblers private
sets up the vector of assembler functions
Definition at line 63 of file gd_navier_stokes.cc.
References Parameters::Stabilization::grad_div, is_bdf(), and Parameters::VelocitySource::srf.
setup_dofs_fd()
template<int dim> void GDNavierStokesSolver< dim >::setup_dofs_fd override private virtual
setup_dofs
Initialize the dofs for fluid dynamics
Implements NavierStokesBase< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > >.
Definition at line 526 of file gd_navier_stokes.cc.
References fluid_dynamics, BoundaryConditions::function, Parameters::MeshAdaptation::none, BoundaryConditions::noslip, BoundaryConditions::periodic, and BoundaryConditions::slip.
setup_ILU()
template<int dim> void GDNavierStokesSolver< dim >::setup_ILU private
Set-up ILU preconditioner
Definition at line 876 of file gd_navier_stokes.cc.
References fluid_dynamics.
solve()
template<int dim> void GDNavierStokesSolver< dim >::solve
Definition at line 1213 of file gd_navier_stokes.cc.
References read_mesh_and_manifolds().
solve_L2_system()
template<int dim> void GDNavierStokesSolver< dim >::solve_L2_system (bool initial_step, double relative_residual, double minimum_residual) private
Solver for the L2 Projection linear system
Definition at line 1136 of file gd_navier_stokes.cc.
References fluid_dynamics, and Parameters::quiet.
solve_linear_system()
template<int dim> void GDNavierStokesSolver< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix) override private virtual
Solver for the NS linear system of equations
Implements PhysicsSolver< VectorType >.
Definition at line 849 of file gd_navier_stokes.cc.
References fluid_dynamics, and Parameters::LinearSolver::gmres.
solve_system_GMRES()
template<int dim> void GDNavierStokesSolver< dim >::solve_system_GMRES (const bool initial_step, const double relative_residual, const double minimum_residual, const bool renewed_matrix) private
GMRES solver with ILU preconditioning or AMG preconditioning
Definition at line 1048 of file gd_navier_stokes.cc.
References Parameters::LinearSolver::amg, fluid_dynamics, Parameters::LinearSolver::ilu, and Parameters::quiet.
update_multiphysics_time_average_solution()
template<int dim> void GDNavierStokesSolver< dim >::update_multiphysics_time_average_solution override private virtual
Update the average velocity field solution in the multiphysics interface.
Implements NavierStokesBase< dim, TrilinosWrappers::MPI::BlockVector, std::vector< IndexSet > >.
Definition at line 164 of file gd_navier_stokes.cc.
References fluid_dynamics.
Member Data Documentation
dofs_per_block
template<int dim> std::vector<types::global_dof_index> GDNavierStokesSolver< dim >::dofs_per_block private
Definition at line 240 of file gd_navier_stokes.h.
gamma
template<int dim> const double GDNavierStokesSolver< dim >::gamma = 1 private
Definition at line 257 of file gd_navier_stokes.h.
pressure_amg_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionAMG> GDNavierStokesSolver< dim >::pressure_amg_preconditioner private
Definition at line 249 of file gd_navier_stokes.h.
pressure_ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> GDNavierStokesSolver< dim >::pressure_ilu_preconditioner private
Definition at line 247 of file gd_navier_stokes.h.
pressure_mass_matrix
template<int dim> TrilinosWrappers::SparseMatrix GDNavierStokesSolver< dim >::pressure_mass_matrix private
Definition at line 238 of file gd_navier_stokes.h.
sparsity_pattern
template<int dim> TrilinosWrappers::BlockSparsityPattern GDNavierStokesSolver< dim >::sparsity_pattern private
Members
Definition at line 236 of file gd_navier_stokes.h.
system_amg_preconditioner
template<int dim> std::shared_ptr<BlockSchurPreconditioner<TrilinosWrappers::PreconditionAMG> > GDNavierStokesSolver< dim >::system_amg_preconditioner private
Definition at line 255 of file gd_navier_stokes.h.
system_ilu_preconditioner
template<int dim> std::shared_ptr<BlockSchurPreconditioner<TrilinosWrappers::PreconditionILU> > GDNavierStokesSolver< dim >::system_ilu_preconditioner private
Definition at line 252 of file gd_navier_stokes.h.
system_matrix
template<int dim> TrilinosWrappers::BlockSparseMatrix GDNavierStokesSolver< dim >::system_matrix private
Definition at line 237 of file gd_navier_stokes.h.
velocity_amg_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionAMG> GDNavierStokesSolver< dim >::velocity_amg_preconditioner private
Definition at line 245 of file gd_navier_stokes.h.
velocity_ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> GDNavierStokesSolver< dim >::velocity_ilu_preconditioner private
Definition at line 243 of file gd_navier_stokes.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/gd_navier_stokes.h
/home/runner/work/lethe/lethe/source/solvers/gd_navier_stokes.cc