Developer documentation for the Lethe open-source library: Tracer< dim > Class Template Reference
Tracer< dim > Class Template Reference
#include <tracer.h>
Public Member Functions
Tracer (MultiphysicsInterface< dim > *multiphysics_interface, const SimulationParameters< dim > &p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim >> p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control)
void attach_solution_to_output (DataOut< dim > &data_out) override
Attach the solution vector to the DataOut provided. This function enable the auxiliary physics to output their solution via the core solver.
double calculate_L2_error ()
Calculates the L2 error of the solution.
void finish_simulation () override
Carry out the operations required to finish a simulation correctly.
void percolate_time_vectors () override
Rearrange vector solution correctly for transient simulations.
void postprocess (bool first_iteration) override
Postprocess the auxiliary physics results. Post-processing this case implies the calculation of all derived quantities using the solution vector of the physics. It does not concern the output of the solution using the DataOutObject, which is accomplished through the attach_solution_to_output function.
void pre_mesh_adaptation () override
pre_mesh_adaption Prepares the auxiliary physics variables for a mesh refinement/coarsening
void post_mesh_adaptation () override
post_mesh_adaption Interpolates the auxiliary physics variables to the new mesh
void compute_kelly (const std::pair< const Parameters::MeshAdaptation::Variable, Parameters::MultipleAdaptationParameters > &, dealii::Vector< float > &) override
Compute the Kelly error estimator for mesh refinement. NB : not implemented for the tracer parameter for now.
void write_checkpoint () override
Prepares Heat Transfer to write checkpoint.
void read_checkpoint () override
Allows tracer physics to set-up solution vector from checkpoint file;.
const DoFHandler< dim > & get_dof_handler () override
Returns the dof_handler of the tracer physics.
void setup_dofs () override
Sets-up the DofHandler and the degree of freedom associated with the physics.
void set_initial_conditions () override
Sets-up the initial conditions associated with the physics. Generally, physics only support imposing nodal values, but some physics additionnaly support the use of L2 projection or steady-state solutions.
void update_boundary_conditions () override
Update non zero constraints if the boundary is time-dependent.
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
Call for the solution of the linear system of equation using a strategy appropriate to the auxiliary physics.
TrilinosWrappers::MPI::Vector & get_evaluation_point () override
Getter methods to get the private attributes for the physic currently solved NB : dof_handler and present_solution are passed to the multiphysics interface at the end of the setup_dofs method.
TrilinosWrappers::MPI::Vector & get_local_evaluation_point () override
TrilinosWrappers::MPI::Vector & get_newton_update () override
TrilinosWrappers::MPI::Vector & get_present_solution () override
TrilinosWrappers::MPI::Vector & get_system_rhs () override
AffineConstraints< double > & get_nonzero_constraints () override
Public Member Functions inherited from AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >
AuxiliaryPhysics (const Parameters::NonLinearSolver non_linear_solver_parameters)
AuxiliaryPhysics - Base constructor for Auxiliary physics. At the present moment this is an interface with nothing. The auxiliary physics is a pure virtual class.
virtual ~AuxiliaryPhysics ()
AuxiliaryPhysics - Base destructor. At the present moment this is an interface with nothing.
virtual void modify_solution ()
Carry out modifications on the auxiliary physic solution. To be defined for some physics only (eg. free surface, see vof.h).
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
solve_non_linear_system Solves the non linear system of equations
virtual void apply_constraints ()
Applies constraints to a local_evaluation_point.
virtual double get_current_residual ()
Default way to evaluate the residual for the nonlinear solver. Some application may use more complex evaluation of the residual and override this method.
Private Member Functions
void assemble_system_matrix () override
Assembles the matrix associated with the solver.
void assemble_system_rhs () override
Assemble the rhs associated with the solver.
virtual void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, TracerScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
Assemble the local matrix for a given cell.
virtual void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, TracerScratchData< dim > &scratch_data, StabilizedMethodsCopyData &copy_data)
Assemble the local rhs for a given cell.
virtual void setup_assemblers ()
sets up the vector of assembler functions
virtual void copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData &copy_data)
Copy local cell information to global matrix.
virtual void copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData &copy_data)
Copy local cell rhs information to global rhs.
void calculate_tracer_statistics ()
Calculate tracer statistics : Max, min, average and standard-deviation.
void write_tracer_statistics ()
Writes the tracer statistics to an output file.
Private Attributes
MultiphysicsInterface< dim > * multiphysics
TimerOutput computing_timer
const SimulationParameters< dim > & simulation_parameters
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
std::shared_ptr< SimulationControl > simulation_control
DoFHandler< dim > dof_handler
std::shared_ptr< FiniteElement< dim > > fe
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
ConvergenceTable error_table
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
TrilinosWrappers::MPI::Vector evaluation_point
TrilinosWrappers::MPI::Vector local_evaluation_point
TrilinosWrappers::MPI::Vector newton_update
TrilinosWrappers::MPI::Vector present_solution
TrilinosWrappers::MPI::Vector system_rhs
AffineConstraints< double > nonzero_constraints
AffineConstraints< double > zero_constraints
TrilinosWrappers::SparseMatrix system_matrix
std::vector< TrilinosWrappers::MPI::Vector > previous_solutions
std::shared_ptr< parallel::distributed::SolutionTransfer< dim, TrilinosWrappers::MPI::Vector > > solution_transfer
std::vector< parallel::distributed::SolutionTransfer< dim, TrilinosWrappers::MPI::Vector > > previous_solutions_transfer
std::vector< std::shared_ptr< TracerAssemblerBase< dim > > > assemblers
TableHandler statistics_table
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class Tracer< dim >
Definition at line 53 of file tracer.h.
Constructor & Destructor Documentation
Tracer()
template<int dim> Tracer< dim >::Tracer (MultiphysicsInterface< dim > * multiphysics_interface, const SimulationParameters< dim > & p_simulation_parameters, std::shared_ptr< parallel::DistributedTriangulationBase< dim >> p_triangulation, std::shared_ptr< SimulationControl > p_simulation_control) inline
Definition at line 56 of file tracer.h.
References Tracer< dim >::cell_quadrature, Tracer< dim >::computing_timer, Tracer< dim >::dof_handler, Tracer< dim >::fe, Tracer< dim >::mapping, maximum_number_of_previous_solutions(), Parameters::Timer::none, Tracer< dim >::previous_solutions, Tracer< dim >::previous_solutions_transfer, Tracer< dim >::simulation_parameters, and Tracer< dim >::solution_transfer.
Member Function Documentation
assemble_local_system_matrix()
template<int dim> void Tracer< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, TracerScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for TracerScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 78 of file tracer.cc.
References TracerScratchData< dim >::calculate_physical_properties(), StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, TracerScratchData< dim >::reinit(), TracerScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_local_system_rhs()
template<int dim> void Tracer< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, TracerScratchData< dim > & scratch_data, StabilizedMethodsCopyData & copy_data) private virtual
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for TracerScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Definition at line 204 of file tracer.cc.
References TracerScratchData< dim >::calculate_physical_properties(), StabilizedMethodsCopyData::cell_is_local, fluid_dynamics, StabilizedMethodsCopyData::local_dof_indices, TracerScratchData< dim >::reinit(), TracerScratchData< dim >::reinit_velocity(), and StabilizedMethodsCopyData::reset().
assemble_system_matrix()
template<int dim> void Tracer< dim >::assemble_system_matrix override private virtual
Assembles the matrix associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 47 of file tracer.cc.
References Tracer< dim >::assemble_local_system_matrix(), Tracer< dim >::copy_local_matrix_to_global_matrix(), and fluid_dynamics.
assemble_system_rhs()
template<int dim> void Tracer< dim >::assemble_system_rhs override private virtual
Assemble the rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Definition at line 172 of file tracer.cc.
References Tracer< dim >::assemble_local_system_rhs(), Tracer< dim >::copy_local_rhs_to_global_rhs(), and fluid_dynamics.
attach_solution_to_output()
template<int dim> void Tracer< dim >::attach_solution_to_output (DataOut< dim > & data_out) override virtual
Attach the solution vector to the DataOut provided. This function enable the auxiliary physics to output their solution via the core solver.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 296 of file tracer.cc.
calculate_L2_error()
template<int dim> double Tracer< dim >::calculate_L2_error
Calculates the L2 error of the solution.
Definition at line 303 of file tracer.cc.
calculate_tracer_statistics()
template<int dim> void Tracer< dim >::calculate_tracer_statistics private
Calculate tracer statistics : Max, min, average and standard-deviation.
Definition at line 423 of file tracer.cc.
References Parameters::verbose.
compute_kelly()
template<int dim> void Tracer< dim >::compute_kelly (const std::pair< const Parameters::MeshAdaptation::Variable, Parameters::MultipleAdaptationParameters > & , dealii::Vector< float > &) inline override virtual
Compute the Kelly error estimator for mesh refinement. NB : not implemented for the tracer parameter for now.
Parameters
ivar The current element of the map simulation_parameters.mesh_adaptation.variables
estimated_error_per_cell The deal.II vector of estimated_error_per_cell
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 176 of file tracer.h.
copy_local_matrix_to_global_matrix()
template<int dim> void Tracer< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell information to global matrix.
Definition at line 157 of file tracer.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void Tracer< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsCopyData & copy_data) private virtual
Copy local cell rhs information to global rhs.
Definition at line 282 of file tracer.cc.
References StabilizedMethodsCopyData::cell_is_local, StabilizedMethodsCopyData::local_dof_indices, and StabilizedMethodsCopyData::local_rhs.
finish_simulation()
template<int dim> void Tracer< dim >::finish_simulation override virtual
Carry out the operations required to finish a simulation correctly.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 348 of file tracer.cc.
References Parameters::SimulationControl::steady, and Parameters::verbose.
get_dof_handler()
template<int dim> const DoFHandler<dim>& Tracer< dim >::get_dof_handler () inline override virtual
Returns the dof_handler of the tracer physics.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 201 of file tracer.h.
References Tracer< dim >::dof_handler.
get_evaluation_point()
template<int dim> TrilinosWrappers::MPI::Vector& Tracer< dim >::get_evaluation_point () inline override virtual
Getter methods to get the private attributes for the physic currently solved NB : dof_handler and present_solution are passed to the multiphysics interface at the end of the setup_dofs method.
Implements PhysicsSolver< VectorType >.
Definition at line 245 of file tracer.h.
References Tracer< dim >::evaluation_point.
get_local_evaluation_point()
template<int dim> TrilinosWrappers::MPI::Vector& Tracer< dim >::get_local_evaluation_point () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 250 of file tracer.h.
References Tracer< dim >::local_evaluation_point.
get_newton_update()
template<int dim> TrilinosWrappers::MPI::Vector& Tracer< dim >::get_newton_update () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 255 of file tracer.h.
References Tracer< dim >::newton_update.
get_nonzero_constraints()
template<int dim> AffineConstraints<double>& Tracer< dim >::get_nonzero_constraints () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 270 of file tracer.h.
References Tracer< dim >::nonzero_constraints.
get_present_solution()
template<int dim> TrilinosWrappers::MPI::Vector& Tracer< dim >::get_present_solution () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 260 of file tracer.h.
References Tracer< dim >::present_solution.
get_system_rhs()
template<int dim> TrilinosWrappers::MPI::Vector& Tracer< dim >::get_system_rhs () inline override virtual
Implements PhysicsSolver< VectorType >.
Definition at line 265 of file tracer.h.
References Tracer< dim >::system_rhs.
percolate_time_vectors()
template<int dim> void Tracer< dim >::percolate_time_vectors override virtual
Rearrange vector solution correctly for transient simulations.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 375 of file tracer.cc.
post_mesh_adaptation()
template<int dim> void Tracer< dim >::post_mesh_adaptation override virtual
post_mesh_adaption Interpolates the auxiliary physics variables to the new mesh
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 531 of file tracer.cc.
postprocess()
template<int dim> void Tracer< dim >::postprocess (bool first_iteration) override virtual
Postprocess the auxiliary physics results. Post-processing this case implies the calculation of all derived quantities using the solution vector of the physics. It does not concern the output of the solution using the DataOutObject, which is accomplished through the attach_solution_to_output function.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 386 of file tracer.cc.
References announce_string(), calculate_L2_error(), Parameters::Timer::iteration, and Parameters::verbose.
pre_mesh_adaptation()
template<int dim> void Tracer< dim >::pre_mesh_adaptation override virtual
pre_mesh_adaption Prepares the auxiliary physics variables for a mesh refinement/coarsening
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 518 of file tracer.cc.
read_checkpoint()
template<int dim> void Tracer< dim >::read_checkpoint override virtual
Allows tracer physics to set-up solution vector from checkpoint file;.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 594 of file tracer.cc.
References deserialize_table().
set_initial_conditions()
template<int dim> void Tracer< dim >::set_initial_conditions override virtual
Sets-up the initial conditions associated with the physics. Generally, physics only support imposing nodal values, but some physics additionnaly support the use of L2 projection or steady-state solutions.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 783 of file tracer.cc.
setup_assemblers()
template<int dim> void Tracer< dim >::setup_assemblers private virtual
sets up the vector of assembler functions
Definition at line 30 of file tracer.cc.
References is_bdf().
setup_dofs()
template<int dim> void Tracer< dim >::setup_dofs override virtual
Sets-up the DofHandler and the degree of freedom associated with the physics.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 642 of file tracer.cc.
References tracer, and BoundaryConditions::tracer_dirichlet.
solve_linear_system()
template<int dim> void Tracer< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) override virtual
Call for the solution of the linear system of equation using a strategy appropriate to the auxiliary physics.
Parameters
initial_step Provides the linear solver with indication if this solution is the first one for the system of equation or not
renewed_matrix Indicates to the linear solve if the system matrix has been recalculated or not
Implements PhysicsSolver< VectorType >.
Definition at line 796 of file tracer.cc.
References Parameters::quiet, and tracer.
update_boundary_conditions()
template<int dim> void Tracer< dim >::update_boundary_conditions override virtual
Update non zero constraints if the boundary is time-dependent.
Reimplemented from AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 747 of file tracer.cc.
References BoundaryConditions::tracer_dirichlet.
write_checkpoint()
template<int dim> void Tracer< dim >::write_checkpoint override virtual
Prepares Heat Transfer to write checkpoint.
Implements AuxiliaryPhysics< dim, TrilinosWrappers::MPI::Vector >.
Definition at line 560 of file tracer.cc.
References serialize_table().
write_tracer_statistics()
template<int dim> void Tracer< dim >::write_tracer_statistics private
Writes the tracer statistics to an output file.
Definition at line 501 of file tracer.cc.
Member Data Documentation
assemblers
template<int dim> std::vector<std::shared_ptr<TracerAssemblerBase<dim> > > Tracer< dim >::assemblers private
Definition at line 412 of file tracer.h.
cell_quadrature
template<int dim> std::shared_ptr<Quadrature<dim> > Tracer< dim >::cell_quadrature private
Definition at line 381 of file tracer.h.
computing_timer
template<int dim> TimerOutput Tracer< dim >::computing_timer private
Definition at line 367 of file tracer.h.
dof_handler
template<int dim> DoFHandler<dim> Tracer< dim >::dof_handler private
Definition at line 375 of file tracer.h.
error_table
template<int dim> ConvergenceTable Tracer< dim >::error_table private
Definition at line 384 of file tracer.h.
evaluation_point
template<int dim> TrilinosWrappers::MPI::Vector Tracer< dim >::evaluation_point private
Definition at line 390 of file tracer.h.
fe
template<int dim> std::shared_ptr<FiniteElement<dim> > Tracer< dim >::fe private
Definition at line 378 of file tracer.h.
local_evaluation_point
template<int dim> TrilinosWrappers::MPI::Vector Tracer< dim >::local_evaluation_point private
Definition at line 391 of file tracer.h.
locally_owned_dofs
template<int dim> IndexSet Tracer< dim >::locally_owned_dofs private
Definition at line 387 of file tracer.h.
locally_relevant_dofs
template<int dim> IndexSet Tracer< dim >::locally_relevant_dofs private
Definition at line 388 of file tracer.h.
mapping
template<int dim> std::shared_ptr<Mapping<dim> > Tracer< dim >::mapping private
Definition at line 380 of file tracer.h.
multiphysics
template<int dim> MultiphysicsInterface<dim>* Tracer< dim >::multiphysics private
Definition at line 365 of file tracer.h.
newton_update
template<int dim> TrilinosWrappers::MPI::Vector Tracer< dim >::newton_update private
Definition at line 392 of file tracer.h.
nonzero_constraints
template<int dim> AffineConstraints<double> Tracer< dim >::nonzero_constraints private
Definition at line 395 of file tracer.h.
present_solution
template<int dim> TrilinosWrappers::MPI::Vector Tracer< dim >::present_solution private
Definition at line 393 of file tracer.h.
previous_solutions
template<int dim> std::vector<TrilinosWrappers::MPI::Vector> Tracer< dim >::previous_solutions private
Definition at line 401 of file tracer.h.
previous_solutions_transfer
template<int dim> std::vector< parallel::distributed::SolutionTransfer<dim, TrilinosWrappers::MPI::Vector> > Tracer< dim >::previous_solutions_transfer private
Definition at line 409 of file tracer.h.
simulation_control
template<int dim> std::shared_ptr<SimulationControl> Tracer< dim >::simulation_control private
Definition at line 374 of file tracer.h.
simulation_parameters
template<int dim> const SimulationParameters<dim>& Tracer< dim >::simulation_parameters private
Definition at line 369 of file tracer.h.
solution_transfer
template<int dim> std::shared_ptr< parallel::distributed::SolutionTransfer<dim, TrilinosWrappers::MPI::Vector> > Tracer< dim >::solution_transfer private
Definition at line 406 of file tracer.h.
statistics_table
template<int dim> TableHandler Tracer< dim >::statistics_table private
Definition at line 415 of file tracer.h.
system_matrix
template<int dim> TrilinosWrappers::SparseMatrix Tracer< dim >::system_matrix private
Definition at line 397 of file tracer.h.
system_rhs
template<int dim> TrilinosWrappers::MPI::Vector Tracer< dim >::system_rhs private
Definition at line 394 of file tracer.h.
triangulation
template<int dim> std::shared_ptr<parallel::DistributedTriangulationBase<dim> > Tracer< dim >::triangulation private
Definition at line 373 of file tracer.h.
zero_constraints
template<int dim> AffineConstraints<double> Tracer< dim >::zero_constraints private
Definition at line 396 of file tracer.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/tracer.h
/home/runner/work/lethe/lethe/source/solvers/tracer.cc