Developer documentation for the Lethe open-source library: GLSVANSSolver< dim > Class Template Reference
GLSVANSSolver< dim > Class Template Reference
#include <gls_vans.h>
Public Member Functions
GLSVANSSolver (CFDDEMSimulationParameters< dim > &nsparam)
~GLSVANSSolver ()
virtual void solve () override
solve Solves the Navier-Stokes problem
Public Member Functions inherited from GLSNavierStokesSolver< dim >
GLSNavierStokesSolver (SimulationParameters< dim > &nsparam)
~GLSNavierStokesSolver ()
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
solve_non_linear_system Solves the non linear system of equations
virtual void apply_constraints ()
Applies constraints to a local_evaluation_point.
virtual double get_current_residual ()
Default way to evaluate the residual for the nonlinear solver. Some application may use more complex evaluation of the residual and override this method.
Protected Member Functions
virtual void setup_dofs () override
associates the degrees of freedom to each vertex of the finite elements and initialize the void fraction
virtual void iterate () override
iterate Do a regular CFD iteration
void initialize_void_fraction ()
void calculate_void_fraction (const double time, bool load_balance_step)
void vertices_cell_mapping ()
virtual void monitor_mass_conservation ()
virtual void finish_time_step_fd ()
finish_time_step Finishes the time step Post-processing and time stepping
void assemble_system_matrix () override
Assembles the matrix associated with the solver.
void assemble_system_rhs () override
Assembles the rhs associated with the solver.
void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
Assembles the local matrix for a given cell.
void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data) override
Assembles the local rhs for a given cell.
void setup_assemblers () override
sets up the vector of assembler functions
void copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > &copy_data) override
Copies local cell information to global matrix.
void copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > &copy_data) override
Copies local cell rhs information to global rhs.
virtual void output_field_hook (DataOut< dim > &data_out) override
a function for adding data vectors to the data_out object for post_processing additional results
void percolate_void_fraction ()
Protected Member Functions inherited from GLSNavierStokesSolver< dim >
virtual void setup_dofs_fd () override
setup_dofs_fd Setup the degree of freedom, system matrix and solution vectors Navier-Stokes problem
void update_boundary_conditions ()
update non zero constraint if the boundary is time-dependent
virtual void set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart=false) override
Sets the initial condition for the solver.
virtual void assemble_system_matrix_without_preconditioner ()
Assembles the matrix associated with the solver without computing the preconditioner.
virtual void update_multiphysics_time_average_solution () override
Updates the average velocity field solution in the multiphyscics interface.
void setup_preconditioner ()
Set-up the appropriate preconditioner.
void define_non_zero_constraints ()
defined the non zero constraints used to solve the problem.
void define_zero_constraints ()
defined the zero_constraints used to solved the problem.
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
Call for the assembly of the linear system of equation.
Protected Member Functions inherited from NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual TrilinosWrappers::MPI::Vector & get_evaluation_point () override
Getter methods to get the private attributes for the physic currently solved.
virtual TrilinosWrappers::MPI::Vector & get_local_evaluation_point () override
virtual TrilinosWrappers::MPI::Vector & get_newton_update () override
virtual TrilinosWrappers::MPI::Vector & get_present_solution () override
virtual TrilinosWrappers::MPI::Vector & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
void finish_simulation ()
finish_simulation Finish the simulation by calling all the post-processing elements that are required
virtual void postprocess (bool first_iteration)
postprocess Post-process simulation after an iteration
virtual void set_initial_condition (Parameters::InitialConditionType initial_condition_type, bool restart=false)
set_initial_conditions
virtual void finish_time_step ()
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
virtual void percolate_time_vectors_fd ()
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
void finish_simulation_fd ()
finish_simulation Finishes the simulation for fluid dynamics by calling the post-processing elements that are required
virtual void postprocess_fd (bool first_iteration)
postprocess Post-process fluid dynamics after an iteration
void postprocessing_forces (const TrilinosWrappers::MPI::Vector &evaluation_point)
postprocessing_forces Post-processing function Outputs the forces acting on each boundary condition
void postprocessing_torques (const TrilinosWrappers::MPI::Vector &evaluation_point)
postprocessing_torques Post-processing function Outputs the torque acting on each boundary condition
virtual void dynamic_flow_control ()
dynamic_flow_control If set to enable, dynamic_flow_control allows to control the flow by executing space-average velocity and beta coefficient force calculation at each time step.
void box_refine_mesh ()
Allow the initial refinement of all cells of the principal mesh that are partially contained in one of the cells of the box refinement mesh given in the parameter.
virtual void refine_mesh ()
Allow the refinement of the mesh according to one of the 2 methods proposed.
void refine_mesh_kelly ()
Allow the refinement of the mesh based on the Kelly error estimator. See : https://www.dealii.org/current/doxygen/deal.II/classKellyErrorEstimator.html for more information on the Kelly error estimator.
void refine_mesh_uniform ()
Allow the uniform refinement of all the mesh.
virtual void read_checkpoint ()
read_checkpoint
void set_nodal_values ()
set_nodal_values Set the nodal values of velocity and pressure
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
Check if a specifique boundary condition exist.
void establish_solid_domain (const bool non_zero_constraints)
Turns regions of the mesh where the material_id=1 to a solid block by injecting it into the constraints This is achieved by imposing $\mathbf{u}=0$ within the cells which have a material_id=1. In addition, solid cells which are not connected to the fluid by any means also get a pressure dirichlet boundary condition which fixes the pressure to 0. This ensures that the linear system is well-posed. Right now, this routine only supports the usage of 1 solid domain, but eventually it could be extended to more than one. By default, the fluid domain is assumed to have a material_id=0 and the rest of the domains have a material_id>0.
virtual void write_checkpoint ()
write_checkpoint
void write_output_results (const TrilinosWrappers::MPI::Vector &solution)
write_output_results Post-processing as parallel VTU files
void write_output_forces ()
write_output_forces Writes the forces per boundary condition to a text file output
void write_output_torques ()
write_output_torques Writes the torques per boundary condition to a text file output
void rescale_pressure_dofs_in_newton_update ()
rescale_pressure_dofs_in_newton_update This function is used to rescale pressure DOFs in the newton correction
TrilinosWrappers::MPI::Vector init_temporary_vector ()
init_temporary_vector This function initializes correctly a temporary vector depending on the vector type
Protected Attributes
CFDDEMSimulationParameters< dim > cfd_dem_simulation_parameters
DoFHandler< dim > void_fraction_dof_handler
FE_Q< dim > fe_void_fraction
MappingQGeneric< dim > particle_mapping
IndexSet locally_owned_dofs_voidfraction
IndexSet locally_relevant_dofs_voidfraction
std::vector< TrilinosWrappers::MPI::Vector > previous_void_fraction
TrilinosWrappers::MPI::Vector nodal_void_fraction_relevant
TrilinosWrappers::MPI::Vector nodal_void_fraction_owned
std::vector< std::shared_ptr< ParticleFluidAssemblerBase< dim > > > particle_fluid_assemblers
TrilinosWrappers::SparseMatrix system_matrix_void_fraction
TrilinosWrappers::MPI::Vector system_rhs_void_fraction
TrilinosWrappers::SparseMatrix complete_system_matrix_void_fraction
TrilinosWrappers::MPI::Vector complete_system_rhs_void_fraction
TrilinosWrappers::SparseMatrix mass_matrix
TrilinosWrappers::MPI::Vector diagonal_of_mass_matrix
IndexSet active_set
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
AffineConstraints< double > void_fraction_constraints
const bool PSPG = true
const bool SUPG = true
const double GLS_u_scale = 1
double pressure_drop
bool has_periodic_boundaries
Tensor< 1, dim > periodic_offset
unsigned int periodic_direction
std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > vertices_to_cell
std::map< unsigned int, std::set< typename DoFHandler< dim >::active_cell_iterator > > vertices_to_periodic_cell
Particles::ParticleHandler< dim, dim > particle_handler
Protected Attributes inherited from GLSNavierStokesSolver< dim >
TrilinosWrappers::SparseMatrix system_matrix
Protected Attributes inherited from NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
TrilinosWrappers::MPI::Vector evaluation_point
TrilinosWrappers::MPI::Vector local_evaluation_point
TrilinosWrappers::MPI::Vector newton_update
TrilinosWrappers::MPI::Vector present_solution
TrilinosWrappers::MPI::Vector system_rhs
std::vector< TrilinosWrappers::MPI::Vector > previous_solutions
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, TrilinosWrappers::MPI::Vector, IndexSet > > average_velocities
TrilinosWrappers::MPI::Vector average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::vector< Tensor< 1, dim > > > forces_on_boundaries
std::vector< Tensor< 1, 3 > > torques_on_boundaries
std::vector< TableHandler > forces_tables
std::vector< TableHandler > torques_tables
Private Member Functions
void assemble_mass_matrix_diagonal (TrilinosWrappers::SparseMatrix &mass_matrix)
void update_solution_and_constraints ()
void particle_centered_method ()
void quadrature_centered_sphere_method (bool load_balance_step)
void satellite_point_method ()
void solve_L2_system_void_fraction ()
void read_dem ()
Tensor< 1, dim > get_periodic_offset_distance (unsigned int boundary_id) const
This function calculates and returns the periodic offset distance of the domain which is needed for the periodic boundary conditions using the QCM or SPM for void fraction with the GLS VANS/CFD-DEM solver. The distance is based on one of the periodic boundaries and all particle location shifted by this distance is according to this periodic boundary.
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class GLSVANSSolver< dim >
A solver class for the VANS equation using GLS stabilization
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Author
Toni EL Geitani, 2020
Definition at line 119 of file gls_vans.h.
Constructor & Destructor Documentation
GLSVANSSolver()
template<int dim> GLSVANSSolver< dim >::GLSVANSSolver (CFDDEMSimulationParameters< dim > & nsparam)
Definition at line 13 of file gls_vans.cc.
References GLSVANSSolver< dim >::cfd_dem_simulation_parameters, GLSVANSSolver< dim >::has_periodic_boundaries, maximum_number_of_previous_solutions(), BoundaryConditions::periodic, and GLSVANSSolver< dim >::previous_void_fraction.
~GLSVANSSolver()
template<int dim> GLSVANSSolver< dim >::~GLSVANSSolver
Definition at line 49 of file gls_vans.cc.
Member Function Documentation
assemble_local_system_matrix()
template<int dim> void GLSVANSSolver< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override protected virtual
Assembles the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Reimplemented from GLSNavierStokesSolver< dim >.
Definition at line 1585 of file gls_vans.cc.
References NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_particle_fluid_interactions(), NavierStokesScratchData< dim >::reinit_void_fraction(), and StabilizedMethodsTensorCopyData< dim >::reset().
assemble_local_system_rhs()
template<int dim> void GLSVANSSolver< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) override protected virtual
Assembles the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Reimplemented from GLSNavierStokesSolver< dim >.
Definition at line 1692 of file gls_vans.cc.
References NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_particle_fluid_interactions(), NavierStokesScratchData< dim >::reinit_void_fraction(), and StabilizedMethodsTensorCopyData< dim >::reset().
assemble_mass_matrix_diagonal()
template<int dim> void GLSVANSSolver< dim >::assemble_mass_matrix_diagonal (TrilinosWrappers::SparseMatrix & mass_matrix) private
Definition at line 283 of file gls_vans.cc.
assemble_system_matrix()
template<int dim> void GLSVANSSolver< dim >::assemble_system_matrix override protected virtual
Assembles the matrix associated with the solver.
Reimplemented from GLSNavierStokesSolver< dim >.
Definition at line 1546 of file gls_vans.cc.
References GLSVANSSolver< dim >::assemble_local_system_matrix(), and GLSVANSSolver< dim >::copy_local_matrix_to_global_matrix().
assemble_system_rhs()
template<int dim> void GLSVANSSolver< dim >::assemble_system_rhs override protected virtual
Assembles the rhs associated with the solver.
Reimplemented from GLSNavierStokesSolver< dim >.
Definition at line 1651 of file gls_vans.cc.
References GLSVANSSolver< dim >::assemble_local_system_rhs(), and GLSVANSSolver< dim >::copy_local_rhs_to_global_rhs().
calculate_void_fraction()
template<int dim> void GLSVANSSolver< dim >::calculate_void_fraction (const double time, bool load_balance_step) protected
Definition at line 240 of file gls_vans.cc.
References announce_string(), Parameters::function, Parameters::pcm, Parameters::qcm, and Parameters::spm.
copy_local_matrix_to_global_matrix()
template<int dim> void GLSVANSSolver< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > & copy_data) override protected virtual
Copies local cell information to global matrix.
Reimplemented from GLSNavierStokesSolver< dim >.
Definition at line 1637 of file gls_vans.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void GLSVANSSolver< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > & copy_data) override protected virtual
Copies local cell rhs information to global rhs.
Reimplemented from GLSNavierStokesSolver< dim >.
Definition at line 1745 of file gls_vans.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_rhs.
finish_time_step_fd()
template<int dim> void GLSVANSSolver< dim >::finish_time_step_fd protected virtual
finish_time_step Finishes the time step Post-processing and time stepping
Definition at line 167 of file gls_vans.cc.
References NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >::finish_time_step().
get_periodic_offset_distance()
template<int dim> Tensor<1, dim> GLSVANSSolver< dim >::get_periodic_offset_distance (unsigned int boundary_id) const inline private
This function calculates and returns the periodic offset distance of the domain which is needed for the periodic boundary conditions using the QCM or SPM for void fraction with the GLS VANS/CFD-DEM solver. The distance is based on one of the periodic boundaries and all particle location shifted by this distance is according to this periodic boundary.
Parameters
boundary_id The id of one of the periodic boundaries
Returns
The periodic offset distance
Definition at line 163 of file gls_vans.h.
initialize_void_fraction()
template<int dim> void GLSVANSSolver< dim >::initialize_void_fraction protected
Definition at line 231 of file gls_vans.cc.
iterate()
template<int dim> void GLSVANSSolver< dim >::iterate override protected virtual
iterate Do a regular CFD iteration
Reimplemented from NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >.
Definition at line 1363 of file gls_vans.cc.
References announce_string(), and PhysicsSolver< VectorType >::solve_non_linear_system().
monitor_mass_conservation()
template<int dim> void GLSVANSSolver< dim >::monitor_mass_conservation protected virtual
Definition at line 1768 of file gls_vans.cc.
References Parameters::SimulationControl::bdf1, Parameters::SimulationControl::bdf2, Parameters::SimulationControl::bdf3, bdf_coefficients(), and Parameters::SimulationControl::steady.
output_field_hook()
template<int dim> void GLSVANSSolver< dim >::output_field_hook (DataOut< dim > & data_out) override protected virtual
a function for adding data vectors to the data_out object for post_processing additional results
Reimplemented from NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >.
Definition at line 1759 of file gls_vans.cc.
particle_centered_method()
template<int dim> void GLSVANSSolver< dim >::particle_centered_method private
Definition at line 414 of file gls_vans.cc.
References DEM::dp.
percolate_void_fraction()
template<int dim> void GLSVANSSolver< dim >::percolate_void_fraction protected
Definition at line 156 of file gls_vans.cc.
quadrature_centered_sphere_method()
template<int dim> void GLSVANSSolver< dim >::quadrature_centered_sphere_method (bool load_balance_step) private
Definition at line 507 of file gls_vans.cc.
References DEM::dp, particle_circle_intersection_2d(), particle_sphere_intersection_3d(), and DEM::volumetric_contribution.
read_dem()
template<int dim> void GLSVANSSolver< dim >::read_dem private
Definition at line 176 of file gls_vans.cc.
satellite_point_method()
template<int dim> void GLSVANSSolver< dim >::satellite_point_method private
Definition at line 1049 of file gls_vans.cc.
References DEM::dp.
setup_assemblers()
template<int dim> void GLSVANSSolver< dim >::setup_assemblers override protected virtual
sets up the vector of assembler functions
Reimplemented from GLSNavierStokesSolver< dim >.
Definition at line 1377 of file gls_vans.cc.
References Parameters::beetstra, Parameters::dallavalle, Parameters::difelice, BoundaryConditions::function_weak, Parameters::gidaspow, is_bdf(), Parameters::kochhill, Parameters::modelA, Parameters::modelB, BoundaryConditions::outlet, BoundaryConditions::partial_slip, BoundaryConditions::pressure, and Parameters::rong.
setup_dofs()
template<int dim> void GLSVANSSolver< dim >::setup_dofs override protected virtual
associates the degrees of freedom to each vertex of the finite elements and initialize the void fraction
Reimplemented from NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >.
Definition at line 57 of file gls_vans.cc.
References BoundaryConditions::periodic, Parameters::qcm, NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >::setup_dofs(), and Parameters::spm.
solve()
template<int dim> void GLSVANSSolver< dim >::solve override virtual
solve Solves the Navier-Stokes problem
This functions solves the problem defined by the Navier-Stokes paramter by iterating through time or through the mesh refinements.
Reimplemented from GLSNavierStokesSolver< dim >.
Reimplemented in CFDDEMSolver< dim >.
Definition at line 1946 of file gls_vans.cc.
References Parameters::MeshAdaptation::none, read_mesh_and_manifolds(), NavierStokesBase< dim, VectorType, DofsType >::refine_mesh(), and LetheGridTools::vertices_cell_mapping().
solve_L2_system_void_fraction()
template<int dim> void GLSVANSSolver< dim >::solve_L2_system_void_fraction private
Definition at line 1288 of file gls_vans.cc.
References fluid_dynamics, and Parameters::quiet.
update_solution_and_constraints()
template<int dim> void GLSVANSSolver< dim >::update_solution_and_constraints private
Definition at line 315 of file gls_vans.cc.
vertices_cell_mapping()
template<int dim> void GLSVANSSolver< dim >::vertices_cell_mapping protected
Definition at line 399 of file gls_vans.cc.
References LetheGridTools::vertices_cell_mapping(), and LetheGridTools::vertices_cell_mapping_with_periodic_boundaries().
Member Data Documentation
active_set
template<int dim> IndexSet GLSVANSSolver< dim >::active_set protected
Definition at line 357 of file gls_vans.h.
cfd_dem_simulation_parameters
template<int dim> CFDDEMSimulationParameters<dim> GLSVANSSolver< dim >::cfd_dem_simulation_parameters protected
Member Variables
Definition at line 331 of file gls_vans.h.
complete_system_matrix_void_fraction
template<int dim> TrilinosWrappers::SparseMatrix GLSVANSSolver< dim >::complete_system_matrix_void_fraction protected
Definition at line 353 of file gls_vans.h.
complete_system_rhs_void_fraction
template<int dim> TrilinosWrappers::MPI::Vector GLSVANSSolver< dim >::complete_system_rhs_void_fraction protected
Definition at line 354 of file gls_vans.h.
diagonal_of_mass_matrix
template<int dim> TrilinosWrappers::MPI::Vector GLSVANSSolver< dim >::diagonal_of_mass_matrix protected
Definition at line 356 of file gls_vans.h.
fe_void_fraction
template<int dim> FE_Q<dim> GLSVANSSolver< dim >::fe_void_fraction protected
Definition at line 334 of file gls_vans.h.
GLS_u_scale
template<int dim> const double GLSVANSSolver< dim >::GLS_u_scale = 1 protected
Definition at line 364 of file gls_vans.h.
has_periodic_boundaries
template<int dim> bool GLSVANSSolver< dim >::has_periodic_boundaries protected
Definition at line 367 of file gls_vans.h.
ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> GLSVANSSolver< dim >::ilu_preconditioner protected
Definition at line 359 of file gls_vans.h.
locally_owned_dofs_voidfraction
template<int dim> IndexSet GLSVANSSolver< dim >::locally_owned_dofs_voidfraction protected
Definition at line 338 of file gls_vans.h.
locally_relevant_dofs_voidfraction
template<int dim> IndexSet GLSVANSSolver< dim >::locally_relevant_dofs_voidfraction protected
Definition at line 339 of file gls_vans.h.
mass_matrix
template<int dim> TrilinosWrappers::SparseMatrix GLSVANSSolver< dim >::mass_matrix protected
Definition at line 355 of file gls_vans.h.
nodal_void_fraction_owned
template<int dim> TrilinosWrappers::MPI::Vector GLSVANSSolver< dim >::nodal_void_fraction_owned protected
Definition at line 345 of file gls_vans.h.
nodal_void_fraction_relevant
template<int dim> TrilinosWrappers::MPI::Vector GLSVANSSolver< dim >::nodal_void_fraction_relevant protected
Definition at line 344 of file gls_vans.h.
particle_fluid_assemblers
template<int dim> std::vector<std::shared_ptr<ParticleFluidAssemblerBase<dim> > > GLSVANSSolver< dim >::particle_fluid_assemblers protected
Definition at line 349 of file gls_vans.h.
particle_handler
template<int dim> Particles::ParticleHandler<dim, dim> GLSVANSSolver< dim >::particle_handler protected
Definition at line 379 of file gls_vans.h.
particle_mapping
template<int dim> MappingQGeneric<dim> GLSVANSSolver< dim >::particle_mapping protected
Definition at line 336 of file gls_vans.h.
periodic_direction
template<int dim> unsigned int GLSVANSSolver< dim >::periodic_direction protected
Definition at line 369 of file gls_vans.h.
periodic_offset
template<int dim> Tensor<1, dim> GLSVANSSolver< dim >::periodic_offset protected
Definition at line 368 of file gls_vans.h.
pressure_drop
template<int dim> double GLSVANSSolver< dim >::pressure_drop protected
Definition at line 365 of file gls_vans.h.
previous_void_fraction
template<int dim> std::vector<TrilinosWrappers::MPI::Vector> GLSVANSSolver< dim >::previous_void_fraction protected
Definition at line 342 of file gls_vans.h.
PSPG
template<int dim> const bool GLSVANSSolver< dim >::PSPG = true protected
Definition at line 362 of file gls_vans.h.
SUPG
template<int dim> const bool GLSVANSSolver< dim >::SUPG = true protected
Definition at line 363 of file gls_vans.h.
system_matrix_void_fraction
template<int dim> TrilinosWrappers::SparseMatrix GLSVANSSolver< dim >::system_matrix_void_fraction protected
Definition at line 351 of file gls_vans.h.
system_rhs_void_fraction
template<int dim> TrilinosWrappers::MPI::Vector GLSVANSSolver< dim >::system_rhs_void_fraction protected
Definition at line 352 of file gls_vans.h.
vertices_to_cell
template<int dim> std::map<unsigned int, std::set<typename DoFHandler<dim>::active_cell_iterator> > GLSVANSSolver< dim >::vertices_to_cell protected
Definition at line 373 of file gls_vans.h.
vertices_to_periodic_cell
template<int dim> std::map<unsigned int, std::set<typename DoFHandler<dim>::active_cell_iterator> > GLSVANSSolver< dim >::vertices_to_periodic_cell protected
Definition at line 376 of file gls_vans.h.
void_fraction_constraints
template<int dim> AffineConstraints<double> GLSVANSSolver< dim >::void_fraction_constraints protected
Definition at line 360 of file gls_vans.h.
void_fraction_dof_handler
template<int dim> DoFHandler<dim> GLSVANSSolver< dim >::void_fraction_dof_handler protected
Definition at line 333 of file gls_vans.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/gls_vans.h
/home/runner/work/lethe/lethe/source/fem-dem/gls_vans.cc