Developer documentation for the Lethe open-source library: GLSNavierStokesSolver< dim > Class Template Reference
GLSNavierStokesSolver< dim > Class Template Reference
A solver class for the Navier-Stokes equation using GLS stabilization.
#include <gls_navier_stokes.h>
Public Member Functions
GLSNavierStokesSolver (SimulationParameters< dim > &nsparam)
~GLSNavierStokesSolver ()
virtual void solve ()
solve Solves the Navier-Stokes problem
Public Member Functions inherited from PhysicsSolver< VectorType >
PhysicsSolver (const Parameters::NonLinearSolver non_linear_solver_parameters)
virtual ~PhysicsSolver ()
void solve_non_linear_system (const bool first_iteration)
solve_non_linear_system Solves the non linear system of equations
virtual void apply_constraints ()
Applies constraints to a local_evaluation_point.
virtual double get_current_residual ()
Default way to evaluate the residual for the nonlinear solver. Some application may use more complex evaluation of the residual and override this method.
Protected Member Functions
virtual void setup_dofs_fd () override
setup_dofs_fd Setup the degree of freedom, system matrix and solution vectors Navier-Stokes problem
void update_boundary_conditions ()
update non zero constraint if the boundary is time-dependent
virtual void set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart=false) override
Sets the initial condition for the solver.
virtual void assemble_system_matrix () override
Assembles the matrix associated with the solver.
virtual void assemble_system_matrix_without_preconditioner ()
Assembles the matrix associated with the solver without computing the preconditioner.
virtual void assemble_system_rhs () override
Assemble the rhs associated with the solver.
virtual void update_multiphysics_time_average_solution () override
Updates the average velocity field solution in the multiphyscics interface.
void setup_preconditioner ()
Set-up the appropriate preconditioner.
void define_non_zero_constraints ()
defined the non zero constraints used to solve the problem.
void define_zero_constraints ()
defined the zero_constraints used to solved the problem.
virtual void assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data)
Assemble the local matrix for a given cell.
virtual void assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator &cell, NavierStokesScratchData< dim > &scratch_data, StabilizedMethodsTensorCopyData< dim > &copy_data)
Assemble the local rhs for a given cell.
virtual void setup_assemblers ()
sets up the vector of assembler functions
virtual void copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > &copy_data)
Copy local cell information to global matrix.
virtual void copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > &copy_data)
Copy local cell rhs information to global rhs.
void solve_linear_system (const bool initial_step, const bool renewed_matrix=true) override
Call for the assembly of the linear system of equation.
Protected Member Functions inherited from NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >
NavierStokesBase (SimulationParameters< dim > &nsparam)
virtual ~NavierStokesBase ()
virtual TrilinosWrappers::MPI::Vector & get_evaluation_point () override
Getter methods to get the private attributes for the physic currently solved.
virtual TrilinosWrappers::MPI::Vector & get_local_evaluation_point () override
virtual TrilinosWrappers::MPI::Vector & get_newton_update () override
virtual TrilinosWrappers::MPI::Vector & get_present_solution () override
virtual TrilinosWrappers::MPI::Vector & get_system_rhs () override
virtual AffineConstraints< double > & get_nonzero_constraints () override
void finish_simulation ()
finish_simulation Finish the simulation by calling all the post-processing elements that are required
virtual void postprocess (bool first_iteration)
postprocess Post-process simulation after an iteration
virtual void setup_dofs ()
setup_dofs
virtual void set_initial_condition (Parameters::InitialConditionType initial_condition_type, bool restart=false)
set_initial_conditions
virtual void finish_time_step ()
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
virtual void percolate_time_vectors_fd ()
finish_time_step Finishes the time step of the fluid dynamics Post-processing and time stepping
void finish_simulation_fd ()
finish_simulation Finishes the simulation for fluid dynamics by calling the post-processing elements that are required
virtual void postprocess_fd (bool first_iteration)
postprocess Post-process fluid dynamics after an iteration
void postprocessing_forces (const TrilinosWrappers::MPI::Vector &evaluation_point)
postprocessing_forces Post-processing function Outputs the forces acting on each boundary condition
void postprocessing_torques (const TrilinosWrappers::MPI::Vector &evaluation_point)
postprocessing_torques Post-processing function Outputs the torque acting on each boundary condition
virtual void dynamic_flow_control ()
dynamic_flow_control If set to enable, dynamic_flow_control allows to control the flow by executing space-average velocity and beta coefficient force calculation at each time step.
virtual void iterate ()
iterate Do a regular CFD iteration
void box_refine_mesh ()
Allow the initial refinement of all cells of the principal mesh that are partially contained in one of the cells of the box refinement mesh given in the parameter.
virtual void refine_mesh ()
Allow the refinement of the mesh according to one of the 2 methods proposed.
void refine_mesh_kelly ()
Allow the refinement of the mesh based on the Kelly error estimator. See : https://www.dealii.org/current/doxygen/deal.II/classKellyErrorEstimator.html for more information on the Kelly error estimator.
void refine_mesh_uniform ()
Allow the uniform refinement of all the mesh.
virtual void read_checkpoint ()
read_checkpoint
void set_nodal_values ()
set_nodal_values Set the nodal values of velocity and pressure
bool check_existance_of_bc (BoundaryConditions::BoundaryType bc)
Check if a specifique boundary condition exist.
void establish_solid_domain (const bool non_zero_constraints)
Turns regions of the mesh where the material_id=1 to a solid block by injecting it into the constraints This is achieved by imposing $\mathbf{u}=0$ within the cells which have a material_id=1. In addition, solid cells which are not connected to the fluid by any means also get a pressure dirichlet boundary condition which fixes the pressure to 0. This ensures that the linear system is well-posed. Right now, this routine only supports the usage of 1 solid domain, but eventually it could be extended to more than one. By default, the fluid domain is assumed to have a material_id=0 and the rest of the domains have a material_id>0.
virtual void write_checkpoint ()
write_checkpoint
void write_output_results (const TrilinosWrappers::MPI::Vector &solution)
write_output_results Post-processing as parallel VTU files
virtual void output_field_hook (DataOut< dim > &)
output_field_hook This function is to be redefined in specialized classes to adapt the output to each solver.
void write_output_forces ()
write_output_forces Writes the forces per boundary condition to a text file output
void write_output_torques ()
write_output_torques Writes the torques per boundary condition to a text file output
void rescale_pressure_dofs_in_newton_update ()
rescale_pressure_dofs_in_newton_update This function is used to rescale pressure DOFs in the newton correction
TrilinosWrappers::MPI::Vector init_temporary_vector ()
init_temporary_vector This function initializes correctly a temporary vector depending on the vector type
Protected Attributes
TrilinosWrappers::SparseMatrix system_matrix
Protected Attributes inherited from NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
MPI_Comm mpi_communicator
const unsigned int n_mpi_processes
const unsigned int this_mpi_process
std::shared_ptr< parallel::DistributedTriangulationBase< dim > > triangulation
DoFHandler< dim > dof_handler
std::shared_ptr< FESystem< dim > > fe
TimerOutput computing_timer
SimulationParameters< dim > simulation_parameters
PVDHandler pvdhandler
Function< dim > * exact_solution
std::shared_ptr< Function< dim > > forcing_function
FlowControl< dim > flow_control
AffineConstraints< double > zero_constraints
AffineConstraints< double > nonzero_constraints
TrilinosWrappers::MPI::Vector evaluation_point
TrilinosWrappers::MPI::Vector local_evaluation_point
TrilinosWrappers::MPI::Vector newton_update
TrilinosWrappers::MPI::Vector present_solution
TrilinosWrappers::MPI::Vector system_rhs
std::vector< TrilinosWrappers::MPI::Vector > previous_solutions
const unsigned int velocity_fem_degree
const unsigned int pressure_fem_degree
unsigned int number_quadrature_points
std::shared_ptr< Mapping< dim > > mapping
std::shared_ptr< Quadrature< dim > > cell_quadrature
std::shared_ptr< Quadrature< dim - 1 > > face_quadrature
std::vector< std::shared_ptr< NavierStokesAssemblerBase< dim > > > assemblers
std::shared_ptr< MultiphysicsInterface< dim > > multiphysics
std::shared_ptr< SimulationControl > simulation_control
TableHandler enstrophy_table
TableHandler kinetic_energy_table
TableHandler apparent_viscosity_table
TableHandler pressure_drop_table
TableHandler flow_rate_table
std::shared_ptr< AverageVelocities< dim, TrilinosWrappers::MPI::Vector, IndexSet > > average_velocities
TrilinosWrappers::MPI::Vector average_solution
MeshController mesh_controller
ConvergenceTable error_table
std::vector< std::vector< Tensor< 1, dim > > > forces_on_boundaries
std::vector< Tensor< 1, 3 > > torques_on_boundaries
std::vector< TableHandler > forces_tables
std::vector< TableHandler > torques_tables
Private Member Functions
void assemble_L2_projection ()
Assembles an L2_projection matrix for the velocity and the pressure. This L2 projection matrix can be used to set the initial condition for the Navier-Stokes problem.
void solve_system_GMRES (const bool initial_step, const double absolute_residual, const double relative_residual)
GMRES solver with ILU(N) preconditioning or AMG preconditioning.
void solve_system_BiCGStab (const bool initial_step, const double absolute_residual, const double relative_residual)
BiCGStab solver with ILU(N) preconditioning.
void solve_system_direct (const bool initial_step, const double absolute_residual, const double relative_residual)
Direct solver using TrilinosWrappers::SolverDirect The use of this solver should be avoided for 3D problems.
void setup_AMG ()
Set-up AMG preconditioner.
void setup_ILU ()
Set-up ILU preconditioner.
Private Attributes
SparsityPattern sparsity_pattern
std::shared_ptr< TrilinosWrappers::PreconditionILU > ilu_preconditioner
std::shared_ptr< TrilinosWrappers::PreconditionAMG > amg_preconditioner
int current_preconditioner_fill_level
int initial_preconditioner_fill_level
Additional Inherited Members
Public Attributes inherited from PhysicsSolver< VectorType >
ConditionalOStream pcout
Parameters::SimulationControl::TimeSteppingMethod time_stepping_method
Detailed Description
template<int dim>
class GLSNavierStokesSolver< dim >
A solver class for the Navier-Stokes equation using GLS stabilization.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Definition at line 43 of file gls_navier_stokes.h.
Constructor & Destructor Documentation
GLSNavierStokesSolver()
template<int dim> GLSNavierStokesSolver< dim >::GLSNavierStokesSolver (SimulationParameters< dim > & nsparam)
Definition at line 53 of file gls_navier_stokes.cc.
References Parameters::LinearSolver::amg, fluid_dynamics, GLSNavierStokesSolver< dim >::initial_preconditioner_fill_level, and NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >::simulation_parameters.
~GLSNavierStokesSolver()
template<int dim> GLSNavierStokesSolver< dim >::~GLSNavierStokesSolver
Definition at line 67 of file gls_navier_stokes.cc.
Member Function Documentation
assemble_L2_projection()
template<int dim> void GLSNavierStokesSolver< dim >::assemble_L2_projection private
Assembles an L2_projection matrix for the velocity and the pressure. This L2 projection matrix can be used to set the initial condition for the Navier-Stokes problem.
Definition at line 1191 of file gls_navier_stokes.cc.
References pressure.
assemble_local_system_matrix()
template<int dim> void GLSNavierStokesSolver< dim >::assemble_local_system_matrix (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) protected virtual
Assemble the local matrix for a given cell.
This function is used by the WorkStream class to assemble the system matrix. It is a thread safe function.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Reimplemented in GLSVANSSolver< dim >, and GLSSharpNavierStokesSolver< dim >.
Definition at line 701 of file gls_navier_stokes.cc.
References cahn_hilliard, NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, heat_transfer, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_cahn_hilliard(), NavierStokesScratchData< dim >::reinit_curvature(), NavierStokesScratchData< dim >::reinit_heat_transfer(), NavierStokesScratchData< dim >::reinit_projected_phase_fraction_gradient(), NavierStokesScratchData< dim >::reinit_vof(), StabilizedMethodsTensorCopyData< dim >::reset(), and VOF.
assemble_local_system_rhs()
template<int dim> void GLSNavierStokesSolver< dim >::assemble_local_system_rhs (const typename DoFHandler< dim >::active_cell_iterator & cell, NavierStokesScratchData< dim > & scratch_data, StabilizedMethodsTensorCopyData< dim > & copy_data) protected virtual
Assemble the local rhs for a given cell.
Parameters
cell The cell for which the local matrix is assembled.
scratch_data The scratch data which is used to store the calculated finite element information at the gauss point. See the documentation for NavierStokesScratchData for more information
copy_data The copy data which is used to store the results of the assembly over a cell
Reimplemented in GLSVANSSolver< dim >, and GLSSharpNavierStokesSolver< dim >.
Definition at line 911 of file gls_navier_stokes.cc.
References cahn_hilliard, NavierStokesScratchData< dim >::calculate_physical_properties(), StabilizedMethodsTensorCopyData< dim >::cell_is_local, heat_transfer, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, NavierStokesScratchData< dim >::reinit(), NavierStokesScratchData< dim >::reinit_cahn_hilliard(), NavierStokesScratchData< dim >::reinit_curvature(), NavierStokesScratchData< dim >::reinit_heat_transfer(), NavierStokesScratchData< dim >::reinit_projected_phase_fraction_gradient(), NavierStokesScratchData< dim >::reinit_vof(), StabilizedMethodsTensorCopyData< dim >::reset(), and VOF.
assemble_system_matrix()
template<int dim> void GLSNavierStokesSolver< dim >::assemble_system_matrix override protected virtual
Assembles the matrix associated with the solver.
Implements PhysicsSolver< VectorType >.
Reimplemented in GLSNitscheNavierStokesSolver< dim, spacedim >, GLSVANSSolver< dim >, and GLSSharpNavierStokesSolver< dim >.
Definition at line 614 of file gls_navier_stokes.cc.
assemble_system_matrix_without_preconditioner()
template<int dim> void GLSNavierStokesSolver< dim >::assemble_system_matrix_without_preconditioner protected virtual
Assembles the matrix associated with the solver without computing the preconditioner.
Definition at line 627 of file gls_navier_stokes.cc.
References GLSNavierStokesSolver< dim >::assemble_local_system_matrix(), cahn_hilliard, GLSNavierStokesSolver< dim >::copy_local_matrix_to_global_matrix(), heat_transfer, and VOF.
assemble_system_rhs()
template<int dim> void GLSNavierStokesSolver< dim >::assemble_system_rhs override protected virtual
Assemble the rhs associated with the solver.
Implements PhysicsSolver< VectorType >.
Reimplemented in GLSNitscheNavierStokesSolver< dim, spacedim >, GLSVANSSolver< dim >, and GLSSharpNavierStokesSolver< dim >.
Definition at line 831 of file gls_navier_stokes.cc.
References GLSNavierStokesSolver< dim >::assemble_local_system_rhs(), cahn_hilliard, GLSNavierStokesSolver< dim >::copy_local_rhs_to_global_rhs(), heat_transfer, and VOF.
copy_local_matrix_to_global_matrix()
template<int dim> void GLSNavierStokesSolver< dim >::copy_local_matrix_to_global_matrix (const StabilizedMethodsTensorCopyData< dim > & copy_data) protected virtual
Copy local cell information to global matrix.
Reimplemented in GLSVANSSolver< dim >, and GLSSharpNavierStokesSolver< dim >.
Definition at line 816 of file gls_navier_stokes.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_matrix.
copy_local_rhs_to_global_rhs()
template<int dim> void GLSNavierStokesSolver< dim >::copy_local_rhs_to_global_rhs (const StabilizedMethodsTensorCopyData< dim > & copy_data) protected virtual
Copy local cell rhs information to global rhs.
Reimplemented in GLSVANSSolver< dim >, and GLSSharpNavierStokesSolver< dim >.
Definition at line 1026 of file gls_navier_stokes.cc.
References StabilizedMethodsTensorCopyData< dim >::cell_is_local, StabilizedMethodsTensorCopyData< dim >::local_dof_indices, and StabilizedMethodsTensorCopyData< dim >::local_rhs.
define_non_zero_constraints()
template<int dim> void GLSNavierStokesSolver< dim >::define_non_zero_constraints protected
defined the non zero constraints used to solve the problem.
Definition at line 220 of file gls_navier_stokes.cc.
References BoundaryConditions::function, BoundaryConditions::noslip, BoundaryConditions::periodic, pressure, and BoundaryConditions::slip.
define_zero_constraints()
template<int dim> void GLSNavierStokesSolver< dim >::define_zero_constraints protected
defined the zero_constraints used to solved the problem.
Definition at line 308 of file gls_navier_stokes.cc.
References BoundaryConditions::function_weak, BoundaryConditions::outlet, BoundaryConditions::partial_slip, BoundaryConditions::periodic, BoundaryConditions::pressure, pressure, and BoundaryConditions::slip.
set_initial_condition_fd()
template<int dim> void GLSNavierStokesSolver< dim >::set_initial_condition_fd (Parameters::InitialConditionType initial_condition_type, bool restart = false) override protected virtual
Sets the initial condition for the solver.
If the simulation is restarted from a checkpoint, the initial solution setting is bypassed and the checkpoint is instead read.
Parameters
initial_condition_type The type of initial condition to be set
restart A boolean that indicates if the simulation is being restarted. if set to true, the initial conditions are never set, but are instead overriden by the read_checkpoint functionnality.
Set the initial condition using a L2 or a viscous solver
Implements NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >.
Definition at line 1043 of file gls_navier_stokes.cc.
References fluid_dynamics, Parameters::LinearSolver::gmres, Parameters::L2projection, Parameters::nodal, Parameters::ramp, read_checkpoint(), PhysicsSolver< VectorType >::solve_non_linear_system(), Parameters::SimulationControl::steady, and Parameters::viscous.
setup_AMG()
template<int dim> void GLSNavierStokesSolver< dim >::setup_AMG private
Set-up AMG preconditioner.
Definition at line 1356 of file gls_navier_stokes.cc.
References fluid_dynamics.
setup_assemblers()
template<int dim> void GLSNavierStokesSolver< dim >::setup_assemblers protected virtual
sets up the vector of assembler functions
Reimplemented in GLSVANSSolver< dim >, and GLSSharpNavierStokesSolver< dim >.
Definition at line 388 of file gls_navier_stokes.cc.
References BoundaryConditions::function_weak, Parameters::Stabilization::gls, is_bdf(), BoundaryConditions::outlet, BoundaryConditions::partial_slip, BoundaryConditions::pressure, Parameters::Stabilization::pspg_supg, and Parameters::VelocitySource::srf.
setup_dofs_fd()
template<int dim> void GLSNavierStokesSolver< dim >::setup_dofs_fd override protected virtual
setup_dofs_fd Setup the degree of freedom, system matrix and solution vectors Navier-Stokes problem
Implements NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >.
Definition at line 74 of file gls_navier_stokes.cc.
References fluid_dynamics.
setup_ILU()
template<int dim> void GLSNavierStokesSolver< dim >::setup_ILU private
Set-up ILU preconditioner.
Definition at line 1336 of file gls_navier_stokes.cc.
References fluid_dynamics.
setup_preconditioner()
template<int dim> void GLSNavierStokesSolver< dim >::setup_preconditioner protected
Set-up the appropriate preconditioner.
Definition at line 1311 of file gls_navier_stokes.cc.
References Parameters::LinearSolver::amg, fluid_dynamics, and Parameters::LinearSolver::ilu.
solve()
template<int dim> void GLSNavierStokesSolver< dim >::solve virtual
solve Solves the Navier-Stokes problem
This functions solves the problem defined by the Navier-Stokes paramter by iterating through time or through the mesh refinements.
Reimplemented in GLSNitscheNavierStokesSolver< dim, spacedim >, GLSVANSSolver< dim >, GLSSharpNavierStokesSolver< dim >, and CFDDEMSolver< dim >.
Definition at line 1692 of file gls_navier_stokes.cc.
References Parameters::MeshAdaptation::none, read_mesh_and_manifolds(), and NavierStokesBase< dim, VectorType, DofsType >::refine_mesh().
solve_linear_system()
template<int dim> void GLSNavierStokesSolver< dim >::solve_linear_system (const bool initial_step, const bool renewed_matrix = true) override protected virtual
Call for the assembly of the linear system of equation.
Parameters
initial_step Indicates if this is the first solution of the linear system. If this is the case, the non_zero version of the constraints are used for the Dirichlet boundary conditions
renewed_matrix Indicates if the matrix has been reassembled, and thus the preconditioner needs to be reassmbled.
//TODO the renewed_matrix parameters needs to be deprecated
Implements PhysicsSolver< VectorType >.
Definition at line 1274 of file gls_navier_stokes.cc.
References Parameters::LinearSolver::bicgstab, Parameters::LinearSolver::direct, fluid_dynamics, and Parameters::LinearSolver::gmres.
solve_system_BiCGStab()
template<int dim> void GLSNavierStokesSolver< dim >::solve_system_BiCGStab (const bool initial_step, const double absolute_residual, const double relative_residual) private
BiCGStab solver with ILU(N) preconditioning.
Definition at line 1559 of file gls_navier_stokes.cc.
References Parameters::extra_verbose, fluid_dynamics, Parameters::LinearSolver::ilu, and Parameters::quiet.
solve_system_direct()
template<int dim> void GLSNavierStokesSolver< dim >::solve_system_direct (const bool initial_step, const double absolute_residual, const double relative_residual) private
Direct solver using TrilinosWrappers::SolverDirect The use of this solver should be avoided for 3D problems.
Definition at line 1660 of file gls_navier_stokes.cc.
References fluid_dynamics.
solve_system_GMRES()
template<int dim> void GLSNavierStokesSolver< dim >::solve_system_GMRES (const bool initial_step, const double absolute_residual, const double relative_residual) private
GMRES solver with ILU(N) preconditioning or AMG preconditioning.
Definition at line 1429 of file gls_navier_stokes.cc.
References Parameters::LinearSolver::amg, Parameters::extra_verbose, fluid_dynamics, Parameters::LinearSolver::ilu, and Parameters::quiet.
update_boundary_conditions()
template<int dim> void GLSNavierStokesSolver< dim >::update_boundary_conditions protected
update non zero constraint if the boundary is time-dependent
Definition at line 192 of file gls_navier_stokes.cc.
update_multiphysics_time_average_solution()
template<int dim> void GLSNavierStokesSolver< dim >::update_multiphysics_time_average_solution override protected virtual
Updates the average velocity field solution in the multiphyscics interface.
Implements NavierStokesBase< dim, TrilinosWrappers::MPI::Vector, IndexSet >.
Definition at line 180 of file gls_navier_stokes.cc.
References fluid_dynamics.
Member Data Documentation
amg_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionAMG> GLSNavierStokesSolver< dim >::amg_preconditioner private
Definition at line 274 of file gls_navier_stokes.h.
current_preconditioner_fill_level
template<int dim> int GLSNavierStokesSolver< dim >::current_preconditioner_fill_level private
Definition at line 275 of file gls_navier_stokes.h.
ilu_preconditioner
template<int dim> std::shared_ptr<TrilinosWrappers::PreconditionILU> GLSNavierStokesSolver< dim >::ilu_preconditioner private
Definition at line 273 of file gls_navier_stokes.h.
initial_preconditioner_fill_level
template<int dim> int GLSNavierStokesSolver< dim >::initial_preconditioner_fill_level private
Definition at line 276 of file gls_navier_stokes.h.
sparsity_pattern
template<int dim> SparsityPattern GLSNavierStokesSolver< dim >::sparsity_pattern private
Definition at line 272 of file gls_navier_stokes.h.
system_matrix
template<int dim> TrilinosWrappers::SparseMatrix GLSNavierStokesSolver< dim >::system_matrix protected
Members
Definition at line 269 of file gls_navier_stokes.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/solvers/gls_navier_stokes.h
/home/runner/work/lethe/lethe/source/solvers/gls_navier_stokes.cc