Developer documentation for the Lethe open-source library: IBParticlesDEM< dim > Class Template Reference
IBParticlesDEM< dim > Class Template Reference
#include <ib_particles_dem.h>
Classes
struct BoundaryCellsInfo
struct DefaultDBL_MAX
struct DefaultUINT_MAX
Public Member Functions
void initialize (const std::shared_ptr< Parameters::IBParticles< dim >> &p_nsparam, const std::shared_ptr< Parameters::Lagrangian::FloatingWalls< dim >> floating_walls_parameters, const MPI_Comm &mpi_communicator_input, const std::vector< IBParticle< dim >> &particles)
Initialize the IBParticlesDEM object with the parameters, the mpi communicator and the particles.
void update_particles (const std::vector< IBParticle< dim >> &particles, double time)
Updates the boundary cells that are contact candidates for each of the particles.
void integrate_particles_motion (const double dt, const double h_max, const double h_min, const double rho, const double mu)
Integrates the dynamics of the IB_particle taking into account the contact between particles and between particles and walls.
void calculate_pp_contact_force (const double dt_dem, std::vector< Tensor< 1, 3 >> &contact_force, std::vector< Tensor< 1, 3 >> &contact_torque)
Calculates non-linear (Hertzian) particle-particle contact force.
void update_contact_candidates ()
Updates the contact candidates of all the particles.
void calculate_pw_contact_force (const double dt_dem, std::vector< Tensor< 1, 3 >> &contact_force, std::vector< Tensor< 1, 3 >> &contact_torque)
Calculates non-linear (Hertzian) particle-wall contact force.
void calculate_pp_lubrication_force (const double dt_dem, const double h_max, const double h_min, const double mu, std::vector< Tensor< 1, 3 >> &lubrication_force, std::vector< Tensor< 1, 3 >> &lubrication_torque)
Calculates particle-particle lubrication force. The force is based on the formula from Microhydrodynamics: Principles and Selected Applications by Kim, Sangtae; Karrila, Seppo J. ISBN 13: 9780750691734.
void calculate_pw_lubrication_force (const double dt_dem, const double h_max, const double h_min, const double mu, std::vector< Tensor< 1, 3 >> &lubrication_force, std::vector< Tensor< 1, 3 >> &lubrication_torque)
Calculates particle-wall lubrication force.
void update_particles_boundary_contact (const std::vector< IBParticle< dim >> &particles, const DoFHandler< dim > &dof_handler, const Quadrature< dim - 1 > &face_quadrature_formula, const Mapping< dim > &mapping)
Updates the boundary cells that are contact candidates for each of the particles.The force is based on the formula from Microhydrodynamics: Principles and Selected Applications by Kim, Sangtae; Karrila, Seppo J. ISBN 13: 9780750691734.
Public Attributes
std::vector< IBParticle< dim > > dem_particles
Private Types
enum lowest_floating_wall_indices { lowest_floating_wall_indices = 1000000 }
Private Attributes
std::shared_ptr< Parameters::IBParticles< dim > > parameters
std::shared_ptr< Parameters::Lagrangian::FloatingWalls< dim > > floating_walls_parameters
DEMSolverParameters< dim > dem_parameters {}
MPI_Comm mpi_communicator
std::shared_ptr< ParticleParticleContactForceBase< dim > > particle_particle_contact_force_object
std::vector< std::set< unsigned int > > particles_contact_candidates
std::shared_ptr< ParticleWallContactForce< dim > > particle_wall_contact_force_object
std::map< unsigned int, std::map< unsigned int, particle_particle_contact_info< dim > > > pp_contact_map
std::map< unsigned int, std::map< unsigned int, particle_wall_contact_info< dim > > > pw_contact_map
std::vector< std::vector< BoundaryCellsInfo > > boundary_cells
double cfd_time
Detailed Description
template<int dim>
class IBParticlesDEM< dim >
A solver class for the DEM used in conjunction with IB particles and gls_sharp_navier_stokes. This class defines and uses some functions of the DEM class that have been modified and simplified to be compatible with IB_particles.
Template Parameters
dim An integer that denotes the dimension of the space in which the flow is solved
Definition at line 54 of file ib_particles_dem.h.
Member Enumeration Documentation
lowest_floating_wall_indices
template<int dim> enum IBParticlesDEM::lowest_floating_wall_indices private
Enumerator
lowest_floating_wall_indices
Definition at line 256 of file ib_particles_dem.h.
Member Function Documentation
calculate_pp_contact_force()
template<int dim> void IBParticlesDEM< dim >::calculate_pp_contact_force (const double dt_dem, std::vector< Tensor< 1, 3 >> & contact_force, std::vector< Tensor< 1, 3 >> & contact_torque)
Calculates non-linear (Hertzian) particle-particle contact force.
Parameters
dt_dem The sub time stepping time step.
contact_force a vector containing the contact force between particles
contact_force a vector containing the contact torques between particles
Definition at line 126 of file ib_particles_dem.cc.
References particle_particle_contact_info< dim >::tangential_overlap.
calculate_pp_lubrication_force()
template<int dim> void IBParticlesDEM< dim >::calculate_pp_lubrication_force (const double dt_dem, const double h_max, const double h_min, const double mu, std::vector< Tensor< 1, 3 >> & lubrication_force, std::vector< Tensor< 1, 3 >> & lubrication_torque)
Calculates particle-particle lubrication force. The force is based on the formula from Microhydrodynamics: Principles and Selected Applications by Kim, Sangtae; Karrila, Seppo J. ISBN 13: 9780750691734.
Parameters
dt_dem The sub time stepping time step.
h_max The gap between the two particle.
h_min The minimal gap distance considered in the force calculation to avoid the singularity of the model.
mu The fluid viscosity.
lubrication_force a vector containing the lubrication force on the particles.
lubrication_torque a vector containing the lubrication torques on the particles.
Definition at line 312 of file ib_particles_dem.cc.
References tensor_nd_to_3d().
calculate_pw_contact_force()
template<int dim> void IBParticlesDEM< dim >::calculate_pw_contact_force (const double dt_dem, std::vector< Tensor< 1, 3 >> & contact_force, std::vector< Tensor< 1, 3 >> & contact_torque)
Calculates non-linear (Hertzian) particle-wall contact force.
Parameters
dt_dem The sub time stepping time step.
contact_force a vector containing the contact force between particles
contact_force a vector containing the contact torques between particles
Definition at line 462 of file ib_particles_dem.cc.
References particle_wall_contact_info< dim >::boundary_id, particle_wall_contact_info< dim >::normal_overlap, particle_wall_contact_info< dim >::normal_relative_velocity, IBParticlesDEM< dim >::BoundaryCellsInfo::normal_vector, point_nd_to_3d(), IBParticlesDEM< dim >::BoundaryCellsInfo::point_on_boundary, particle_wall_contact_info< dim >::tangential_overlap, particle_wall_contact_info< dim >::tangential_relative_velocity, and tensor_nd_to_3d().
calculate_pw_lubrication_force()
template<int dim> void IBParticlesDEM< dim >::calculate_pw_lubrication_force (const double dt_dem, const double h_max, const double h_min, const double mu, std::vector< Tensor< 1, 3 >> & lubrication_force, std::vector< Tensor< 1, 3 >> & lubrication_torque)
Calculates particle-wall lubrication force.
Parameters
dt_dem The sub time stepping time step.
h_max The gap between particle and the wall below which we evaluate the force.
h_min The minimal gap distance considered in the force calculation to avoid the singularity of the model.
mu The fluid viscosity.
lubrication_force a vector containing the lubrication force on the particles.
lubrication_torque a vector containing the lubrication torques on the particles.
Definition at line 645 of file ib_particles_dem.cc.
References IBParticlesDEM< dim >::BoundaryCellsInfo::normal_vector, point_nd_to_3d(), IBParticlesDEM< dim >::BoundaryCellsInfo::point_on_boundary, and tensor_nd_to_3d().
initialize()
template<int dim> void IBParticlesDEM< dim >::initialize (const std::shared_ptr< Parameters::IBParticles< dim >> & p_nsparam, const std::shared_ptr< Parameters::Lagrangian::FloatingWalls< dim >> floating_walls_parameters, const MPI_Comm & mpi_communicator_input, const std::vector< IBParticle< dim >> & particles)
Initialize the IBParticlesDEM object with the parameters, the mpi communicator and the particles.
Parameters
p_nsparam The parameters for the immersed boundary particles
dem_parameters
mpi_communicator_input The mpi communicator of the simulation.
particles The particles vector containing all the IB particles.
Definition at line 37 of file ib_particles_dem.cc.
References Parameters::Lagrangian::hertz, Parameters::Lagrangian::no_resistance, and Parameters::Lagrangian::ModelParameters::nonlinear.
integrate_particles_motion()
template<int dim> void IBParticlesDEM< dim >::integrate_particles_motion (const double dt, const double h_max, const double h_min, const double rho, const double mu)
Integrates the dynamics of the IB_particle taking into account the contact between particles and between particles and walls.
Parameters
dt The CFD time step.
h_max The gap between the two particle.
h_min The minimal gap distance considered in the force calculation to avoid the singularity of the model.
rho The fluid density.
mu The fluid viscosity.
Definition at line 767 of file ib_particles_dem.cc.
References DEM::mass, and DEM::velocity.
update_contact_candidates()
template<int dim> void IBParticlesDEM< dim >::update_contact_candidates
Updates the contact candidates of all the particles.
Definition at line 78 of file ib_particles_dem.cc.
update_particles()
template<int dim> void IBParticlesDEM< dim >::update_particles (const std::vector< IBParticle< dim >> & particles, double time)
Updates the boundary cells that are contact candidates for each of the particles.
Parameters
particles The particles vector containing all the IB particles.
time The current CFD time.
Definition at line 68 of file ib_particles_dem.cc.
update_particles_boundary_contact()
template<int dim> void IBParticlesDEM< dim >::update_particles_boundary_contact (const std::vector< IBParticle< dim >> & particles, const DoFHandler< dim > & dof_handler, const Quadrature< dim - 1 > & face_quadrature_formula, const Mapping< dim > & mapping)
Updates the boundary cells that are contact candidates for each of the particles.The force is based on the formula from Microhydrodynamics: Principles and Selected Applications by Kim, Sangtae; Karrila, Seppo J. ISBN 13: 9780750691734.
Parameters
particles The particles vector containing all the IB particles.
dof_handler The dof handler of the mesh used for the fluid simulation.
face_quadrature_formula The face quadrature formula used in the elements.
mapping The FEM mapping of the face element.
Definition at line 388 of file ib_particles_dem.cc.
References IBParticlesDEM< dim >::BoundaryCellsInfo::boundary_index, LetheGridTools::find_boundary_cells_in_sphere(), IBParticlesDEM< dim >::BoundaryCellsInfo::normal_vector, and IBParticlesDEM< dim >::BoundaryCellsInfo::point_on_boundary.
Member Data Documentation
boundary_cells
template<int dim> std::vector<std::vector<BoundaryCellsInfo> > IBParticlesDEM< dim >::boundary_cells private
Definition at line 285 of file ib_particles_dem.h.
cfd_time
template<int dim> double IBParticlesDEM< dim >::cfd_time private
Definition at line 288 of file ib_particles_dem.h.
dem_parameters
template<int dim> DEMSolverParameters<dim> IBParticlesDEM< dim >::dem_parameters {} private
Definition at line 264 of file ib_particles_dem.h.
dem_particles
template<int dim> std::vector<IBParticle<dim> > IBParticlesDEM< dim >::dem_particles
Definition at line 219 of file ib_particles_dem.h.
floating_walls_parameters
template<int dim> std::shared_ptr<Parameters::Lagrangian::FloatingWalls<dim> > IBParticlesDEM< dim >::floating_walls_parameters private
Definition at line 263 of file ib_particles_dem.h.
mpi_communicator
template<int dim> MPI_Comm IBParticlesDEM< dim >::mpi_communicator private
Definition at line 265 of file ib_particles_dem.h.
parameters
template<int dim> std::shared_ptr<Parameters::IBParticles<dim> > IBParticlesDEM< dim >::parameters private
Definition at line 261 of file ib_particles_dem.h.
particle_particle_contact_force_object
template<int dim> std::shared_ptr<ParticleParticleContactForceBase<dim> > IBParticlesDEM< dim >::particle_particle_contact_force_object private
Definition at line 268 of file ib_particles_dem.h.
particle_wall_contact_force_object
template<int dim> std::shared_ptr<ParticleWallContactForce<dim> > IBParticlesDEM< dim >::particle_wall_contact_force_object private
Definition at line 273 of file ib_particles_dem.h.
particles_contact_candidates
template<int dim> std::vector<std::set<unsigned int> > IBParticlesDEM< dim >::particles_contact_candidates private
Definition at line 270 of file ib_particles_dem.h.
pp_contact_map
template<int dim> std::map<unsigned int, std::map<unsigned int, particle_particle_contact_info<dim> > > IBParticlesDEM< dim >::pp_contact_map private
Definition at line 279 of file ib_particles_dem.h.
pw_contact_map
template<int dim> std::map<unsigned int, std::map<unsigned int, particle_wall_contact_info<dim> > > IBParticlesDEM< dim >::pw_contact_map private
Definition at line 282 of file ib_particles_dem.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/fem-dem/ib_particles_dem.h
/home/runner/work/lethe/lethe/source/fem-dem/ib_particles_dem.cc