Developer documentation for the Lethe open-source library: /home/runner/work/lethe/lethe/source/core/grids.cc File Reference
grids.cc File Reference
#include <core/boundary_conditions.h>
#include <core/grids.h>
#include <core/periodic_hills_grid.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_in.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/tria_accessor.h>
#include <fstream>
#include <iostream>
Functions
template<int dim, int spacedim>
void attach_grid_to_triangulation (parallel::DistributedTriangulationBase< dim, spacedim > &triangulation, const Parameters::Mesh &mesh_parameters)
Attaches a grid to a triangulation using mesh parameters.
template<int dim, int spacedim>
void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< dim, spacedim > &triangulation, const BoundaryConditions::BoundaryConditions< spacedim > &boundary_conditions)
Modifies the triangulation to setup periodic boundary conditions in the case of CFD simulations.
template<int dim, int spacedim>
void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< dim, spacedim > &triangulation, const Parameters::Mesh &mesh_parameters, const Parameters::Manifolds &manifolds_parameters, const bool &restart, const BoundaryConditions::BoundaryConditions< spacedim > &boundary_conditions)
Completely set-up a mesh and its manifold.
template void attach_grid_to_triangulation (parallel::DistributedTriangulationBase< 2 > &triangulation, const Parameters::Mesh &mesh_parameters)
template void attach_grid_to_triangulation (parallel::DistributedTriangulationBase< 3 > &triangulation, const Parameters::Mesh &mesh_parameters)
template void attach_grid_to_triangulation (parallel::DistributedTriangulationBase< 2, 3 > &triangulation, const Parameters::Mesh &mesh_parameters)
template void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< 2, 2 > &triangulation, const BoundaryConditions::BoundaryConditions< 2 > &boundary_conditions)
template void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< 2, 3 > &triangulation, const BoundaryConditions::BoundaryConditions< 3 > &boundary_conditions)
template void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< 3, 3 > &triangulation, const BoundaryConditions::BoundaryConditions< 3 > &boundary_conditions)
template void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< 2 > &triangulation, const Parameters::Mesh &mesh_parameters, const Parameters::Manifolds &manifolds_parameters, const bool &restart, const BoundaryConditions::BoundaryConditions< 2 > &boundary_conditions)
template void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< 3 > &triangulation, const Parameters::Mesh &mesh_parameters, const Parameters::Manifolds &manifolds_parameters, const bool &restart, const BoundaryConditions::BoundaryConditions< 3 > &boundary_conditions)
template void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< 2, 3 > &triangulation, const Parameters::Mesh &mesh_parameters, const Parameters::Manifolds &manifolds_parameters, const bool &restart, const BoundaryConditions::BoundaryConditions< 3 > &boundary_conditions)
Function Documentation
attach_grid_to_triangulation() [1/4]
template void attach_grid_to_triangulation (parallel::DistributedTriangulationBase< 2 > & triangulation, const Parameters::Mesh & mesh_parameters)
attach_grid_to_triangulation() [2/4]
template void attach_grid_to_triangulation (parallel::DistributedTriangulationBase< 2, 3 > & triangulation, const Parameters::Mesh & mesh_parameters)
attach_grid_to_triangulation() [3/4]
template void attach_grid_to_triangulation (parallel::DistributedTriangulationBase< 3 > & triangulation, const Parameters::Mesh & mesh_parameters)
attach_grid_to_triangulation() [4/4]
template<int dim, int spacedim> void attach_grid_to_triangulation (parallel::DistributedTriangulationBase< dim, spacedim > & triangulation, const Parameters::Mesh & mesh_parameters)
Attaches a grid to a triangulation using mesh parameters.
Parameters
triangulation The triangulation to which a grid is attached
mesh_parameters The mesh parameters used to decide what type of mesh or primitive is used
boundary_conditions The information about the boundary conditions id. This is used to set-up the periodicity of the domain
Definition at line 21 of file grids.cc.
References Parameters::Mesh::cylinder, Parameters::Mesh::dealii, Parameters::Mesh::file_name, Parameters::Mesh::gmsh, Parameters::Mesh::grid_arguments, Parameters::Mesh::grid_type, Parameters::Mesh::initial_refinement, PeriodicHillsGrid< dim, spacedim >::make_grid(), Parameters::Mesh::periodic_hills, Parameters::Mesh::simplex, and Parameters::Mesh::type.
read_mesh_and_manifolds() [1/4]
template void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< 2 > & triangulation, const Parameters::Mesh & mesh_parameters, const Parameters::Manifolds & manifolds_parameters, const bool & restart, const BoundaryConditions::BoundaryConditions< 2 > & boundary_conditions)
read_mesh_and_manifolds() [2/4]
template void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< 2, 3 > & triangulation, const Parameters::Mesh & mesh_parameters, const Parameters::Manifolds & manifolds_parameters, const bool & restart, const BoundaryConditions::BoundaryConditions< 3 > & boundary_conditions)
read_mesh_and_manifolds() [3/4]
template void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< 3 > & triangulation, const Parameters::Mesh & mesh_parameters, const Parameters::Manifolds & manifolds_parameters, const bool & restart, const BoundaryConditions::BoundaryConditions< 3 > & boundary_conditions)
read_mesh_and_manifolds() [4/4]
template<int dim, int spacedim> void read_mesh_and_manifolds (parallel::DistributedTriangulationBase< dim, spacedim > & triangulation, const Parameters::Mesh & mesh_parameters, const Parameters::Manifolds & manifolds_parameters, const bool & restart, const BoundaryConditions::BoundaryConditions< spacedim > & boundary_conditions)
Completely set-up a mesh and its manifold.
Parameters
triangulation The triangulation to which a grid is attached
mesh_parameters The mesh parameters used to decide what type of mesh or primitive is used
manifolds_parameters The information about the type of manifolds attached to the boundary conditions
boundary_conditions The information about the boundary conditions id. This is used to set-up the periodicity of the domain
Definition at line 308 of file grids.cc.
References attach_grid_to_triangulation(), attach_manifolds_to_triangulation(), Parameters::Mesh::gmsh, Parameters::Manifolds::id, Parameters::Mesh::initial_refinement, Parameters::Mesh::refine_until_target_size, setup_periodic_boundary_conditions(), Parameters::Mesh::simplex, Parameters::Manifolds::size, Parameters::Mesh::target_size, and Parameters::Mesh::type.
setup_periodic_boundary_conditions() [1/4]
template void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< 2, 2 > & triangulation, const BoundaryConditions::BoundaryConditions< 2 > & boundary_conditions)
setup_periodic_boundary_conditions() [2/4]
template void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< 2, 3 > & triangulation, const BoundaryConditions::BoundaryConditions< 3 > & boundary_conditions)
setup_periodic_boundary_conditions() [3/4]
template void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< 3, 3 > & triangulation, const BoundaryConditions::BoundaryConditions< 3 > & boundary_conditions)
setup_periodic_boundary_conditions() [4/4]
template<int dim, int spacedim> void setup_periodic_boundary_conditions (parallel::DistributedTriangulationBase< dim, spacedim > & triangulation, const BoundaryConditions::BoundaryConditions< spacedim > & boundary_conditions)
Modifies the triangulation to setup periodic boundary conditions in the case of CFD simulations.
Parameters
triangulation The triangulation to which a grid is attached
boundary_conditions The information about the boundary conditions id. This is used to set-up the periodicity of the domain
Definition at line 279 of file grids.cc.
References BoundaryConditions::BoundaryConditions< dim >::id, BoundaryConditions::periodic, BoundaryConditions::BoundaryConditions< dim >::periodic_direction, BoundaryConditions::BoundaryConditions< dim >::periodic_id, BoundaryConditions::BoundaryConditions< dim >::size, and BoundaryConditions::BoundaryConditions< dim >::type.