Developer documentation for the Lethe open-source library: /home/runner/work/lethe/lethe/include/core/utilities.h File Reference
utilities.h File Reference
#include <deal.II/base/conditional_ostream.h>
#include <deal.II/base/table_handler.h>
#include <deal.II/base/tensor.h>
#include <deal.II/dofs/dof_handler.h>
#include <boost/archive/text_iarchive.hpp>
#include <boost/archive/text_oarchive.hpp>
#include <regex>
Classes
class statistics
Small class that is used to store statistics (min,max,total,average) of variables that are used in simulations. This small class allows us to agglomerate the statistics instead of returning tuples. For example, this class is used to store the kinetic energy of the particles in the DEM model.
Functions
void add_statistics_to_table_handler (const std::string variable, const statistics stats, TableHandler &table)
add_statistics_to_table_handler Add statistics to a TableHandler under the indicated variable name
template<int dim, typename T >
TableHandler make_table_scalars_tensors (const std::vector< T > &independent_values, const std::string &independent_column_name, const std::vector< Tensor< 1, dim >> &dependent_vector, const std::vector< std::string > &dependent_column_name, const unsigned int display_precision)
Generate a table from a vector of scalar and a vector of tensor<1,dim>
template<int dim, typename T >
TableHandler make_table_scalars_tensors (const std::vector< T > &independent_values, const std::string &independent_column_name, const std::vector< std::vector< Tensor< 1, dim >>> &dependent_vector, const std::vector< std::string > &dependent_column_name, const unsigned int display_precision)
template<int dim>
TableHandler make_table_tensors_tensors (const std::vector< Tensor< 1, dim >> &independent_vector, const std::vector< std::string > &independent_column_name, const std::vector< Tensor< 1, dim >> &dependent_vector, const std::vector< std::string > &dependent_column_name, const unsigned int display_precision)
Generate a table from a vector of tensor<1,dim> and a vector of tensor<1,dim>
template<int dim>
TableHandler make_table_tensors_scalars (const std::vector< Tensor< 1, dim >> &independent_vector, const std::vector< std::string > &independent_column_name, const std::vector< double > &dependent_values, const std::string &dependent_column_name, const unsigned int display_precision)
Generate a table from a vector of tensor<1,dim> and a vector of tensor<1,dim>.
double calculate_point_property (const double phase, const double property0, const double property1)
Used in multiphasic simulations to calculates the equivalent properties for a given phase. Method called in quadrature points loop.
template<typename T >
int sgn (T val)
Used in the calculate_properties_ch to retrieve the sign of the phase parameter.
double calculate_point_property_cahn_hilliard (const double phase_cahn_hilliard, const double property0, const double property1)
Used in multiphasic simulations to calculates the equivalent properties for a given phase given by the Cahn-Hilliard equations. Method called in quadrature points loop.
void fill_table_from_file (TableHandler &table, const std::string file_name, const std::string delimiter=" ")
Reads a file that was built by writing a deal.II TableHandler class, and refills a TableHandler with the data in the file.
void fill_vectors_from_file (std::map< std::string, std::vector< double >> &map, const std::string file_name, const std::string delimiter=" ")
function that read a file that was build from a dealii table and fill 2 vectors. The first vector contains all the columns names and the second one contained all the column data.
void create_output_folder (const std::string &dirname)
Creates the simulation output folder.
void announce_string (const ConditionalOStream &pcout, const std::string expression, const char delimiter='-')
Prints a string and then adds a line above and below made with dashes containing as many dashes as the string has characters+1.
void serialize_table (const TableHandler &table, const std::string filename)
Serializes a table using boost serialization feature the filename should contain the desired extension.
void deserialize_table (TableHandler &table, const std::string filename)
Loads a table using boost serialization feature the filename should contain the desired extension.
std::string get_last_value_of_parameter (const std::string &file_name, const std::string &parameter_name)
get the value of a particular parameter from the contents of the input file. Return an empty string if not found. This function is used to read an individual parameter for an input file. This function is adapted from ASPECT and is mainly used in parsing the dim of the problem before creating the whole parameter parser
unsigned int get_dimension (const std::string &file_name)
Extract the dimension in which to run Lethe from the the contents of the parameter file. This is something that we need to do before processing the parameter file since we need to know whether to use the dim=2 or dim=3 instantiation of the main classes.
int get_max_number_of_boundary_conditions (const std::string &file_name)
Extract the maximum number of boundary conditions from the file. The number of boundary conditions is linked to the string "number" so this feature will need to be monitored extensively in the future.
Function Documentation
add_statistics_to_table_handler()
void add_statistics_to_table_handler (const std::string variable, const statistics stats, TableHandler & table) inline
add_statistics_to_table_handler Add statistics to a TableHandler under the indicated variable name
Definition at line 66 of file utilities.h.
References statistics::average, statistics::max, statistics::min, and statistics::total.
announce_string()
void announce_string (const ConditionalOStream & pcout, const std::string expression, const char delimiter = '-') inline
Prints a string and then adds a line above and below made with dashes containing as many dashes as the string has characters+1.
For example, if the string to be printed is "Tracer" the result will be:
Tracer
Parameters
pcout the parallel cout used to print the information
expression string that will be printed
delimiter the character used to delimit the printing. Default value is "-"
Definition at line 288 of file utilities.h.
calculate_point_property()
double calculate_point_property (const double phase, const double property0, const double property1) inline
Used in multiphasic simulations to calculates the equivalent properties for a given phase. Method called in quadrature points loop.
Parameters
phase Phase value for the given quadrature point
property0 Property value for the fluid with index 0 (fluid for phase = 0)
property1 Property value for the fluid with index 1 (fluid for phase = 1)
Definition at line 174 of file utilities.h.
calculate_point_property_cahn_hilliard()
double calculate_point_property_cahn_hilliard (const double phase_cahn_hilliard, const double property0, const double property1) inline
Used in multiphasic simulations to calculates the equivalent properties for a given phase given by the Cahn-Hilliard equations. Method called in quadrature points loop.
Parameters
phase Phase value for the given quadrature point
property0 Property value for the fluid with index 0 (fluid for phase = -1)
property1 Property value for the fluid with index 1 (fluid for phase = 1)
Definition at line 220 of file utilities.h.
References sgn().
create_output_folder()
void create_output_folder (const std::string & dirname)
Creates the simulation output folder.
Parameters
dirname Output directory name
Definition at line 247 of file utilities.cc.
deserialize_table()
void deserialize_table (TableHandler & table, const std::string filename) inline
Loads a table using boost serialization feature the filename should contain the desired extension.
Parameters
table The table to be deserialized
filename The file name (including the extension) to be used
Definition at line 320 of file utilities.h.
fill_table_from_file()
void fill_table_from_file (TableHandler & table, const std::string file_name, const std::string delimiter = " ")
Reads a file that was built by writing a deal.II TableHandler class, and refills a TableHandler with the data in the file.
Parameters
table The table to be filled. Warning ! if the table is empty, it's content will be erased.
file The path the file that will be use to fill up the table.
delimiter The delimiter used to read the table.
Definition at line 139 of file utilities.cc.
fill_vectors_from_file()
void fill_vectors_from_file (std::map< std::string, std::vector< double >> & map, const std::string file_name, const std::string delimiter = " ")
function that read a file that was build from a dealii table and fill 2 vectors. The first vector contains all the columns names and the second one contained all the column data.
Parameters
map A map used to contain the data based on the columns name.
file The path the file that will be use to fill up the table.
delimiter The delimiter used to read the table.
Definition at line 189 of file utilities.cc.
get_dimension()
unsigned int get_dimension (const std::string & file_name)
Extract the dimension in which to run Lethe from the the contents of the parameter file. This is something that we need to do before processing the parameter file since we need to know whether to use the dim=2 or dim=3 instantiation of the main classes.
Parameters
file_name The file name from which dimension is read
Definition at line 470 of file utilities.cc.
References get_last_value_of_parameter().
get_last_value_of_parameter()
std::string get_last_value_of_parameter (const std::string & file_name, const std::string & parameter_name)
get the value of a particular parameter from the contents of the input file. Return an empty string if not found. This function is used to read an individual parameter for an input file. This function is adapted from ASPECT and is mainly used in parsing the dim of the problem before creating the whole parameter parser
Parameters
file_name The file name from which to read a value
parameter_name The name of the parameter
Definition at line 386 of file utilities.cc.
get_max_number_of_boundary_conditions()
int get_max_number_of_boundary_conditions (const std::string & file_name)
Extract the maximum number of boundary conditions from the file. The number of boundary conditions is linked to the string "number" so this feature will need to be monitored extensively in the future.
Parameters
file_name The file name from which the number of boundary conditions is read
Definition at line 536 of file utilities.cc.
References get_max_value_of_parameter().
make_table_scalars_tensors() [1/2]
template<int dim, typename T > TableHandler make_table_scalars_tensors (const std::vector< T > & independent_values, const std::string & independent_column_name, const std::vector< std::vector< Tensor< 1, dim >>> & dependent_vector, const std::vector< std::string > & dependent_column_name, const unsigned int display_precision)
Definition at line 39 of file utilities.cc.
make_table_scalars_tensors() [2/2]
template<int dim, typename T > TableHandler make_table_scalars_tensors (const std::vector< T > & independent_values, const std::string & independent_column_name, const std::vector< Tensor< 1, dim >> & dependent_vector, const std::vector< std::string > & dependent_column_name, const unsigned int display_precision)
Generate a table from a vector of scalar and a vector of tensor<1,dim>
Parameters
independent_values A vector of scalar values that serve as the independent variable. For example time.
independent_column_name The name of the independent variable
dependent_vector. A vector of Tensor<1,dim> which are the dependent variable. For example force.
dependent_column_names. A vector of string which are the label of dependent tensor
display_precision. An integer which indicate the precision at which the tables are written
Definition at line 10 of file utilities.cc.
make_table_tensors_scalars()
template<int dim> TableHandler make_table_tensors_scalars (const std::vector< Tensor< 1, dim >> & independent_vector, const std::vector< std::string > & independent_column_name, const std::vector< double > & dependent_values, const std::string & dependent_column_name, const unsigned int display_precision)
Generate a table from a vector of tensor<1,dim> and a vector of tensor<1,dim>.
Parameters
independent_values A vector of Tensor<1,dim> that serve as the independent variable. For example position.
independent_column_name The name of the independent variable.
dependent_vector. A vector of scalar which are the dependent variable. For example energy.
dependent_column_names. The label of the dependent scalar.
display_precision. An integer which indicate the precision at which the tables are written.
Definition at line 111 of file utilities.cc.
make_table_tensors_tensors()
template<int dim> TableHandler make_table_tensors_tensors (const std::vector< Tensor< 1, dim >> & independent_vector, const std::vector< std::string > & independent_column_name, const std::vector< Tensor< 1, dim >> & dependent_vector, const std::vector< std::string > & dependent_column_name, const unsigned int display_precision)
Generate a table from a vector of tensor<1,dim> and a vector of tensor<1,dim>
Parameters
independent_values A vector of Tensor<1,dim> that serve as the independent variable. For example position.
independent_column_name A vector of string which are the label of the independent tensor.
dependent_vector. A vector of Tensor<1,dim> which are the dependent variable. For example force.
dependent_column_names. A vector of string which are the label of dependent tensor.
display_precision. An integer which indicate the precision at which the tables are written.
Definition at line 78 of file utilities.cc.
serialize_table()
void serialize_table (const TableHandler & table, const std::string filename) inline
Serializes a table using boost serialization feature the filename should contain the desired extension.
Parameters
table The table to be serialized
filename The file name (including the extension) to be used
Definition at line 305 of file utilities.h.
sgn()
template<typename T > int sgn (T val)
Used in the calculate_properties_ch to retrieve the sign of the phase parameter.
Template Parameters
T val argument's type
Parameters
val value of the variable for which we want to evaluate the sign
Returns
an integer -1 or 1 depending of the sign of the phase parameter
Definition at line 205 of file utilities.h.